arviz-devs/arviz

mcmcplotlib/plot_post.py
mcmcplotlib/plots.py

Issue 10 local imports

---

arviz/plots/densityplot.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py

minor improvement for plotting discrete variables and fix typos

improve plots for discrete variables

---

arviz/plots/styles/arviz-whitegrid.mplstyle
setup.py

Finally I can copy files during installation using pip

copy styles with pip

---

arviz/stats/__init__.py
arviz/stats/stats.py
arviz/tests/test_stats.py

cherry picked https://github.com/pymc-devs/pymc3/pull/2952/files
also expose psis_lw (it is quite a handy function that can be use in many diagnoistics)

small bug fix for psis_lw

---

arviz/plots/__init__.py
arviz/plots/pairplot.py
arviz/plots/plot_utils.py
arviz/plots/posteriorplot.py
arviz/tests/test_plots.py
arviz/utils/utils.py

I did the required changes for porting PyMC3's pairplot into Arviz.

Pairplot for arviz

---

arviz/plots/autocorrplot.py
arviz/plots/compareplot.py
arviz/plots/densityplot.py
arviz/plots/energyplot.py
arviz/plots/forestplot.py
arviz/plots/jointplot.py
arviz/plots/pairplot.py
arviz/plots/parallelplot.py
arviz/plots/plot_utils.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py
arviz/tests/test_plots.py

I am trying to increase consistency across plots in terms of common keywords and style. This is also an attempt to make plots auto-scale properly with figsize, this means changing the fontsize (labels, ticks, titles), linewidth and size of markers, result looks reasonable and it should be easier to improve this in future PRs.

improve consistency

---

arviz/plots/energyplot.py
arviz/plots/styles/arviz-darkgrid.mplstyle
arviz/plots/styles/arviz-whitegrid.mplstyle

improve colorblind friendliness

---

arviz/plots/pairplot.py

The colorbar only works for kind='hexbin'

add optional colorbar

---

.pylintrc
arviz/__init__.py
arviz/plots/autocorrplot.py
arviz/plots/compareplot.py
arviz/plots/densityplot.py
arviz/plots/energyplot.py
arviz/plots/forestplot.py
arviz/plots/jointplot.py
arviz/plots/kdeplot.py
arviz/plots/pairplot.py
arviz/plots/parallelplot.py
arviz/plots/plot_utils.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
arviz/tests/__init__.py
arviz/tests/test_diagnostics.py
arviz/tests/test_plots.py
arviz/tests/test_stats.py
arviz/tests/test_utils.py
arviz/utils/utils.py

Trying to help tidy up for a release.  This adds a pylint file to help enforce code style.  I fixed all the warnings and errors, which turned up a few places where arguments weren't getting passed to internal functions).  
If you think this is helpful, I am happy to finish linting, and add the linter to CI.  I tried to err on the side of leaving lots of warnings enabled, which led to a few inline annotations (`# pylint disable=...`).  Also happy to disable or enable more if you'd like!  
The remaining suggested changes are [at this gist](https://gist.github.com/ColCarroll/54ed8bdd7e47d0d383e41a226ae2a6ce).  Most are because of 1 or 2 letter variable names.

Add linting framework

---

arviz/plots/__init__.py
arviz/plots/khatplot.py
arviz/stats/diagnostics.py

This PR adds into Arviz the features discussed in PyMC3 [issue](https://github.com/pymc-devs/pymc3/issues/2930) #2930.

Additional diagnostics for loo

---

README.md

This will work best after #83, but also works fine now (I activated the coveralls repository).

Add logo and badges to README

---

arviz/plots/posteriorplot.py
arviz/plots/traceplot.py

This fix a bug introduced by  #84

pass bw argument by name

---

arviz/plots/pairplot.py
arviz/plots/plot_utils.py
arviz/plots/posteriorplot.py
arviz/plots/ppcplot.py

change default figsize values, for posteriorplot, ppcplot and pairplot. And also other small changes to posteriorplot

Change default figsize values

---

arviz/plots/autocorrplot.py
arviz/plots/plot_utils.py
arviz/plots/traceplot.py

Small changes to increase the data-ink ratio :-) This also removes `get_axis`, just to increases consistency across plots.

autocorrplot: share x-y labels

---

setup.py

fix install

---

arviz/plots/forestplot.py
doc/index.rst
examples/forestplot.py
examples/jointplot.py
examples/kdeplot.py
examples/pairplot.py
examples/parallelplot.py
examples/posteriorplot.py
examples/ppcplot.py

There is now an example for every plot except `khatplot` (I do not know how to make one!)
I have also updated the choices of front page images, made those images a bit larger (they disappear (on purpose) on mobile, though), and fixed a tiny annoyance that I added in `forestplot`.

More examples

---

arviz/plots/__init__.py
arviz/plots/violintraceplot.py
arviz/tests/test_plots.py

add violintraceplot

---

README.md
scripts/Dockerfile
scripts/create_testenv.sh
scripts/start_container.sh

Add a Docker container for encapsulated development.

Add Dockerfile for containerized development

---

arviz/stats/stats.py

Basically the same as #113, but without bootstrapping

Remove the need to use bootstrapping

---

arviz/utils/xarray_utils.py

Some small edits for PyStan Xarray  function.

update re for PyStan

---

requirements-dev.txt
scripts/create_testenv.sh

Cython is needed for PyStan (and also for some of the mkl modules need it).

Use conda cython

---

arviz/plots/posteriorplot.py

In writing the docs I found a bug in mode. In summary it was expecting a dataframe instead of a numpy array. Its fix is part of this pr

Fix Bug in mode and add additional plots to posterior documentation

---

.travis.yml

Trying out this one 
https://github.com/arviz-devs/arviz/issues/153
If there's a better way let me know so I can learn!

Modify ci script to only deploy docs once

---

arviz/tests/helpers.py
arviz/tests/test_plots.py

Add posteriorplot point estimate tests

---

arviz/compat/optional_dep.py
arviz/plots/autocorrplot.py
arviz/plots/forestplot.py
arviz/plots/plot_utils.py
arviz/plots/posteriorplot.py
arviz/plots/ppcplot.py
arviz/stats/stats.py
arviz/tests/test_diagnostics.py
arviz/tests/test_plots.py
arviz/tests/test_stats.py
arviz/tests/test_utils.py
arviz/tests/test_xarray_utils.py

This remove the extra axes when row * cols > number of plots.

remove extra axes

---

.travis.yml

I'm using this pull request to test TravisCI. Please don't merge yet!
Update
--------
I believe this is good for a merge. Tested new strategy and it should work. Here are the build logs from the test.
https://travis-ci.org/arviz-devs/arviz/jobs/413130428
https://travis-ci.org/arviz-devs/arviz/jobs/413130427

Documentation Fix 2

---

arviz/plots/posteriorplot.py
arviz/plots/ppcplot.py

I was having trouble with the size of the plots specially for few variables, this works better but we should think a better solution for auto-scaling figures.
Also add option to pass axes to posteriorplot

figsize, pass ax to posteriorplot

---

arviz/plots/violintraceplot.py
arviz/tests/test_plots.py

Fix for https://github.com/arviz-devs/arviz/issues/130
WIP Traveling and don't have access to my linux desktop so can't locally. I think things are ok but TravisCI will tell me for sure

Change violinplot to xarray

---

examples/violinplot.py

Fixes https://github.com/arviz-devs/arviz/issues/174

Add violinplot example to gallery

---

arviz/plots/forestplot.py
arviz/tests/test_plots.py
doc/index.rst
examples/ridgeplot.py

ggjoy has been deprecated, and renamed joyplot to ridgeplot, for a compelling historical reason. I propose we do the same.
I did hasty find and replace job to illustrate the point. If you all agree I'll clean this up when I get home.
https://serialmentor.com/blog/2017/9/15/goodbye-joyplots

[WIP] Rename joyplot to ridgeplot

---

arviz/plots/densityplot.py

I think I rebased poorly, but the keyword was missing here!

Missing keyword argument

---

arviz/plots/pairplot.py
arviz/plots/parallelplot.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py
arviz/tests/test_plots.py
examples/pairplot.py

Also fix another bug for coords in posteriorplot and add plots in traceplot documentation.
Sorry I didn't know that github would combine PRs automatically. I got a little overambitious with this pull request

Convert Pairplot to Inference data

---

arviz/plots/energyplot.py
arviz/stats/stats.py
arviz/tests/test_plots.py
arviz/tests/test_stats.py

Fixes #124 
Tidies up a few bugs and funny spots with the old version too (in particular, `kind='hist'` looks nicer now).

Update energyplot to xarray

---

arviz/utils/xarray_utils.py

accepts only dictionaries extracted from `fit` object.
fit.extract(pars=pars, permuted=False) # results shape => draws, chains, *shape
works natively with PyStan 2.18+, but needs manual transforming for earlier version
accepts a string, a list of strings or dictionary.
For dictionary, see prior rules
str or a list of str: extracted from fit object.
fit.data[par]

add prior, posterior predictive and observed data for pystan conversion

---

arviz/plots/plot_utils.py
arviz/tests/test_plotutils.py

Per comment from @ahartikainen about var name ordering

Ensure varnames order is consistent

---

arviz/plots/ppcplot.py

This way user can choose which posterior predictive var_names correspond to which data var_names.

add data_pairs optional kw to plot_ppc

---

arviz/data/io_pystan.py
arviz/tests/test_data.py

Enables ppc also for values not really in data (e.g. transformed data).

input observed data as dictionary

---

arviz/data/io_pystan.py
arviz/plots/plot_utils.py
arviz/tests/test_data.py
arviz/tests/test_plot_utils.py

This removes unneeded odict and fixes the order in tests.

Remove odict and fix test

---

arviz/data/io_pystan.py
arviz/plots/ppcplot.py
arviz/tests/test_plots.py

This version does kde plot in one step with all the data. Basically it does plot_kde manually.

Faster plot ppc

---

arviz/data/io_pymc3.py

I find a couple of problem with linear model and single chain traces that this should fix.

small fix to posterior_to_xarray

---

arviz/data/converters.py
arviz/data/io_pymc3.py
arviz/data/io_pystan.py
arviz/plots/autocorrplot.py
arviz/plots/densityplot.py
arviz/plots/energyplot.py
arviz/plots/forestplot.py
arviz/plots/jointplot.py
arviz/plots/pairplot.py
arviz/plots/parallelplot.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py
arviz/plots/violinplot.py

Also name all arviz imports relative imports
This one was only was mostly due to my OCD. I hope you guys don't judge me too much

Remove private method

---

arviz/data/converters.py
arviz/data/io_netcdf.py
arviz/plots/autocorrplot.py
arviz/plots/densityplot.py
arviz/plots/forestplot.py
arviz/plots/jointplot.py
arviz/plots/pairplot.py
arviz/plots/parallelplot.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py
arviz/plots/violinplot.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
doc/api.rst

Addresses https://github.com/arviz-devs/arviz/issues/196
Showing one example for density plot. Let me know If this looks good and I can replicate across all other docs

Update density plots documentation

---

setup.py

Release candidate. No version to bump, so tidied the setup.py. Will merge, tag, and push to pypi once test pass.

Branch for release

---

arviz/data/io_pystan.py

Better examples and move `unpermute` to more reachable location.

fix from_pystan docstring

---

setup.py

Next PyPI release will include a long description.

Include readme in setup.py

---

doc/index.rst

Pip install arviz

---

arviz/plots/ppcplot.py

Rescale xticks and use cyan (C5) instead of brownish (C4)

minor tweaks

---

arviz/stats/diagnostics.py
arviz/stats/stats.py

Regarding https://github.com/arviz-devs/arviz/issues/271 I fixed the code paths that raised FutureWarnings from which I could detect through testing.
@ahartikainen mentioned there's a couple of cases in stats.py but I'm *not* able to see them 
If there are cases left I would be happy with any of the following (or any suggestions really)
* Tell me where they are so I can edit them
* Tell me what method they are in so I can write more tests
* Update this PR directly

Fix numpy multidimensional indexing

---

arviz/plots/jointplot.py
arviz/plots/pairplot.py
arviz/plots/posteriorplot.py
arviz/plots/traceplot.py
arviz/plots/violinplot.py

Starting down the path of converting plots to object oriented matplotlib syntax per https://github.com/arviz-devs/arviz/issues/274. Please feel free to edit this branch if you have spare time and want to help out.
I plan to have all plots converted by Friday 9 pm pst at the latest.
Updated Pairplot

Convert all plots to object oriented mpl

---

arviz/tests/test_plots.py

Converted all the tests to follow functional fixture pattern. This is a big change so please criticize or discuss as much as needed.

Functionalize tests for test_plots.py

---

arviz/tests/test_data.py

Continuation of going through the tests

Assert stricter check

---

arviz/tests/test_plots.py

A couple more PRs and I think we'll be covered here. Breaking them up so we don't get a stale branch

More test coverage

---

arviz/plots/khatplot.py
arviz/plots/pairplot.py
arviz/tests/pytest.ini
arviz/tests/test_plots.py

Found some bugs in khatplot and pairplot that are fixed as well.
Submitting for code review but should rebase after https://github.com/arviz-devs/arviz/pull/296 is merged

[WIP] More testing

---

arviz/tests/test_plot_utils.py

Fixes a test failure occuring in Ari's cmdstan branch

More order invariance

---

arviz/plots/traceplot.py
arviz/tests/test_plots.py

I had 50 warnings before this PR, and none after (travis is seeing some theano errors that I don't see).

Fix more warnings

---

doc/api.rst

To show of all the hard work you guys have been doing

Add from * methods to docs

---

arviz/plots/forestplot.py

add clip_on for n_eff

---

doc/api.rst
doc/notebooks/InferenceDataCookBook.ipynb

Added placeholders for the newer from_* methods to get the docs in faster

Inference data cookbook

---

doc/conf.py
doc/index.rst
doc/notebooks/InferenceDataCookbook.ipynb
doc/notebooks/XarrayforArviZ.ipynb

Small changes for consistency, but removed the roadmap and added the cookbook to the first page of the docs. Also linked the xarray stuff from the front page and from the cookbook.

Update documentation to point to new notebooks

---

arviz/__init__.py

Tag version for release

---

doc/notebooks/InferenceDataCookbook.ipynb
doc/sphinxext/gallery_generator.py

Also remove extra cell in cookbook
Minimally reproducible example of what was causing problem. I generated docs locally and looked through the thumbnails. If you see something I missed let me know :)
```
az.style.use('arviz-darkgrid')
centered = az.load_arviz_data('centered_eight')
coords = {'school': ['Choate', 'Deerfield']}
az.plot_pair(centered, var_names=['theta', "mu", "tau"], kind='hexbin', coords=coords,
colorbar=True, divergences=True)
import matplotlib.pyplot as plt; plt.savefig("test.png", bbox_inches="tight")
```

Fix color bar problem and sort gallery alphabetically

---

arviz/plots/autocorrplot.py
arviz/plots/compareplot.py
arviz/plots/densityplot.py
arviz/plots/energyplot.py
arviz/plots/forestplot.py
arviz/plots/jointplot.py
arviz/plots/kdeplot.py
arviz/plots/khatplot.py
arviz/plots/pairplot.py
arviz/plots/parallelplot.py
arviz/plots/plot_utils.py
arviz/plots/posteriorplot.py
arviz/plots/ppcplot.py
arviz/plots/styles/arviz-darkgrid.mplstyle
arviz/plots/styles/arviz-whitegrid.mplstyle
arviz/plots/traceplot.py
arviz/plots/violinplot.py

figure autoscale

---

CONTRIBUTING.md

Add initial draft of Contributing.md. It's basically a copy of the Pymc3 contributing.md.
Notable changes
* pyflakes was replaced with pylint
* Added instructions to include a copy of the image in the Pull Request body(? What do you call this box?)
* Added instructions for using the "save plot" feature in the tests

Contributing.MD

---

arviz/plots/forestplot.py
arviz/tests/test_plots.py

also change the order of plotting for eff_n and  r_hat and unify names with those proposed  for summary in #338

plot_forest: Do not plot eff_n or r_hat by default

---

arviz/tests/test_plots.py

I have a question on what the benefit of the conditional in the modified test is.
I commented it out and things seem to work alright. In it's original form I believe it was overriding the parameterization from the decorator, meaning that all the tests suite was really just repeating the same test over and over again. Is my understanding correct?

Fix potential bug in tests

---

arviz/plots/forestplot.py
arviz/plots/pairplot.py

This makes the forestplot layout a little nicer, and allows adjusting marker size in `plot_pair`.

Allow more customization of forest and pairplot

---

arviz/tests/helpers.py
arviz/tests/test_data.py

Also adds some permutations for input.

Fix testing for PyStan 2.17

---

arviz/tests/helpers.py
arviz/tests/test_data.py

Fixes some edge cases with 2.17 in tests.

Fix permuted loglik for PyStan tests

---

.travis.yml
scripts/create_testenv.sh

Fixes #294 
Add Travis test matrices for pystan 2.17 and latest

Add Travis test matrices for pystan 2.17 and latest

---

arviz/stats/stats.py

solved #364
My IDE agrees that this variable is not used anywhere in this function.
- remove unused variable batches in stats/summary

remove unused variable batches in stats/summary

---

arviz/stats/stats.py

- remove batches reference in document

remove stats/summary in document

---

CONTRIBUTING.md
arviz/tests/helpers.py
arviz/tests/test_data.py
arviz/tests/test_diagnostics.py
arviz/tests/test_stats.py

All xunit test class setups have been removed in favor of pytest fixture style tests. I tried to preserve the classes wherever possible to make the tests look visually the same.
Also added a statement in the contributing.md doc to state ArviZ uses functional style tests, if thats ok by all
Big change so let me know if theres any issues!

Functionalize tests

---

arviz/plots/densityplot.py
arviz/tests/test_plots.py

Use a grid _a la posteriorplot_.

density grid

---

arviz/plots/ppcplot.py

Minor fixes to the plot_ppc parameter descriptions as noted in #375

Fix parameter descriptions for plot_ppc #375

---

arviz/tests/helpers.py

add sys.platform to test cache

---

arviz/plots/plot_utils.py

Small fix to documentation of a private function.

Document returns from scale_fig_size

---

arviz/__init__.py

Try to implement #331
- log matplotlib backend
**PR In progress - need some idea on this**
e.g.
- What would you like to see in log?

init logging

---

Code_of_Conduct.MD
README.md

Add ArviZ Code of Conduct

---

arviz/data/io_pystan.py

Extra tweaking making code faster and easier to read.

faster io_pystan

---

.github/ISSUE_TEMPLATE/usage-question----insert-question-here--.md

Issue template for users with general ArviZ usage questions. 
First time I've done this. Hopefully its correct

Create an ArviZ usage issue template

---

CONTRIBUTING.md

Revamp Code Style section in CONTRIBUTING.md

---

arviz/plots/densityplot.py

This change the way the density is estimated following discussion in #403 and [discourse](https://discourse.pymc.io/t/bug-in-sample-prior-predictive/2210/6).

Density plot

---

README.md
doc/index.rst

Will merge after checks are done. I can't imagine these changes will be very controversial and I'd like to send Stefan an email by tonight.

Usage Docs link added to README and Docs Front page

---

scripts/Dockerfile
scripts/container.sh
scripts/create_testenv.sh

No changes made to CI, but added more functionality to make local dev easier.
Roadmap after this is merged
* Make python and pystan version variables much more obvious
* Change TravisCI to actually run docker containers

More docker test

---

examples/styles.py

styles example: add imports

---

arviz/tests/helpers.py
arviz/tests/test_data.py
arviz/tests/test_plots.py

Hopefully fixes (oddly) failing master branch
https://travis-ci.org/arviz-devs/arviz/builds/456930803

Fix test errors

---

arviz/data/io_emcee.py

 emcee version 3 compatibility 

---

arviz/plots/autocorrplot.py

Fixes this issue https://github.com/arviz-devs/arviz/issues/346

Add inline documentation for plot_autocorr

---

arviz/data/io_emcee.py
doc/notebooks/InferenceDataCookbook.ipynb

Add emcee and pyro cookbook examples

---

arviz/plots/pairplot.py
arviz/plots/traceplot.py

For some reason sometimes tittles get cropped, this _magically_ fix it.

fix cropped titles

---

arviz/plots/hpdplot.py

A simple change to remove the lines marking the hpd limits by default

no line by default

---

examples/plot_ppc.py
examples/plot_ppc_cumulative.py

Quick fix. Something fills up something.
Commenting both of these out, travis works.

Travis tmp fix

---

arviz/__init__.py

increase version to 0.3.1

---

paper/paper.md

Fixing YAML header

---

arviz/data/base.py

Check if library has `__version__` for attr lookup.

Refined version check for attr

---

arviz/plots/compareplot.py
arviz/tests/test_plots.py

Raise ValueError if WAIC or LOO is not present in compare_df rather than doing nothing
Add inline docs

Add docs and exception to plot compare

---

README.md

Added `-it` to start interactive shell.

Add `-it` to docker instructions

---

examples/plot_ppc.py
examples/plot_ppc_cumulative.py

[docs] Run all examples

---

arviz/plots/jointplot.py

Without this fix jointplot returns a warning

fix warning

---

README.md

Add installation instructions
https://github.com/arviz-devs/arviz/issues/481

Add more installation instructions to README

---

arviz/data/io_pystan.py
arviz/tests/test_data.py

Test some edgecases
Also removed code, that was impossible to hit (coords with parameter name)

Increase PyStan testing

---

paper/paper.bib

Rendered paper
[paper_arvixlinkedadded.pdf](https://github.com/arviz-devs/arviz/files/2730013/paper_arvixlinkedadded.pdf)

Add arvix references to paper

---

requirements-dev.txt

pytest-cov 2.6.1 released which fixes issue

Remove pytest pinned version

---

.travis.yml
arviz/plots/forestplot.py
arviz/plots/posteriorplot.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
arviz/tests/helpers.py
arviz/tests/test_data.py
arviz/tests/test_diagnostics.py
arviz/tests/test_plot_utils.py
arviz/tests/test_plots.py
arviz/tests/test_stats.py
arviz/tests/test_utils.py

Now mostly everything (excluding tfp + pymc3) that is not really hard to impossible to do is tested.
This pr does a bunch of changes.

Increase coverage

---

arviz/tests/test_stats.py

This was actually fixed by #503

fix unneeded xfail

---

arviz/__init__.py

update version number to 0.3.2

---

.travis.yml
arviz/tests/test_plots.py
arviz/tests/test_utils.py

By following recommendation in https://stackoverflow.com/questions/26875191/analyzing-coverage-of-numba-wrapped-functions
Basically it goes to numba, but returns the normal function.

Run tests without numba

---

README.md

Simple fix
badges from 
- https://github.com/openjournals/joss-reviews/issues/1143#issuecomment-454512886
- https://zenodo.org/record/2540945#.XD5kU1wzZPZ

Add JOSS and Zenodo badges

---

README.md

Simple fix. I forgot to update this.

Update CoC link

---

doc/index.rst

Add JOSS and Zenodo badges to doc

---

arviz/plots/kdeplot.py

Added a rug plot example in the inline documentation.

Added inline rugplot example #468

---

arviz/data/io_tfp.py
arviz/plots/ppcplot.py
arviz/tests/helpers.py
arviz/tests/test_data.py
arviz/tests/test_plots.py
scripts/Dockerfile

- Add tests for animation.
- removed tfp model from plotting tests. The old code was already giving inference data, but now it gives a model and list of arrays, which needs some more wrapping. And this wrapping was a bit hard to implement as a class variables. (Other libs go to convert_infererence_data, but we don't have currently no way to support it, unless tfp outputs some simple class that should contain needed information (lib + data + variables)
- tfp edgecases (one left)

Increase testing

---

arviz/tests/test_utils.py

Add test for warning when confusing varname

---

doc/api.rst

This fixes #587 to clean up the api docs.

Add from_dict, remove extra from_netcdf

---

arviz/__init__.py

Fixes #594, and brings some nice new features onto pypi.
- Plot ppc supports multiple chains (#526)
- Plot titles now wrap (#441)
- plot_density uses a grid (#379)
- emcee reader support (#550)
- Animations in plot_ppc (#546)
- Optional dictionary for stat_funcs in summary (#583)
- Can exclude variables in selections with negated variable names (#574)
- Order maintained with xarray_var_iter (#557)
- Testing very improved (multiple)
- Fix nan handling in effective sample size (#573)
- Fix kde scaling (#582)
- xticks for discrete variables (#586)
- Empty InferenceData saves consistent with netcdf (#577)
- JOSS and Zenodo badges (#537)
- Gitter badge (#548)
- Docs for combining InferenceData (#590)

Bump minor version

---

arviz/plots/forestplot.py
arviz/plots/jointplot.py
arviz/plots/pairplot.py

Related to issues  #353,  #352 and #350

Add inline documentation for forest, joint and pairplot

---

arviz/plots/__init__.py
arviz/plots/distplot.py
arviz/plots/jointplot.py
arviz/plots/plot_utils.py
arviz/plots/traceplot.py
arviz/tests/test_plot_utils.py
arviz/tests/test_plots.py
examples/plot_dist.py

Fix #146
This should not pass the tests as I change `plot_utils.get_bins`. A 2D histogram (I guess an hexbin) is missing also tests and docstring. So very early draft.

add distplot

---

doc/api.rst

Added arivz.autocorr in the API docs.

Added documentation for arviz.autocorr in API doc. #393

---

arviz/plots/densityplot.py

Remove tight_layout

---

.travis.yml
doc/_static/custom.css
examples/plot_dist.py
requirements-dev.txt
scripts/deploy_docs.sh

`travis-sphinx` is a nice project with not much code. The logic here is _almost_ the same as the logic there (they also do a check for cname, that we don't use, and tags on non-master branches).
I'm marking this as a draft: once tests pass, I would like to merge on _my_ fork to make sure nothing gets nuked.

Fix doc build, drop travis-sphinx

---

arviz/__init__.py
arviz/data/io_cmdstan.py
arviz/data/io_dict.py
arviz/plots/ppcplot.py
arviz/tests/conftest.py
arviz/tests/test_data.py
arviz/tests/test_plots.py

Start implementing logging. Part of #331.

Add logging arviz wide

---

arviz/plots/parallelplot.py
arviz/tests/test_plots.py

Made the following changes:
* Added two normalization methods, normal and minmax
* Not added the tests yet.
Please review my normalization method to ensure that the method has been implemented properly.

Added normalization in plot_parallel. Fixes #419 and #351.

---

arviz/plots/kdeplot.py

This will give exactly the same result as before but with a simpler computation (and slightly faster).

replace entropy by log

---

arviz/stats/stats.py

`loo` returns a Series, `waic` should do the same

make waic return a Series

---

scripts/create_testenv.sh

#560 should be fixed already.
EDIT: Closes #560

Unpin pip version

---

CONTRIBUTING.md
README.md
scripts/container.sh

Update CONTRIBUTING.md to guide the full development process in docker.  Closes #421

Update docker instructions

---

arviz/stats/stats.py
arviz/tests/test_stats.py

Following discussion in https://github.com/arviz-devs/arviz/issues/649

make BB-pseudo-BMA the default method

---

arviz/plots/autocorrplot.py
arviz/tests/test_plots.py

Minor fix for defaulting on small chains

Add small draw length defaulting

---

arviz/stats/diagnostics.py
arviz/tests/test_diagnostics.py
doc/api.rst

After discussion let's trim ress functionality and explicit split_ess, which is now ess_mean.
Also there was errors in docs.

Quick fix for diagnostics

---

arviz/__init__.py

Didn't perform Step 5
If no one gets to this I'll finish the remaining steps in ~8 hours or so
https://github.com/arviz-devs/arviz/wiki/ArviZ-Release-Checklist

Increment version number to 0.4.0

---

arviz/plots/energyplot.py
arviz/plots/kdeplot.py

Made the changes suggested by @OriolAbril  in #652. Still working on the plot_energy issue.

improving the legend in plot_energy #643

---

arviz/data/io_pystan.py
arviz/tests/test_data.py

fixes #675 
Added better handling for 0-size arrays and vectors. Also changed the test to trigger the error, if seen in future.

fix special 0-size bug with from_pystan

---

arviz/plots/traceplot.py

Pointed out by @rpgoldman -- looks like we copy/pasted too aggressively!

Update traceplot docstring

---

arviz/plots/forestplot.py
arviz/stats/stats.py

With this change `plot_forest(ess=True)` will report the value of ess even for 1 chain. `summary` will always report all the stats and diagnostics (rhat will be `NaN`)

Plot forest and summary reported values

---

arviz/plots/hpdplot.py
arviz/tests/helpers.py
arviz/tests/test_data.py
arviz/tests/test_data_cmdstan.py
arviz/tests/test_data_emcee.py
arviz/tests/test_data_pymc.py
arviz/tests/test_data_pyro.py
arviz/tests/test_data_pystan.py
arviz/tests/test_data_tfp.py
arviz/tests/test_plots.py

Simplify tests.
This PR enables one to test specific modules without other ones.

split tests for data module

---

arviz/data/inference_data.py
arviz/tests/test_data.py

If dim=None --> concat unique groups
Valid dim values are {"chain", "draw"}.
~Needs tests.~
~Needs examples.~ (let's update tutorial in another PR)

Advanced concat for InferenceData

---

arviz/stats/stats.py

Fixes https://github.com/arviz-devs/arviz/issues/336
Minimal changes. I think we can assume that users should use updated xarray?

ddof=1 for std

---

arviz/data/converters.py

Small fix: to converter `PosteriorSample` --> `RunSet`

Update CmdStanPy functionality

---

arviz/plots/forestplot.py

closes #599
`a` is Gaussian and `c` is Poisson
**Old version**
**New version**
**new version with `kind=hist` and `ridgeplot_alpha=0`**

ridgeplot: use histograms for discrete variables by default

---

arviz/utils.py
azure-pipelines.yml

I will inlcude 4 commits in this PR. The first one is the modifications to azure-pipelines.yml, which should pass all checks. The second will have a doc lint error, the third a black error and the third a pylint error. If all 3 fail in the same way as travis I will undo the lint errors to merge the PR.

Fix azure lint job

---

arviz/plots/forestplot.py

Follow-up to #735, making two minor "fixes" for readability.

Minor nits with plot_forest

---

examples/plot_forest_ridge.py

Replaces the existing example with a new a new one using the rugby dataset.

Rugby plot

---

arviz/plots/ppcplot.py
arviz/stats/stats.py

It changes how the number of bins is assigned for the posterior predictive mean plot

Use observations shape to estimate bins in posterior mean plot

---

arviz/plots/violinplot.py

violin plot histogram

---

README.md
arviz/data/io_cmdstanpy.py
doc/index.rst

Fixes #760 
Updated docstrings from PyCmdStan to CmdStanPy.
Added convenience functionality for log_likelihood (list / tuple lenght of 1 are unpacked).
Updated docs
Added conda-forge information for README

Update CmdStanPy related docstring / docs

---

arviz/stats/stats.py

@canyon289 do you think this is clear enough? Or would it be best to add the explanation somewhere else like the notes section?

Add note on scale use in waic and loo [GSoC]

---

.travis.yml

Skip branch tests (run the tests with PR)

don't run tests twice

---

arviz/stats/stats.py

Remove coords without dims from summary

---

arviz/tests/conftest.py
arviz/tests/helpers.py
arviz/tests/test_plots.py
arviz/tests/test_stats.py
arviz/tests/test_stats_utils.py

set numpy random seed in conftest.py and removed it from other test files.
closes #661

Set Numpy Random Seed in one place for tests

---

arviz/plots/posteriorplot.py
arviz/tests/test_plots.py

kwargs were only passed to `plt.hist` but not to `plot_kde` this should fix it.

posteriorplot kwargs bug

---

arviz/data/base.py
arviz/data/io_emcee.py
arviz/data/io_pymc3.py
arviz/data/io_pystan.py
arviz/tests/test_data_emcee.py
arviz/tests/test_data_pymc.py
arviz/tests/test_data_pystan.py

Add constant_data group

---

doc/notebooks/InferenceDataCookbook.ipynb
doc/notebooks/Numba.ipynb

Trying again
https://github.com/arviz-devs/arviz/pull/816

Fix pyro example in notebook

---

.pylintrc
arviz/tests/helpers.py
arviz/tests/test_diagnostics.py
arviz/tests/test_stats_utils.py

Added some common false positives we have.

update pylintrc disable rules

---

.gitignore

Please merge this sooner, rather than later! It's benign and these cache directories are driving me crazy! Thanks!

Ignore mypy's cache directories.

---

arviz/data/converters.py
arviz/data/io_cmdstanpy.py
arviz/tests/test_data_cmdstanpy.py

Update CmdStanPy class

---

arviz/tests/helpers.py

Added `control=dict(adapt_engaged=False)`

Fix pystan adapt_engaged

---

arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/plots/backends/bokeh/bokeh_traceplot.py
arviz/plots/backends/matplotlib/mpl_traceplot.py
arviz/plots/traceplot.py
arviz/tests/test_plots_bokeh.py

Rug + divergence
also fixes multidim input.

[Bokeh] rug and divergences to traceplot

---

arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/tests/test_plots_bokeh.py

Add quantiles to bokeh traceplot.

Add quantiles for bokeh traceplot

---

arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/plots/backends/matplotlib/mpl_kdeplot.py
arviz/tests/test_plots_bokeh.py
arviz/tests/test_plots_matplotlib.py

Checks rotated kw and changes `x <--> y`

rotated kw for kde bokeh

---

arviz/plots/mcseplot.py
examples/plot_mcse.py

Make it easier for people to understand what MCSE is

Expand MCSE acronym

---

arviz/data/io_cmdstan.py
arviz/utils.py

Fixes #901 
Added dtype argument to ``utils.full`

[bugfix] from_cmdstan dtype issue

---

arviz/__init__.py
arviz/plots/backends/__init__.py
arviz/plots/backends/bokeh/__init__,py.py
arviz/plots/backends/bokeh/__init__.py
arviz/plots/backends/bokeh/bokeh_distplot.py
arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/plots/backends/bokeh/bokeh_traceplot.py
arviz/plots/backends/matplotlib/__init__,py.py
arviz/plots/backends/matplotlib/__init__.py
arviz/plots/backends/matplotlib/mpl_distplot.py
arviz/plots/backends/matplotlib/mpl_traceplot.py
arviz/plots/distplot.py
arviz/plots/kdeplot.py
arviz/plots/traceplot.py
arviz/tests/test_plots_bokeh.py
arviz/tests/test_plots_matplotlib.py

Add options to save to file and notebook (simple wrapper + docstring overwrite)
```
from bokeh.plotting import output_notebook, output_file
```
-->
```
az.backends.bokeh.output_notebook()
az.backends.bokeh.output_file()
```

Add bokeh convenience functionality to arviz

---

arviz/plots/autocorrplot.py
arviz/plots/backends/bokeh/bokeh_autocorrplot.py
arviz/plots/backends/matplotlib/mpl_autocorrplot.py
arviz/plots/plot_utils.py

~Currently, bokeh just crashes :)~
Uses bokeh.figure.segment plot. Looking good.

split autocorrplot

---

arviz/tests/test_plots_bokeh.py

Add bokeh autocorr tests

---

arviz/plots/backends/bokeh/bokeh_compareplot.py
arviz/plots/backends/bokeh/bokeh_densityplot.py
arviz/plots/backends/bokeh/bokeh_distplot.py
arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/plots/backends/bokeh/bokeh_traceplot.py
arviz/plots/backends/matplotlib/mpl_compareplot.py
arviz/plots/backends/matplotlib/mpl_densityplot.py
arviz/plots/compareplot.py
arviz/plots/densityplot.py
arviz/tests/test_plots_bokeh.py

Quick and dirty solution.
- compare
- density

Bokeh plots for compare, density

---

arviz/plots/backends/bokeh/bokeh_compareplot.py
arviz/plots/backends/bokeh/bokeh_elpdplot.py
arviz/plots/backends/matplotlib/mpl_elpdplot.py
arviz/plots/elpdplot.py
arviz/tests/test_plots_bokeh.py

Add minimal support for elpdplot.
Multidim stuff tripped me, not sure what is in what dimension (bokeh glyph methods don't handle multidim stuff automatically).
Code style is not pretty.

Bokeh elpdplot

---

arviz/plots/backends/bokeh/bokeh_distplot.py
arviz/plots/backends/bokeh/bokeh_energyplot.py
arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/plots/backends/matplotlib/mpl_energyplot.py
arviz/plots/energyplot.py
arviz/tests/test_plots_bokeh.py

Quick and dirty implementation.

Add bokeh energyplot

---

arviz/plots/backends/bokeh/bokeh_densityplot.py
arviz/plots/forestplot.py
arviz/plots/kdeplot.py
arviz/plots/khatplot.py
arviz/plots/ppcplot.py
arviz/plots/rankplot.py
arviz/plots/violinplot.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
arviz/stats/stats_utils.py
arviz/tests/test_plots_matplotlib.py
arviz/tests/test_stats_utils.py

This should fix the warning introduced by #860

jitted histogram: fix numba compilation

---

arviz/plots/backends/bokeh/bokeh_essplot.py
arviz/plots/backends/matplotlib/mpl_essplot.py
arviz/plots/essplot.py
arviz/tests/test_plots_bokeh.py

Again, not pretty, works, missing some notations and a lot of the settings (almost all).

bokeh plot_ess

---

arviz/plots/backends/bokeh/bokeh_forestplot.py
arviz/plots/backends/matplotlib/mpl_forestplot.py
arviz/plots/forestplot.py
arviz/tests/test_plots_bokeh.py

WIP
Implement plot_forest on Bokeh.

[WIP] Bokeh plotforest

---

arviz/plots/backends/bokeh/bokeh_hpdplot.py
arviz/plots/backends/bokeh/bokeh_jointplot.py
arviz/plots/backends/matplotlib/mpl_hpdplot.py
arviz/plots/backends/matplotlib/mpl_jointplot.py
arviz/plots/hpdplot.py
arviz/plots/jointplot.py
arviz/tests/test_plots_bokeh.py

Same stuff as previous implementations. Not pretty.

Bokeh hpdplot and jointplot

---

arviz/plots/backends/bokeh/bokeh_compareplot.py
arviz/plots/backends/bokeh/bokeh_distplot.py
arviz/plots/backends/bokeh/bokeh_energyplot.py
arviz/plots/backends/bokeh/bokeh_hpdplot.py
arviz/plots/backends/bokeh/bokeh_kdeplot.py
arviz/plots/backends/bokeh/bokeh_khatplot.py
arviz/plots/backends/bokeh/bokeh_loopitplot.py
arviz/plots/backends/matplotlib/mpl_khatplot.py
arviz/plots/backends/matplotlib/mpl_loopitplot.py
arviz/plots/khatplot.py
arviz/plots/loopitplot.py
arviz/tests/test_plots_bokeh.py

Bokeh khatplot and loopitplot

---

arviz/plots/backends/bokeh/bokeh_mcseplot.py
arviz/plots/backends/matplotlib/mpl_mcseplot.py
arviz/plots/mcseplot.py
arviz/tests/test_plots_bokeh.py

Bokeh mcseplot

---

arviz/plots/backends/bokeh/bokeh_pairplot.py
arviz/plots/backends/matplotlib/mpl_pairplot.py
arviz/plots/pairplot.py
arviz/tests/test_plots_bokeh.py

Pair plot with synced data :) (selection is awesome). Ugly code :)

Bokeh pairplot

---

arviz/plots/backends/bokeh/bokeh_parallelplot.py
arviz/plots/backends/matplotlib/mpl_parallelplot.py
arviz/plots/parallelplot.py
arviz/tests/test_plots_bokeh.py

Bokeh parallel

---

arviz/plots/backends/bokeh/bokeh_rankplot.py
arviz/plots/backends/matplotlib/mpl_rankplot.py
arviz/plots/plot_utils.py
arviz/plots/rankplot.py

Rank plot (synced axes :) ). Ugly code

Bokeh rankplot

---

arviz/plots/backends/bokeh/bokeh_violinplot.py
arviz/plots/backends/matplotlib/mpl_violinplot.py
arviz/plots/violinplot.py
arviz/tests/test_plots_bokeh.py

I changed from one line to default grid.
Code is ugly.
Violinplot needs a rewrite. Like the center lines, what are those? quantiles?

Bokeh violinplot

---

arviz/tests/helpers.py

fix numpyro pickle error

---

arviz/plots/backends/bokeh/bokeh_ppcplot.py
arviz/plots/backends/matplotlib/mpl_ppcplot.py
arviz/plots/ppcplot.py
arviz/tests/test_plots_bokeh.py

Implements ppcplot with Bokeh. Ugly code.

Bokeh ppcplot

---

arviz/plots/backends/bokeh/bokeh_posteriorplot.py
arviz/plots/backends/matplotlib/mpl_posteriorplot.py
arviz/plots/posteriorplot.py
arviz/tests/test_plots_bokeh.py
arviz/tests/test_plots_matplotlib.py

Bokeh posteriorplot

---

arviz/plots/rankplot.py

Minimal change. This code is going to be changed later when we restructure plotting code, so this temporary fix should be ok.

update rows and cols location

---

arviz/tests/test_plots_bokeh.py

add missing tests for bokeh

---

arviz/plots/backends/bokeh/khatplot.py
arviz/plots/backends/bokeh/posteriorplot.py

Fixes #962
Remove cds presentation and use plain lists.

Use lists for ax.text for bokeh

---

arviz/plots/autocorrplot.py
arviz/plots/backends/bokeh/autocorrplot.py
arviz/plots/backends/bokeh/densityplot.py
arviz/plots/backends/matplotlib/autocorrplot.py
arviz/plots/backends/matplotlib/densityplot.py
arviz/plots/densityplot.py

Move axes creation from frontend to backend. (two plots: autocorr, density).

Move axes creation to backend code

---

requirements.txt

Enable numpy [ci skip]

---

arviz/__init__.py

Bump version 0.6.0 [ci skip]

---

arviz/plots/backends/__init__.py
arviz/plots/backends/bokeh/__init__.py
arviz/plots/backends/bokeh/pairplot.py
arviz/plots/backends/matplotlib/__init__.py

Enable hide-show for legend on 2 variable case.
For n-var case it would cause too much of a clutter. We can use widgets for them.

Bokeh interactive legend for pair_plot 2 variable case

---

arviz/__init__.py

bump version number to 0.6.1

---

arviz/plots/backends/matplotlib/traceplot.py

Fixes erroneous warning reported by @fonnesbeck

Fix erroneous warning in traceplot

---

.gitattributes
CHANGELOG.md

As discussed in the last lab-meeting.

add changelog

---

arviz/plots/ppcplot.py
examples/matplotlib/mpl_plot_ppc.py

Plot_ppc - KeyError: "['y'] var names are not present in dataset"

---

arviz/tests/helpers.py
requirements.txt

Remove numpy restriction

---

azurepipelines-coverage.yml

should add a coverage check in github PRs

add azure coverage yaml

---

doc/sphinxext/gallery_generator.py

Added the new line for API link documentation.
PR format?

Added the new line for the API link documentation

---

arviz/plots/autocorrplot.py
arviz/plots/backends/bokeh/autocorrplot.py
arviz/plots/backends/bokeh/forestplot.py
arviz/plots/backends/bokeh/parallelplot.py
arviz/plots/backends/bokeh/traceplot.py
arviz/plots/forestplot.py
arviz/plots/parallelplot.py
arviz/plots/traceplot.py
arviz/rcparams.py
arviz/tests/test_rcparams.py
arvizrc.template

Adding pan limits in the following plots in bokeh:
- autocorrplot
- forestplot
- parallelplot
- traceplot (y axis)
I'm not sure if this is the right way though.
fixes #959

[WIP] Add pan limit in bokeh

---

CONTRIBUTING.md

fix broken tensorflow style guide link with updated link

---

arviz/plots/hpdplot.py

Well it seems #1039 does not always works, haha. This should be a better fix.

fix hpd_plot interpolation

---

CONTRIBUTING.md

Adding some notes to make things more clear and transparent

[WIP] Add note for order of precedence of work

---

CHANGELOG.md
arviz/data/io_cmdstan.py
arviz/data/io_cmdstanpy.py
arviz/tests/test_data_cmdstan.py
arviz/tests/test_data_cmdstanpy.py

New groups for CmdStan and CmdStanPy:
PR format?

Update CmdStan & CmdStanPy groups

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Extends the contributing guide on contributing to documentation, specifically explaining how to build the documentation locally. It also tries to summarize the PR template. I find it is working quite well, however some new contributors have not used the checklist. I tried to shorten it a little to make it less daunting to see if we can yet make the template more useful.

extend guidance on working with documentation

---

arviz/data/io_pyro.py

```log_likelihood_to_xarray``` used ```dims``` instead of ```self.dims``` in ```io_pyro```.

Fix io_pyro log_likelihood dims

---

arviz/data/io_pystan.py

I have seen I only updated pystan2 log likelihood conversion. The check is needed for the original model, where log_lik_ex is not present.

Update pystan3 version of log likelihood for refitting

---

CHANGELOG.md
arviz/plots/plot_utils.py

As discussed in the channel, This PR corrects the UserWarning in `fast_kde_2d`.

Corrected warning for fast_kde_2d

---

arviz/plots/backends/matplotlib/traceplot.py
arviz/tests/test_plots_matplotlib.py

Fixes #929 . Removed bugs from traceplotlines

Removed bugs from traceplot lines

---

arviz/data/inference_data.py

fix small error in concat docs

---

CHANGELOG.md
arviz/data/base.py

Add arviz version to InferenceData attr.

Add arviz version to InferenceData attrs

---

arviz/plots/backends/__init__.py

Ignore fixed sizing_mode

---

CHANGELOG.md
arviz/plots/densityplot.py
arviz/tests/base_tests/test_plots_bokeh.py
arviz/tests/base_tests/test_plots_matplotlib.py

Fix plot_density when variables are not a subset of one another

---

.azure-pipelines/azure-pipelines-docs.yml
CHANGELOG.md
doc/sphinxext/gallery_generator.py

fix bokeh thumb generation for 2.0.0

---

.azure-pipelines/azure-pipelines-docs.yml

fix installation of bokeh additional dependencies

---

doc/sphinxext/gallery_generator.py

One day I'll try to see if Azure can build docs but not upload in PRs.

missed some export_png instances

---

.azure-pipelines/azure-pipelines-base.yml
.azure-pipelines/azure-pipelines-external.yml

Codecov bash uploader

---

CHANGELOG.md

Add info for #1135

---

requirements-docs.txt

force m2r compatible Sphinx

---

arviz/stats/diagnostics.py
requirements-dev.txt

There was something wrong in the embedded latex code that I had to fix.
Also there were some missing requirements from requirements-dev.

Fix issues with ESS docstring.

---

.gitattributes
requirements-dev.txt

Line endings

---

arviz/plots/khatplot.py
arviz/plots/plot_utils.py
arviz/tests/base_tests/test_plot_utils.py

To transform colors in plotting functions to hex. 
To fix #956

To transform colors in plotting functions to hex

---

scripts/README.md

Adding small README for scripts . Feel free to edit if you think my descriptions are terrible

[WIP] Add scripts readme

---

scripts/README.md

Fix typo and add explanation for container.ps1

Improve scripts readme

---

arviz/plots/backends/matplotlib/forestplot.py
arviz/tests/base_tests/test_plots_matplotlib.py

fix ridgeplot failure for discrete variables

---

arviz/stats/stats.py
arviz/wrappers/wrap_pystan.py
doc/api.rst
doc/developer_guide.rst

I need the page for hpd to exist for pymc docs to link to it :sweat_smile:, I have also taken advantage of intersphinx to add a clickable link to hdi so users can access it faster.

minor changes to docs

---

CHANGELOG.md
arviz/__init__.py

Bump minor version to "0.8.0"

---

doc/conf.py

use dev as version in docs

---

CHANGELOG.md
arviz/__init__.py
arviz/tests/external_tests/test_data_pymc.py

bump patch version

---

elections/ArviZ_2020.md
elections/README.md

Ignore governance.md. Will rebase once we merge that

[WIP] Election 2020

---

GOVERNANCE.md

update governance to match description in election.md

---

GOVERNANCE.md

Adding core contributors per process detailed in https://github.com/arviz-devs/arviz/blob/master/elections/ArviZ_2020.md
If there is any comment or question make a comment in this PR

Add core contributors

---

elections/ArviZ_2020.md

Adding issue ticket for Nominations for historical tracking

Add log for Nomination Process

---

CHANGELOG.md
arviz/__init__.py

This PR increments the version number to 0.9.0 and updates the CHANGELOG. 
When tests pass, I'll merge into master and create a new release 🎉

Set up 0.9.0 Release 

---

README.md

Add NF badge

---

examples/bokeh/bokeh_plot_bpv_tstat.py

Fixes broken doc build. Should have been included with that other PR but I forgot

Fix the other broken example

---

doc/developer_guide.rst

impove developer guide and fix intersphinx mistake

---

GOVERNANCE.md

Update council number pending election results

Update Council number

---

elections/ArviZ_2020.md

Update ArviZ election doc with result

---

scripts/Dockerfile

add jags dependency to docker

---

scripts/container.sh
scripts/create_testenv.sh

Working on getting build container to work. Addresses this issue and perhaps some more as I work on this
https://github.com/arviz-devs/arviz/issues/1303

Fix docker environment for development

---

requirements.txt

Fix matplotlib to <3.3 version until we have time to fix the incompatibilities with 3.3 version.

pin matplotlib until fix

---

doc/api.rst

add plot_bpv to api section

---

arviz/plots/ppcplot.py

Fix commented line from posterior predictive docs

---

doc/index.rst

Nicole Foster noticed that the contributing guide was not easy to reach from the home page. I also added it a link to gitter.

add contributing guide to homepage

---

CHANGELOG.md
arviz/data/datasets.py
arviz/data/inference_data.py
arviz/plots/distcomparisonplot.py
arviz/plots/khatplot.py
arviz/plots/loopitplot.py
arviz/plots/ppcplot.py
doc/api.rst
examples/bokeh/bokeh_plot_ess_quantile.py
examples/bokeh/bokeh_plot_loo_pit_ecdf.py
examples/matplotlib/mpl_plot_ess_quantile.py
examples/matplotlib/mpl_plot_loo_pit_ecdf.py

update radon dataset

---

doc/index.rst

Make contributing blurb more prominent

Move contributing blurb up

---

CHANGELOG.md
arviz/stats/stats_utils.py

I think we can remove the warning already plus it will make the stancon presentation look nicer.

remove warning in ic print

---

CONTRIBUTING.md

fixed virtual env. link in contributing.md

---

arviz/numeric_utils.py

Correct order of operations

---

arviz/tests/external_tests/test_data_cmdstanpy.py

Add iter_samples to SamplerArgs.

Update CmdStanPy model

---

arviz/data/inference_data.py
arviz/tests/base_tests/test_data.py

In continuation with the #1223 and #1254 . Related to #1066 . FIx #1239

Add custom methods for InferenceData

---

.azure-pipelines/azure-pipelines-base.yml
.azure-pipelines/azure-pipelines-benchmarks.yml
.azure-pipelines/azure-pipelines-docs.yml
.azure-pipelines/azure-pipelines-external.yml
.azure-pipelines/azure-pipelines-wheel.yml

Use Python 3.8.
Install `wheel` after `pip` update.

Update testing workflow

---

CHANGELOG.md

Add links to changelog

---

arviz/data/inference_data.py
arviz/data/io_pystan.py
arviz/plots/backends/matplotlib/traceplot.py
arviz/plots/distplot.py
arviz/tests/base_tests/test_plot_utils.py
arviz/tests/base_tests/test_plots_matplotlib.py
doc/conf.py
doc/sphinxext/gallery_generator.py
examples/matplotlib/mpl_plot_trace_circ.py

Small changes to clean up codebase.
Fix concat order.
Use lists in attrs.

Clean code

---

arviz/data/__init__.py
arviz/data/base.py
arviz/data/inference_data.py
arviz/data/io_json.py
arviz/tests/base_tests/test_data.py
requirements-optional.txt

As per discussed in the channel, this PR implements the methods `from_json` and `to_json`.

Add JSON converter

---

arviz/data/inference_data.py
arviz/data/io_pymc3.py
arviz/plots/backends/bokeh/__init__.py
arviz/plots/plot_utils.py
arviz/rcparams.py
arviz/stats/stats_utils.py
arviz/utils.py

Fixes pylint errors for raise from that are causing CI failures
For those curious heres the difference

Fix raise from

---

arviz/tests/external_tests/test_data_cmdstanpy.py

Change method for cmdstanpy

---

arviz/data/io_pymc3.py
arviz/tests/external_tests/test_data_cmdstanpy.py
arviz/tests/external_tests/test_data_pymc.py

Check mask rank in missing value

---

arviz/plots/backends/bokeh/violinplot.py
arviz/plots/backends/matplotlib/violinplot.py

It is originally #1375 but I messed up with git so I opened this new PR.

Fix violin plot nan handling II

---

README.md
doc/about.rst
doc/index.rst

add donation links to readme and docs

---

.azure-pipelines/azure-pipelines-docs.yml
CHANGELOG.md
arviz/plots/backends/bokeh/essplot.py
arviz/plots/backends/bokeh/mcseplot.py
arviz/plots/backends/bokeh/rankplot.py
arviz/plots/backends/matplotlib/essplot.py
arviz/plots/backends/matplotlib/mcseplot.py
arviz/plots/backends/matplotlib/rankplot.py
arviz/plots/parallelplot.py
examples/bokeh/bokeh_plot_parallel_minmax.py
examples/bokeh/bokeh_plot_parallel_normal.py
examples/bokeh/bokeh_plot_parallel_rank.py
examples/matplotlib/mpl_plot_parallel_minmax.py
examples/matplotlib/mpl_plot_parallel_normal.py
examples/matplotlib/mpl_plot_parallel_rank.py

Add more examples plots. (normal, rankdata and minmax)
Use rankdata with `"average"`.
- Default
- minmax
- normal
- rank

[doc] Add plot_parallel examples and fix rankdata use

---

.azure-pipelines/azure-pipelines-base.yml
codecov.yml

Install with `--pre` keyword and instal xarray from github master.

Test against preview and xarray master on base tests

---

CHANGELOG.md
arviz/__init__.py

bump ArviZ minor version to 0.10.0

---

CHANGELOG.md
arviz/plots/hdiplot.py
arviz/stats/stats.py

Incorporated input_core_dims in hdi and plot_hdi docstrings 

---

arviz/__init__.py
arviz/plots/backends/matplotlib/traceplot.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
arviz/stats/stats_utils.py
arviz/utils.py
doc/api.rst
requirements-optional.txt

Start adding Dask compatibility starting from `diagnostics`/`stats` ufuncs.

[WIP] Start adding Dask support

---

arviz/stats/density_utils.py

This should make `plot_kde` to works even when the passed array has a single repeated value, and it will report a warning.

add warning when bw estimation fails and add failsafe value

---

CONTRIBUTING.md
scripts/container.sh

updating build docs for docker & updating build script for doc reorganization

---

arviz/stats/density_utils.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
arviz/stats/stats_refitting.py
arviz/stats/stats_utils.py

use f-strings in stats

---

CHANGELOG.md
arviz/__init__.py
arviz/stats/stats.py
arviz/stats/stats_utils.py

avoid repeated warning in summary

---

README.md
doc/source/about.rst
doc/source/index.rst

update numfocus donation link

---

arviz/plots/backends/bokeh/posteriorplot.py
arviz/plots/backends/matplotlib/posteriorplot.py

Fix  #842. That issue was almost solved but the circular hdi was missing.

add circular argument to hdi

---

arvizrc.template
doc/source/getting_started/Introduction.ipynb

fix #659
Add inline comment in arvizrc.template and a paragraph with a short code example in the ArviZ quickstart guide

default credible interval clarification

---

arviz/data/datasets.py

Adds references to where local datasets can be reproduced
Related to https://github.com/arviz-devs/arviz/issues/1295

Add docstring for local dataset generating code

---

arviz/plots/backends/bokeh/violinplot.py

Remove despine from bokeh violinplot. Each ax (bokeh.figure) is its own object, so we can rearrange and handle each ax individually.
Despining is confusing when user uses other than default for figure location.

Revert despine on bokeh

---

arviz/stats/stats.py

set correct types for compare DataFrame

---

CHANGELOG.md
arviz/plots/traceplot.py

Switch to `compact=True` by default in our plots #1468

Switch to `compact=True` by default

---

CHANGELOG.md
arviz/plots/elpdplot.py

plot_elpd, avoid modyfing the input dict

---

arviz/data/inference_data.py
doc/source/conf.py
doc/source/contributing/developer_guide.rst

I tried these locally and they seem to work even if intersphinx docs does not mention this.

extend docs on intersphinx

---

CHANGELOG.md
arviz/data/inference_data.py

I was surprised to find that the InferenceData object didn't have a copy method. In `inference_data.py` `copy.deepcopy()` was used. So I have added a copy method that simply calls `deepcopy`.
Possibly we should replace the other uses of deepcopy in this file with invocations of the copy method, which would make things tidier if we later were to change how `InferenceData` objects are to be copied.
This is a matter of style as much as anything: I leave it to the community to decide if it's worth doing.

Add copy() method to InferenceData

---

CHANGELOG.md
arviz/__init__.py
arviz/data/inference_data.py
examples/matplotlib/mpl_plot_violin.py

bump version to 0.11.0

---

arviz/plots/traceplot.py

Add some fixes to traceplot docstring

Add docfixes to traceplot

---

.azure-pipelines/azure-pipelines-docs.yml

Do not publish docs if broken

---

requirements-docs.txt

[docs] Update requirements-docs.txt

---

.azure-pipelines/azure-pipelines-docs.yml

Would help debug docs breaking.

Add step to doc build where we print installed packages.

---

requirements-docs.txt

Both myst-parser and myst-nb have had new bugfix releases to fix the issue we encountered
PR format?

unpin myst version

---

doc/source/about.rst
doc/source/usage.rst

fix broken quickstart link

---

.azure-pipelines/azure-pipelines-docs.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/bug-fix.md
.github/PULL_REQUEST_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE/new-feature.md
CHANGELOG.md
CONTRIBUTING.md
GOVERNANCE.md
README.md
asv_benchmarks/asv.conf.json
azure-pipelines.yml
codecov.yml
doc/source/about.rst
doc/source/conf.py
doc/source/contributing/developer_guide.rst
doc/source/index.rst
doc/source/usage.rst

Following the renaming of our default branch to main, this PR updates all the code and link
references to main.

Rename everything to main

---

arviz/tests/helpers.py

Update pyro code

---

CHANGELOG.md
arviz/__init__.py

Patch release to get plot_pair labels working again in the latest stable release.

Bump arviz version to 0.11.1

---

arviz/data/io_numpyro.py
arviz/tests/external_tests/test_data_numpyro.py

Matched sample stats to ArviZ names in `from_numpyro` converter. Addreses issue #1514

Update from_numpyro converter to follow schema convention

---

CHANGELOG.md
arviz/plots/__init__.py
arviz/plots/backends/bokeh/loopitplot.py
arviz/plots/backends/matplotlib/loopitplot.py
arviz/plots/densityplot.py
arviz/plots/forestplot.py
arviz/plots/hdiplot.py
arviz/plots/loopitplot.py
arviz/plots/posteriorplot.py
arviz/plots/violinplot.py
arviz/stats/__init__.py
arviz/stats/stats.py
arviz/tests/base_tests/test_plots_bokeh.py
arviz/tests/base_tests/test_plots_matplotlib.py
arviz/tests/base_tests/test_stats_numba.py
arviz/utils.py
doc/source/api/stats.rst

remove deprecation warnings for credible_interval and include_circ

---

arviz/data/io_pymc3.py

This PR renames Theano to Aesara.  It complements the changes in https://github.com/pymc-devs/pymc3/pull/4471.

Change Theano references to Aesara

---

.pylintrc
CHANGELOG.md
arviz/__init__.py
arviz/tests/base_tests/test_plots_matplotlib.py

Quick release to get cmdstanpy latest version to work with latest ArviZ.

Bump version to 0.11.2

---

arviz/data/base.py

closes #1560
It seemed like we wanted to remove the print statement. If not, let me know and I can change this.
Let me know if this is correct. This is my first PR to an open source library so any feed back would be great!

Remove print statement

---

.azure-pipelines/azure-pipelines-external.yml
CHANGELOG.md
arviz/data/io_cmdstanpy.py

Fix missing posterior calls and fix default log_likelihood for older versions. closes #1594

Fix cmdstanpy io

---

arviz/data/io_pystan.py

This needs httpstan and pystan (v3) updates for tests.

fix pystan3 empty arrays

---

CHANGELOG.md
arviz/stats/stats.py

fixes #1604. Removed compare warning in stats.py compare function.

removed compare warning in stats.py compare function

---

CHANGELOG.md
arviz/labels.py

change norepeat for novar labeller

---

arviz/data/inference_data.py

Remove docstrings from overload functions

---

arviz/rcparams.py
arviz/tests/base_tests/test_diagnostics.py
arvizrc.template

Not needed anymore, from_cmdstan uses numpy.

Remove pandas float_precision

---

README.md

Add pypi version badge to README

Add PyPI Version badge

---

.azure-pipelines/azure-pipelines-external.yml

Update pystan instructions

---

arviz/wrappers/base.py

Inversion of links in sampling wrappers api documentation. Fixes #1623.

Changed order of links in sampling wrapper docstrings

---

requirements-docs.txt

Pin docutils to 0.16 [docs]

---

CHANGELOG.md
arviz/stats/stats.py
arviz/tests/base_tests/test_plots_bokeh.py
arviz/tests/base_tests/test_stats.py

Renamed `sample` dim to `__sample__` when stacking in `loo` and `loo_pit` to avoid dimension collision. Related methods that require stacking `chain` and `draw` will now expect a  `__sample__` dim.
Closes #1613

Renamed `sample` dim to `__sample__` when stacking `chain` and `draw`

---

doc/source/conf.py

add analytics

---

doc/_templates/layout.html
doc/source/conf.py

This PR comes from the comments on #1667, once my PR is merged upstream (pydata-sphinx-theme) we should be able to revert these changes and everything should still work - I'm happy to provide another PR to revert this once pydata sphinx theme can handle both types of ids.

Add google analytics script with new id

---

arviz/stats/density_utils.py

Fix pylint

---

doc/_templates/layout.html
doc/source/conf.py
requirements-docs.txt

Hello again!
My PR to pydata sphinx theme was merged last week (or two). Since I had promised that I would come back and revert the changes once the PR was merged, I am creating this PR to revert the changes to adding the google analytics to the header and use the theme logic to handle the google analytics id.
I had to pin a minimum version, hope that is okay? Please let me know if you would like me to change anything. Also, my autoformatter changed some small things. Let me know if you want me to revert these.

Revert changes to add google analytics script

---

requirements-docs.txt

Temp fix for docs, until myst-nb is updated.

pin myst-parser [docs]

---

.azure-pipelines/azure-pipelines-external.yml

Change github branch for pymc3

---

doc/source/getting_started/XarrayforArviZ.ipynb

Extremely small, self-explanatory typo fix :)

Fix small typo in documentation

---

doc/source/user_guide/label_guide.rst

Hi ,
This resolves these two issues.
Please review.
As for the changes themselves, there are two to be done:
Move the ipython directive https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/label_guide.rst#L14 a few lines down. It should be right before the code (like in the rest of examples) instead of having a section title in the between.
Fix the see also directive in https://github.com/arviz-devs/arviz/blob/main/doc/source/user_guide/label_guide.rst#L58. There should be no dash and it should be indented 3 spaces.
Best,
Nikhil

Fix label guide rendering [docs]

---

doc/source/contributing/developer_guide.rst

conf.py had a broken link, just replaced that
cc: @OriolAbril

fixed broken link of conf.py

---

doc/_templates/layout.html

Adds a banner with a link to our survey to the documentation!

add banner with survey to docs

---

.azure-pipelines/azure-pipelines-external.yml
arviz/data/io_pyjags.py
arviz/stats/stats.py
arviz/stats/stats_utils.py
arviz/tests/base_tests/test_data.py
arviz/tests/base_tests/test_data_zarr.py
arviz/tests/base_tests/test_plot_utils.py
arviz/tests/base_tests/test_utils.py
arviz/tests/base_tests/test_utils_numba.py
arviz/tests/external_tests/test_data_cmdstan.py
arviz/tests/external_tests/test_data_cmdstanpy.py
arviz/tests/external_tests/test_data_emcee.py
arviz/tests/external_tests/test_data_pyjags.py
arviz/tests/external_tests/test_data_pymc.py
arviz/tests/external_tests/test_data_pystan.py
arviz/tests/external_tests/test_data_tfp.py
requirements-dev.txt

From #258  (cc @canyon289 ) :
> Also name all arviz imports relative imports
>
> This one was only was mostly due to my OCD. I hope you guys don't judge me too much
If relative imports are preferred here, why not automate them?
---
disclaimer: I'm the author of absolufy-imports

use relative imports

---

arviz/plots/backends/bokeh/kdeplot.py
arviz/plots/backends/bokeh/khatplot.py
arviz/plots/backends/bokeh/traceplot.py
arviz/plots/backends/matplotlib/elpdplot.py
arviz/plots/backends/matplotlib/khatplot.py
arviz/plots/backends/matplotlib/traceplot.py
arviz/plots/loopitplot.py
arviz/tests/external_tests/test_data_pymc.py
arviz/wrappers/wrap_stan.py

Fix many linting issues

---

doc/source/getting_started/Installation.rst

**Description:** Updated the[ Installation guide](https://arviz-devs.github.io/arviz/getting_started/Installation.html) part. 
**Note**: In order to add `python>=3.6`, should I update the `requirements.txt` or add it separately here?

Updated Installation Guide

---

CONTRIBUTING.md

Fixed typo in Contributing.md

---

doc/source/getting_started/WorkingWithInferenceData.ipynb

Updated [Working with InferenceData](https://arviz-devs.github.io/arviz/getting_started/WorkingWithInferenceData.html) part.

Updated working with inferenceData

---

doc/source/getting_started/CreatingInferenceData.ipynb

Updated [Creating InferenceData](https://arviz-devs.github.io/arviz/getting_started/CreatingInferenceData.html) part.

Updated Creating InferenceData

---

CHANGELOG.md
arviz/plots/backends/bokeh/elpdplot.py
arviz/plots/backends/matplotlib/elpdplot.py
arviz/tests/base_tests/test_plots_bokeh.py
arviz/tests/base_tests/test_plots_matplotlib.py

plot_elpd fails when there is single observation beyond the threshold. This fix that corner case.

fix plot_elpd for a single outlier

---

doc/source/getting_started/XarrayforArviZ.ipynb

Updated the [Introduction to xarray, InferenceData, and NetCDF for ArviZ](https://arviz-devs.github.io/arviz/getting_started/XarrayforArviZ.html) part.

Updated Introduction to xarray, InferenceData, and NetCDF 

---

doc/source/getting_started/Introduction.ipynb
doc/sphinxext/gallery_generator.py

Updated the [Arviz Quickstart](https://arviz-devs.github.io/arviz/getting_started/Introduction.html) part.

Updated Quickstart

---

doc/source/schema/schema.md

Updated [InferenceData schema specification](https://arviz-devs.github.io/arviz/schema/schema.html#) part.

Updated InferenceData schema specification

---

doc/source/contributing/index.md

Description:
Updating the [contributing](https://arviz-devs.github.io/arviz/contributing/index.html) guide.

Updated Contributing doc

---

doc/source/user_guide/Numba.ipynb
doc/source/user_guide/computation.md

Updated [Numba](https://arviz-devs.github.io/arviz/user_guide/Numba.html) part.

Updated numba an overview

---

doc/source/contributing/issue_reports.md

Updated the [issue reports](https://arviz-devs.github.io/arviz/contributing/issue_reports.html).

Updated issue reports

---

doc/source/user_guide/pystan2_refitting.ipynb

Description:
Updated[ Refitting PyStan (2.x) models with ArviZ](https://arviz-devs.github.io/arviz/user_guide/pystan2_refitting.html#) part.

Updated Refitting PyStan (2.x) models with ArviZ

---

doc/source/user_guide/sampling_wrappers.md

Description:
Updated [Sampling wrappers](https://arviz-devs.github.io/arviz/user_guide/sampling_wrappers.html).

Updated Sampling wrappers

---

doc/source/external_resources.md

Fixes: https://github.com/arviz-devs/arviz/issues/1815

Fixed pymc img path

---

arviz/plots/autocorrplot.py

Description:
Added references in the docstring of `plot_autocorr.py` file. 
Fixes: https://github.com/arviz-devs/arviz/issues/1809

Added references in docstring- plot_autocorr

---

CHANGELOG.md
arviz/__init__.py

Bump version number to 0.11.3

---

CHANGELOG.md
arviz/__init__.py

Bump version to 0.11.4

---

doc/source/schema/PyMC3_schema_example.ipynb

Updated the[ pymc3 example](https://arviz-devs.github.io/arviz/schema/PyMC3_schema_example.html) part.
- Tried to use simple language to leave no room for confusion.
- Used bullet points to make it more readable.

Updated pymc3 example

---

doc/source/user_guide/numpyro_refitting.ipynb

Updated the[ Refitting NumPyro models with ArviZ](https://arviz-devs.github.io/arviz/user_guide/numpyro_refitting.html) part.

Updated Refitting NumPyro models with ArviZ

---

doc/source/user_guide/pymc3_refitting.ipynb

Updated the [Refitting PyMC3 models with ArviZ](https://arviz-devs.github.io/arviz/user_guide/pymc3_refitting.html#
) part.

Updated Refitting PyMC3 models with ArviZ

---

doc/source/conf.py
doc/source/contributing/contributing_prs.md
requirements-docs.txt

Updating the [Contributing code via pull requests](https://arviz-devs.github.io/arviz/contributing/contributing_prs.html).

Contributing code via pull requests

---

doc/source/contributing/developer_guide.md

Updated the [developer guide](https://arviz-devs.github.io/arviz/contributing/developer_guide.html).
**Note**:  Could not find the proper page to link to the following:
*  `arviz.plots.backends`
*  `arviz.plots.get_plotting_function`
*  ` tests.test_plots_matplotlib`

Developer Guide

---

arviz/data/io_cmdstanpy.py

Add checks for CmdStanPy 1.0 methods.

Add checks for metadata

---

arviz/plots/khatplot.py

This PR adds references to the plot_khat function, addressing #1841

Add references to plot_khat #1841

---

doc/_templates/layout.html

We shared the survey on 14th June, and have gotten 56 responses. During the last month, we only got 2 or 3 more responses. We are not receiving any more responses. It is the time we close the survey and remove the banner from the docs.

removed survey banner

---

arviz/stats/stats.py

Updated [arviz.loo](https://arviz-devs.github.io/arviz/api/generated/arviz.loo.html).
* Added references
* Added "See Also" section
* Added backticks
Fixes: https://github.com/arviz-devs/arviz/issues/1874

Added references - arviz.loo

---

arviz/plots/lmplot.py

Added docstring references for the docstring of the `lmplot.py` file.
Addresses Issue #1884

Added docs references to plot_lm docstring for Issue #1884

---

arviz/plots/rankplot.py

1. Added references
2. Fixed mistake
Fixes: https://github.com/arviz-devs/arviz/issues/1864

Added references - Plot rank

---

arviz/stats/stats.py

Updated [arviz.loo_pit](https://arviz-devs.github.io/arviz/api/generated/arviz.loo_pit.html).
* Added references
* Added "See Also" section
* Added backticks
Fixes: https://github.com/arviz-devs/arviz/issues/1875

Added references - arviz.loo_pit

---

arviz/plots/distplot.py

Description:
Added references to the docstring of [plot_dist](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_dist.html).
Fixes: #1824

Added references-plot_dist

---

arviz/plots/khatplot.py
arviz/plots/ppcplot.py

Fixed few minor mistakes in docstring-plots

---

arviz/stats/diagnostics.py

Add docs references to arviz.ess docstring. Closes #1909

Add docs references to arviz.ess docstring

---

doc/source/about_us.md
doc/source/api/data.rst
doc/source/community.md
doc/source/conf.py
doc/source/contributing/developer_guide.md
doc/source/contributing/index.md
doc/source/contributing/issue_triaging.md
doc/source/contributing/outreach.md
doc/source/contributing/review_prs.md
doc/source/core_contributors.md
doc/source/external_resources.md
doc/source/user_guide/label_guide.rst
doc/sphinxext/gallery_generator.py
requirements-docs.txt

Some changes with docs:
* Add sphinx-codeautolink
* Show `dev` in the navbar version section for readthedocs latest and PR preview docs
* I was going to fix google analytics but it turns out it fixed itself on its own a couple weeks ago
* Remove sphinx-panels and use only sphinx-design
* Add more guides and contribution options to the contributing guide

General doc maintenance

---

arviz/stats/stats.py

Went through all the docstrings and made the necessary changes.
* Fixes: https://github.com/arviz-devs/arviz/issues/1877
* Added references to external libraries 
* Added See Also section
* Highlighted code keywords.

Updated the remaining docstrings - stats

---

arviz/stats/diagnostics.py

Fixes: https://github.com/arviz-devs/arviz/issues/1911
Fixes: https://github.com/arviz-devs/arviz/issues/1910
Fixes: https://github.com/arviz-devs/arviz/issues/1908

Updated the rest of docstrings files - diagnostics

---

arviz/plots/distcomparisonplot.py
arviz/plots/dotplot.py

There were only two files left in plot modules that needed to be updated. Updated those files to finish the work on plot modules.

Added references in plot_dot and plot_dist_comparison

---

arviz/stats/density_utils.py
arviz/stats/stats_utils.py

Pylint for copy method

---

doc/source/user_guide/Numba.ipynb

Fix spelling in Numba.ipynb

---

arviz/data/io_pystan.py
arviz/tests/external_tests/test_data_pystan.py

Closes #1961 
Ignore kw was ignored.

Add missing ignore handling

---

arviz/plots/traceplot.py

"rank_bar" should be "rank_bars"

Fix typo in docstring

---

CHANGELOG.md
arviz/stats/stats.py

Fix FutureWarning about `DataFrame.append()` deprecation. (closes #1971)

Update pandas.append to pandas.concat due to deprecation

---

doc/source/conf.py
doc/source/user_guide/plots_arguments_guide.md

Some more additions to the Plotting Guide.

[WIP] Additions to the Plotting Guide

---

arviz/plots/backends/__init__.py
arviz/plots/backends/bokeh/autocorrplot.py
arviz/plots/backends/bokeh/elpdplot.py
arviz/plots/backends/bokeh/pairplot.py
arviz/plots/backends/matplotlib/autocorrplot.py
arviz/plots/backends/matplotlib/elpdplot.py
arviz/plots/backends/matplotlib/khatplot.py
arviz/plots/backends/matplotlib/pairplot.py
arviz/plots/plot_utils.py
arviz/stats/density_utils.py
arviz/stats/diagnostics.py
arviz/stats/stats.py
arviz/tests/base_tests/test_stats.py
arviz/tests/base_tests/test_utils.py
arviz/tests/external_tests/test_data_emcee.py
arviz/tests/helpers.py
asv_benchmarks/benchmarks/benchmarks.py
requirements-dev.txt
requirements-docs.txt

unpin black and reformat codebase

---

doc/source/user_guide/plotting.md
doc/source/user_guide/plotting_with_bokeh.md
doc/source/user_guide/plotting_with_matplotlib.md

Adds plotting guide per backend. It solves #1488 
- [ x] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format

Adding plotting guides

---

arviz/__init__.py

This bumps the version to use the proper version string with dev in the name.

Bump version to next dev release

---

requirements-docs.txt

Related (but doesn't completely fix) #2051

pin pydata-sphinx-theme<0.9

---

CHANGELOG.md
doc/source/contributing/index.md
doc/source/contributing/translate.md

This adds a new page to our "contribution overview" section with instructions
on how to translate content for our project website (for now the only website with translations
activated)
cc @aloctavodia

add translation overview

---

arviz/plots/kdeplot.py

Added a space at the end of the error message for proper understanding in kdeplot.py  - line 253

add missing space in exception message for plot_kde

---

CONTRIBUTING.md

1) replaced the broken link with the link to PR checklist (intended for people familiar with contributing through GitHub) - fixes issue #2070 
2) also added a link to step by step PR tutorial (intended for 1st time contributors)
- [+] Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- [n/a] Includes a sample plot to visually illustrate the changes (only for plot-related functions)
- [n/a] New features are properly documented (with an example if appropriate)?
- [n/a] Includes new or updated tests to cover the new feature
- [n/a] Code style  correct (follows pylint and black guidelines)
- [n/a] Changes are listed in [changelog](https://github.com/arviz-devs/arviz/blob/main/CHANGELOG.md#v0xx-unreleased)

replaced Development Workflow Link with link to pull request checklist - issue #2070

---

.azure-pipelines/azure-pipelines-base.yml
.azure-pipelines/azure-pipelines-external.yml

If it works, it should fix https://github.com/arviz-devs/arviz/issues/1269. 
Followed the steps in https://docs.codecov.com/docs/codecov-uploader#integrity-checking-the-uploader

Use new codecov uploader

---

doc/source/getting_started/Installation.rst

----
:books: Documentation preview :books:: https://arviz--2097.org.readthedocs.build/en/2097/

Fix minimum required python and mention nep+spec

---

doc/source/external_resources.md
doc/source/user_guide/plots_arguments_guide.md

Some grammar errors I noticed.
----
:books: Documentation preview :books:: https://arviz--2123.org.readthedocs.build/en/2123/

Some grammar errors

---

arviz/__init__.py

Closes #2135
----
:books: Documentation preview :books:: https://arviz--2140.org.readthedocs.build/en/2140/

Register cet_gray only if colorcet is not installed

---

CHANGELOG.md
arviz/__init__.py
arviz/data/io_beanmachine.py

Trying a pre-release to double check NetCDF writing issues
----
:books: Documentation preview :books:: https://arviz--2143.org.readthedocs.build/en/2143/

Updated changelog and init for new release

---

CHANGELOG.md
arviz/__init__.py

Final changes to `CHANGELOG.md` and `__init__.py` to complete release
----
:books: Documentation preview :books:: https://arviz--2145.org.readthedocs.build/en/2145/

Post release changes to v0.13.0dev1

---

arviz/data/io_beanmachine.py
doc/source/contributing/how_to_release.md

Added a step missing from the guide and other improvements
----
:books: Documentation preview :books:: https://arviz--2144.org.readthedocs.build/en/2144/

Improve how to release page

---

doc/source/contributing/how_to_release.md

We missed this step in the last release and it wasn't in the how-to guide.
----
:books: Documentation preview :books:: https://arviz--2159.org.readthedocs.build/en/2159/

Add step about conda forge recipe to how-to release notes

---

CHANGELOG.md
arviz/__init__.py

This is a PR to update to 0.13.1
----
:books: Documentation preview :books:: https://arviz--2163.org.readthedocs.build/en/2163/

Version bump to 0.13.1

---

CHANGELOG.md
arviz/__init__.py

Includes changes needed after the 0.14.0 release
----
:books: Documentation preview :books:: https://arviz--2164.org.readthedocs.build/en/2164/

Post release changes

---

arviz/plots/autocorrplot.py
arviz/plots/bpvplot.py
arviz/plots/compareplot.py
arviz/plots/densityplot.py
arviz/plots/distcomparisonplot.py
arviz/plots/distplot.py
arviz/plots/dotplot.py
arviz/plots/elpdplot.py
arviz/plots/energyplot.py
arviz/plots/essplot.py
arviz/plots/forestplot.py
arviz/plots/kdeplot.py
arviz/plots/khatplot.py
arviz/plots/lmplot.py
arviz/plots/loopitplot.py
arviz/plots/mcseplot.py
doc/source/conf.py

start adding links to api docs

---

arviz/data/inference_data.py
arviz/tests/base_tests/test_data.py

Small fix how kwargs are handled
----
:books: Documentation preview :books:: https://arviz--2173.org.readthedocs.build/en/2173/

fix issue with coordinate

---

arviz/plots/autocorrplot.py
arviz/plots/bpvplot.py
arviz/plots/essplot.py

----
:books: Documentation preview :books:: https://arviz--2185.org.readthedocs.build/en/2185/

Update docstrings of ess, autocorr and bpv plots

---

arviz/plots/autocorrplot.py
arviz/plots/bpvplot.py
arviz/plots/essplot.py

Additional minimal documentation corrections for:
1 auto_corr
2 bpv
3 ess
plots

Additional minor corrections

---

arviz/plots/compareplot.py
arviz/plots/densityplot.py
arviz/plots/distcomparisonplot.py

Documentation updates for:
1. plot_compare()
2. plot_density()
3. plot_dist_comparison()
functions.
----
:books: Documentation preview :books:: https://arviz--2193.org.readthedocs.build/en/2193/

Agsd21 compare1

---

arviz/plots/distplot.py
arviz/plots/dotplot.py
arviz/plots/ecdfplot.py

Documentation updates for:
+ plot_dist()
+ plot_deot()
+ plot_ecdf()
functions.
Change default options for :
+ plot_dot:   `point_interval = True`
+ plot_ecdf:  `confidence_bands=True`
----
:books: Documentation preview :books:: https://arviz--2199.org.readthedocs.build/en/2199/

Gsd dist dot ecdf+elpd

---

CHANGELOG.md
arviz/__init__.py

Prep v0.15.0 release
----
:books: Documentation preview :books:: https://arviz--2206.org.readthedocs.build/en/2206/

Release for v.0.15.0

---

CHANGELOG.md
arviz/__init__.py

Post release pull request
----
:books: Documentation preview :books:: https://arviz--2213.org.readthedocs.build/en/2213/

Post release version update

---

CHANGELOG.md
arviz/__init__.py

Prep v0.15.1 release
----
:books: Documentation preview :books:: https://arviz--2219.org.readthedocs.build/en/2219/

Release for ArviZ v0.15.1

---

CHANGELOG.md
arviz/__init__.py

----
:books: Documentation preview :books:: https://arviz--2220.org.readthedocs.build/en/2220/

0.16.0.dev

---

arviz/plots/bfplot.py

----
:books: Documentation preview :books:: https://arviz--2230.org.readthedocs.build/en/2230/

fix typos bfplot docstring

---

.azure-pipelines/azure-pipelines-external.yml

----
:books: Documentation preview :books:: https://arviz--2235.org.readthedocs.build/en/2235/

Remove codecov pypi install

---

.pylintrc

----
:books: Documentation preview :books:: https://arviz--2234.org.readthedocs.build/en/2234/

use builtins.Exception in .pylintrc

---

CHANGELOG.md
arviz/data/io_emcee.py

----
:books: Documentation preview :books:: https://arviz--2239.org.readthedocs.build/en/2239/

fix object array in emcee code

---

CHANGELOG.md
arviz/__init__.py

----
:books: Documentation preview :books:: https://arviz--2267.org.readthedocs.build/en/2267/

post release updates

---

arviz/plots/backends/matplotlib/lmplot.py

I changed the explicit color notation to themed color notation. I also made it more aesthetically pleasing by changing y_model fill and the y_hat_fill to different blues, and changing the mean line color to black.
This PR partially addresses the issue #2183.
----
:books: Documentation preview :books:: https://arviz--2271.org.readthedocs.build/en/2271/

use theme colors and change styling for lmplot

---

arviz/tests/external_tests/test_data_cmdstanpy.py
pytest.ini

Temporary change.
----
:books: Documentation preview :books:: https://arviz--2279.org.readthedocs.build/en/2279/

skip cmdstanpy tests

---

doc/source/community.md

----
:books: Documentation preview :books:: https://arviz--2285.org.readthedocs.build/en/2285/

Update community.md (update pymc(3) links + add ArviZ video)

---

doc/source/conf.py
requirements-docs.txt

Fix myst configuration to work with latest versions.
----
:books: Documentation preview :books:: https://arviz--2292.org.readthedocs.build/en/2292/

fix myst config

---

arviz/tests/helpers.py

----
📚 Documentation preview 📚: https://arviz--2297.org.readthedocs.build/en/2297/

fix stan model

---

arviz/plots/backends/matplotlib/bpvplot.py
arviz/plots/bpvplot.py

reverts  #2179
----
📚 Documentation preview 📚: https://arviz--2299.org.readthedocs.build/en/2299/

 plot_bpv smooth discrete for both u_values and p_values

---

CHANGELOG.md
arviz/__init__.py

Add dev flag and unreleased template to changelog
----
📚 Documentation preview 📚: https://arviz--2303.org.readthedocs.build/en/2303/

post release tasks

---

arviz/plots/ppcplot.py

----
📚 Documentation preview 📚: https://arviz--2308.org.readthedocs.build/en/2308/

plot_ppc: default observed to False if group prior

---

CHANGELOG.md
arviz/__init__.py
setup.py

Make a patch release with the fix for plot_forest.
----
📚 Documentation preview 📚: https://arviz--2323.org.readthedocs.build/en/2323/

make patch release

---

CHANGELOG.md
arviz/__init__.py
doc/source/getting_started/Installation.rst
requirements.txt

----
📚 Documentation preview 📚: https://arviz--2339.org.readthedocs.build/en/2339/

prepare for 0.18.0 release

---

arviz/plots/ecdfplot.py
arviz/plots/essplot.py
arviz/plots/khatplot.py
arviz/plots/loopitplot.py
arviz/plots/mcseplot.py
arviz/plots/rankplot.py
arviz/stats/diagnostics.py
arviz/stats/stats.py

Update and fix some references
----
📚 Documentation preview 📚: https://arviz--2346.org.readthedocs.build/en/2346/

fix some references

---

.azure-pipelines/azure-pipelines-base.yml
arviz/plots/backends/bokeh/pairplot.py
requirements-docs.txt
requirements-optional.txt

----
📚 Documentation preview 📚: https://arviz--2356.org.readthedocs.build/en/2356/

Try bokeh 3

---

CHANGELOG.md
arviz/__init__.py
requirements-optional.txt

----
📚 Documentation preview 📚: https://arviz--2360.org.readthedocs.build/en/2360/

bump release 0.19.0

---

CHANGELOG.md
arviz/__init__.py

----
📚 Documentation preview 📚: https://arviz--2363.org.readthedocs.build/en/2363/

follow-up release 0.19.0

---

arviz/plots/compareplot.py

Following the discussion in https://github.com/arviz-devs/arviz/discussions/2386
----
📚 Documentation preview 📚: https://arviz--2388.org.readthedocs.build/en/2388/

Set plot_ic_diff and legend to False by default

---

doc/source/community.md
doc/source/conf.py

Change Twitter to X, including the icon. 
----
📚 Documentation preview 📚: https://arviz--2418.org.readthedocs.build/en/2418/

Change Twitter to X, including the icon

---

doc/source/getting_started/Installation.rst
doc/source/user_guide/Numba.ipynb

The Numba links have been moved to https://numba.readthedocs.io/.
Original Numba link does not work.
https://numba.pydata.org/numba-doc/latest/index.html
----
📚 Documentation preview 📚: https://arviz--2421.org.readthedocs.build/en/2421/

DOC: Change Numba links

---

doc/source/community.md
doc/source/external_resources.md

Add missing periods to the ArviZ community page.
----
📚 Documentation preview 📚: https://arviz--2426.org.readthedocs.build/en/2426/

DOC: Add missing periods to the ArviZ community page

---

doc/source/community.md

Correct a typo: `InfereceData` -> `InferenceData` in community.md.
----
📚 Documentation preview 📚: https://arviz--2428.org.readthedocs.build/en/2428/

DOC: Correct a typo: `InfereceData` -> `InferenceData`

---

doc/source/user_guide/plotting_with_bokeh.md

Update two Bokeh reference links.
----
📚 Documentation preview 📚: https://arviz--2432.org.readthedocs.build/en/2432/

DOC: Update two Bokeh reference links

---

doc/source/getting_started/Installation.rst

Update Bokeh link in Installation.rst.
Correct link:
https://docs.bokeh.org/en/latest/docs/first_steps/installation.html
The old link does not work:
https://docs.bokeh.org/en/dev/docs/first_steps/installation.html
----
📚 Documentation preview 📚: https://arviz--2425.org.readthedocs.build/en/2425/

DOC: Update Bokeh link in Installation.rst

---

CHANGELOG.md
arviz/__init__.py

----
📚 Documentation preview 📚: https://arviz--2435.org.readthedocs.build/en/2435/

changes after release

---

doc/source/getting_started/WorkingWithInferenceData.ipynb

Add punctuation to `WorkingWithInferenceData.ipynb`.
----
📚 Documentation preview 📚: https://arviz--2436.org.readthedocs.build/en/2436/

Add punctuation to WorkingWithInferenceData.ipynb

---

doc/source/getting_started/Installation.rst

Correct a typo in Installation.rst: ``pip install "arviz[preview]"``
----
📚 Documentation preview 📚: https://arviz--2439.org.readthedocs.build/en/2439/

Correct a typo in Installation.rst

---

doc/source/contributing/content_structure.md

Just fixed a typo nothing more to add
----
📚 Documentation preview 📚: https://arviz--2440.org.readthedocs.build/en/2440/

fixed a typo in content-structure.md

---

doc/source/getting_started/Introduction.ipynb

added cross-ref to the See Also box
https://python.arviz.org/en/latest/getting_started/Introduction.html
----
📚 Documentation preview 📚: https://arviz--2443.org.readthedocs.build/en/2443/

added cross-ref to the See Also box

---

.azure-pipelines/azure-pipelines-base.yml

----
📚 Documentation preview 📚: https://arviz--2451.org.readthedocs.build/en/2451/

Remove h5py from nightlies

---

CHANGELOG.md
arviz/data/io_numpyro.py
arviz/tests/external_tests/test_data_numpyro.py

Fixes: #2022
If dims are not provided, `az.from_numpyro` now infers dims automatically based on model plates, sample sites, and provided `coords`. 
For event_dims...
* for numpyro.sample sites, infer={"event_dims":["dim1"]} can be provided
* for deterministic sites, there is an `extra_event_dims` field in az.from_numpyro to manually provide them.
`pred_dims` are also now inferred by default if they arent provided.
----
📚 Documentation preview 📚: https://arviz--2441.org.readthedocs.build/en/2441/

Infer NumPyro InferenceData dims automatically

---

doc/source/getting_started/CreatingInferenceData.ipynb

Closes #2442 
* Replaced outdated PyMC3 with PyMC workflow.
* Using sigma instead of sd to prevent DeprecationWarning.
* Removed az.from_pymc3() and integrated prior, posterior, and posterior predictive sampling directly using pm.sample() and .extend().
----
📚 Documentation preview 📚: https://arviz--2444.org.readthedocs.build/en/2444/

Update Getting Started for PyMC

---

CHANGELOG.md
arviz/__init__.py

----
📚 Documentation preview 📚: https://arviz--2461.org.readthedocs.build/en/2461/

update version and add empty changelog sections after release

---

CHANGELOG.md
arviz/data/inference_data.py

Fixes #2463
----
📚 Documentation preview 📚: https://arviz--2464.org.readthedocs.build/en/2464/

Don't close unloaded xarray data in from_netcdf

---

.github/FUNDING.yml

Closes #2466
Following discussion in #2466, this keep the current sponsor list, but flips the order.
----
📚 Documentation preview 📚: https://arviz--2467.org.readthedocs.build/en/2467/

Change order sponsors

---

doc/source/user_guide/migration_guide.ipynb

----
📚 Documentation preview 📚: https://arviz--2478.org.readthedocs.build/en/2478/

Update migration guide
