- .gitignore
- README.md
- setup.py
- setupegg.py
If we want to make mcmcplotlib an (optional) dependancy for pymc3, we need to make it auto-installable with pymc3. 
Refactoring and testing are probably needed to be added, before making it a full dependancy.
As a first step, we can put a reference to:
`pip install git+git://github.com/mcmcplotlib/mcmcplotlib.git` to pymc3 and start adding reference to mcmcplotlib in examples in pymc3.
> minimal pip install support

- arviz/plots/__init__.py
- arviz/plots/energyplot.py
- arviz/plots/parallelplot.py
- arviz/plots/posteriorplot.py
- arviz/tests/test_plots.py
While a parallel coordinates plot could be more general this implementation is tailored to help diagnose NUTS samples. See this [page](https://docs.pymc.io/notebooks/Diagnosing_biased_Inference_with_Divergences.html) and this [paper](https://arxiv.org/abs/1709.01449) for details.
This PR also make change in other files:
* Remove duplicated code from energyplot
* Rename `text_size` argument in `posteriorplot` to `textsize` (for consistence with other argument names)
* More test for plots (still not very thorough).
> add parallelplot

- arviz/plots/forestplot.py
- arviz/tests/test_plots.py
Now forestplot looks closer to the graphical version of `summary` :-)
> forestplot: add effective sample size

- arviz/plots/autocorrplot.py
- arviz/plots/pairplot.py
- arviz/plots/styles/arviz-darkgrid.mplstyle
- arviz/plots/styles/arviz-whitegrid.mplstyle
* styles: use viridis cmap
* autocorrplot: add `combined` argument
* pairplot:
* add `gridsize` argument for hexbin, default to 1% of the number of samples
* ensure grid is off when `hexbin=True`
* add missing grid lines.
> minor tweaks pairplot, autocorrplot and styles

- arviz/plots/__init__.py
- arviz/plots/jointplot.py
- arviz/plots/kdeplot.py
- arviz/plots/pairplot.py
- arviz/plots/plot_utils.py
- arviz/plots/traceplot.py
- arviz/tests/test_plots.py
New jointplot, it could be implemented as part of pairplot, with a _marginals_ arguments, but for now I am adding it as a standalone plot.  
```python
az.jointplot(trace, varnames=['e', 'd'])
```
```python
az.jointplot(trace, varnames=['e', 'd'], hexbin=True)
```
This PR also adds:
* kdeplot: new `rotated` argument
* gridsize is now computed as len(trace)**0.35, instead of 1% of samples
* pairplot: small fix, use `get_varnames` to handle varnames
> add jointplot

- .pylintrc
- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/energyplot.py
- arviz/plots/khatplot.py
- arviz/plots/pairplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/traceplot.py
- arviz/stats/stats.py
- arviz/tests/test_stats.py
This leaves only `stats.stats` and `stats.diagnostics` to be linted before I can stop making these nitpicky changes.  
A few conditions I turned off can be useful when writing maintainable functions (`too-many-locals`, `too-many-statements`, `too-many-branches`), but it seemed like too big a change to take those on.
> Add more linting

- .travis.yml
- requirements-dev.txt
- requirements.txt
- setup.py
This activates coveralls (79% currently), and also might make writing documentation for new developers a little easier (`pip install -r requirements.txt`, `pip install -r requirements-dev.txt`).  
You are doing some cool conda stuff, but I do not know enough to set up an environment.yml or to write those instructions.
Note you will have to go to coveralls.io and activate the repo to start getting covered (and then you can get travis/coveralls badges on readme.md).
> Add coveralls, requirements files

- arviz/plots/__init__.py
- arviz/plots/kdeplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/plots/ppcplot.py
- arviz/tests/test_plots.py
Potentially this could be a very flexible plot, this is just a first step. At this point it can generate just two plots `kind=kde` and `kind=cumulative`.
I also made two small changes to kdeplot:
* a new cumulative argument (ppcplot does not use this option, but the empirical cdf)
* a small change to better handle samples with few data points
> Add posterior predictive checks plot

- .pylintrc
- arviz/compat/__init__.py
- arviz/compat/optional_dep.py
This is a way to use methods from `pymc3` or `altair` when it is clear the user wishes to use such a method.  For example, if the user passes a `pymc3` trace, I think it would be fair to use a method from `arviz.compat.pymc3`.  
I also plan to use this to implement some methods using `arviz`.
> Add optional dependency class

- arviz/plots/traceplot.py
- arviz/utils/__init__.py
- arviz/utils/utils.py
- setup.py
This adds an argument to `arviz.traceplot` that outputs an altair plot instead of a matplotlib one.  Let me know if you would like to surface it in some other way.
This also adds a utility function to make the traceplot that might be useful in the main traceplot, if you would like it to look more like the main 'pymc3' one.
Here is a comparison of the two:
> Add altair traceplot

- .travis.yml
- arviz/tests/test_xarray_utils.py
- arviz/utils/__init__.py
- arviz/utils/xarray_utils.py
- requirements.txt
This uses @aseyboldt 's code, as well as a bit of the details from #97 (including the recommendation to use `draw` over `sample`).  Example usage is [here](https://gist.github.com/ColCarroll/c607842947b08bc44d4e1588e6bef98d).  Note that it is not automated, but gives reasonably helpful error messages in certain cases.
I erred on the side of writing too many tests so that as the "spec" changes over there, it will be easier to update this code.
Definitely understand if you want to cut a release or wait for the conversation to settle before merging, but I thought an implementation might help (and I want to start converting the plotting functions to use `xarray`).
> Add xarray trace conversion for PyMC3

- arviz/tests/test_xarray_utils.py
- arviz/utils/xarray_utils.py
Added functions for xarray_utils to translate fit object to xarray object.
Also I replaced some `.copy` methods to `deepcopy` functions. They were done over the dictionary containing lists, so `deepcopy` was needed. 
Currently these functions work only with the current PyStan github (develop) version, but given the assumption that these functions are removed  and transported to corresponding libraries before official release, that is ok.
If we leave these functions as a backup for the users, then I can fix that step.
> Pystan xarray

- .travis.yml
- arviz/tests/test_xarray_utils.py
- arviz/utils/__init__.py
- arviz/utils/xarray_utils.py
- requirements-dev.txt
- scripts/create_testenv.sh
- scripts/install_miniconda.sh
This does a few things to get ready to port functions to `xarray`:
- in `xarray_utils`, there is an abstract base class so that `PyMC3ToXarray` and `PyStanToXarray` have the same interface
- Adds a function `convert_to_xarray` that dispatches code to the correct converter
- Adds `pystan` to the travis build
- Tests the `PyStanToXarray` code (in the exact way the `PyMC3ToXarray` code is tested)
I have `autocorrplot` mostly ready to go after this lands.
> Refactor xarray utilties

- requirements-dev.txt
This seemed to get installed with `xarray` on my machine, but it is keeping docs from building.
> Netcdf4 required to build docs

- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/plot_utils.py
- arviz/tests/test_plots.py
- doc/index.rst
- examples/densityplot.py
This also allows direct comparisons of posteriors from `PyStan` and `PyMC3`, which is part of the goal of the whole `xarray` exercise.  These are from the non centered eight schools model fit with default arguments.
I also added this plot to the front page of http://arviz-devs.github.io/arviz/ because it looks nice!
> Update densityplot to use xarray

- arviz/stats/stats.py
- arviz/tests/test_stats.py
This is an alternative way to compute r2. This version provides a much more better agreement with the one computed by `stats.linregress`. Just an example.
```python
np.random.seed(1)
N = 100
alpha_real = 2.5
beta_real = 0.9
eps_real = np.random.normal(0, 100, size=N)
x = np.random.normal(10, 1, N)
y_real = alpha_real + beta_real * x 
y = y_real + eps_real
x = np.random.normal(10, 1, N)
y_real = alpha_real + beta_real * x 
y = y_real + eps_real
with pm.Model() as model:
α = pm.Normal('α', mu=0, sd=1000)
β = pm.Normal('β', mu=0, sd=1000)
ϵ = pm.HalfCauchy('ϵ', 50)
μ = pm.Deterministic('μ', α + β * x)
y_pred = pm.Normal('y_pred', mu=μ, sd=ϵ, observed=y)
trace = pm.sample(1000)
ppc = pm.sample_ppc(trace, samples=1000, model=model)
```
With the previous version we get 0.34, with the new one …
> change r2_score

- .pylintrc
- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/plot_utils.py
- arviz/stats/diagnostics.py
- arviz/tests/test_plots.py
- doc/index.rst
- examples/forestplot.py
- examples/joyplot.py
Phew! This was sort of tough.  I used an object-oriented approach that leans heavily on the `VarHandler.iterator` method, which figures out where every row in this figure should go.  This makes it easy to add more facets (for example, a traceplot) to this in the future.  I added a joyplot to show it can be supported.
Just showing off a bit of what can be done
```python
fig, ax = az.forestplot(data)
```
```python
fig, axes = az.forestplot([stan_xarray, centered_data, pymc3_xarray], 
model_names=['PyStan', 'Centered', 'PyMC3'], 
var_names=['theta', 'theta_tilde'], 
colors=['#AF0A22', 'C1', '#1B6989']);
```
```python
fig, ax = az.forestplot(data, 
var_names=['theta'], 
joyplot=True, 
combined=True, 
textsize=12, 
colors='white')
```
```python
fig, axes = az.forestplot([centered_data, data], …
```
> Add xarray support to forestplot

- scripts/start_container.sh
Without this, changes to the code on the host machine are not reflected in the container.
> Actually share the source directory as a volume with the Docker container

- arviz/plots/forestplot.py
Very small change.  The dots in the r-hat and effective N plots in forestplot are now outlined in black.
> Outline markers in forestplot

- arviz/plots/autocorrplot.py
- arviz/plots/traceplot.py
- arviz/tests/test_plots.py
- examples/traceplot.py
Looks quite similar to the current implementation.  Two big differences:
1. I removed the `prior` argument. It seemed hard to understand how to use, hard to implement, and I'd rather wait and accept an xarray dataset there (perhaps similar to how forestplot just accepts multiple datasets?)
2. The `lines` argument now looks like `[('theta', {'school': ['Choate', 'Phillips Andover']}, [0, 1, 8])]`.  The first two arguments say which plots the lines should go on, and the last argument says where the vlines go.
Here's the example that goes in the documentation:
> Traceplot supports xarray

- arviz/utils/utils.py
Without introducing a fixed dependency on `pymc3` (or any other non-standard library module), this commit introduces facilities to safely recognize `pymc3` objects (and objects with origin in other modules). This is achieved by reliance on standard library module `importlib`.
In summary, we add a function with signature `_has_type(object_, typename, module_path)` that checks if `object_` has a type given as string `typename` that can be found under a `module_path`, also given as string. If a module under `module_path` can not be imported (e.g. because it is not installed), we return `False` to cover cases where a user does not use `pymc3`. 
We use this function to refactor a few problematic string-based checks in `arviz.utils.utils`, for further information on those check issue #138.
> safely check for pymc3 objects without additional dependency

- arviz/plots/posteriorplot.py
- doc/conf.py
While trying working on the pull request for prior distribution plots in pymc3, I thought it would be helpful both for me and others to have more documentation on what various plotting options, similar to how Seaborn's documentation.
To that extent I tried it out. Attached is a exported PDF of the documentation to illustrate the change.
If this is welcome I would be happy to continue with this PR until the documentation is comprehensive.  Any feedback positive or negative would be appreciated!
Seaborn Inspiration
https://seaborn.pydata.org/generated/seaborn.distplot.html
[arviz.posteriorplot — ArviZ 0.1.0 documentation_example.pdf](https://github.com/arviz-devs/arviz/files/2238547/arviz.posteriorplot.ArviZ.0.1.0.documentation_example.pdf)
> [WIP] Add some sample figures in docs

- arviz/__init__.py
- arviz/plots/posteriorplot.py
- arviz/tests/test_plots.py
- arviz/utils/__init__.py
- arviz/utils/utils.py
- examples/posteriorplot.py
- examples/traceplot.py
A change I'm happy with is the addition of `load_arviz_data`, which allows you to load some pretrained datasets.  You can train some data, use `az.save_data(...)` on it, then move the file to the appropriate folder if you want to add more (I'd like to add models trained with pystan, edward, pymc4, tensorflow probability...) I made this so I could update @canyon289's documentation examples.
The actual plot definitely works but has some rough edges.  I think it is ok to merge given that there may be others who want to work on it.  As an example,
```python
az.posteriorplot(non_centered, var_names=('theta_tilde',), ref_val=0, rope=(-1, 1))
```
If we wanted followups, I think
1. The way of passing `rope` or `ref_val` arguments to individual plots is pretty nasty, but the best I could do. …
> Update posterior plot to work with xarray

- arviz/plots/ppcplot.py
- doc/index.rst
- doc/roadmap.rst
- examples/ppcplot.py
This adds the current roadmap to the documentation and fixes the ppcplot there.  FYI @canyon289 .
> Add roadmap to documentation

- arviz/utils/xarray_utils.py
This way no need to check dims for all the variables to see if they are empty.
> fix empty pars if at least one par nonempty

- arviz/plots/kdeplot.py
- arviz/plots/traceplot.py
- arviz/stats/stats.py
* Loo was returning `loo_i` even when `pointwise=False`
* Colors for rug and fill in a kdeplot is set by default as the same color of the kde-line by default. 
* I think the fill under the line should be 0 (transparent) by default. KDEs are very useful to overlaid many distributions (contrary to filled-histtogram) having a shade by defaults reduce the usefulness of this feature.
> a couple of small fixes

- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/violintraceplot.py
- arviz/stats/stats.py
- arviz/tests/test_stats.py
- examples/densityplot.py
* the mean, standard deviation and hpd intervals are estimates of the _true_ variable while mc_error, n_eff and rhat are properties only of the samples used to approximate that variable. This change the order of mc_error accordingly.
* This also changes the name of the argument `alpha` to `credible_interval` to avoid confusion with matplotlib's alpha parameter.
* The value of the credible interval is set to 0.94, just to make the point that 0.95 is completely arbitrary
> change order mc_error and credible interval default value

- arviz/stats/stats.py
When setting alpha (now credible_interval) out of the bounds of 0 to 1, the user gets a confusing error.
I propose adding an extra line of text to make it a little more clear what the user should do.
I would like to write a test for this but am traveling and away from my linux computer. Submitting for now just to get feedback.
> [WIP] Add additional information to hdp exception

- arviz/plots/forestplot.py
- arviz/plots/plot_utils.py
Adresses #166. Dimensions of multidimensional variables are now ordered ascending instead of descending as they were previously. I decided to go the route @ColCarroll suggested in #166. I introduced 
a flag `reverse_selections` for `xarray_var_iter` in `arviz.plots.plot_utils.py` and set it to `True` inside `arviz.plots.forestplot`. 
They say pictures say more than a thousand words, so:
Old:
New:
> fix forestplot: order dimensions in ascending order

- arviz/utils/xarray_utils.py
> add sample_stats for PyStan

- doc/sphinxext/gallery_generator.py
The Example Generator was using the module name to label the thumbnails in the gallery so the ridgeplot was showing labeled as a forestplot
I propose changing this to the sphinxtag which allows for more flexibility in naming. The tradeoff though is it matches the "human" name now for the plot but not the method name, although I argue the user can just click into the example to see the code.
Before change
After change
> [WIP] Fix labels for plot

- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/jointplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/traceplot.py
- arviz/plots/violintraceplot.py
- arviz/utils/utils.py
- arviz/utils/xarray_utils.py
While the code works, the posterior argument is ignored and to a human it looks like a second non keyword argument is actually doing something when it isnt
@ColCarroll Out of curiosity why is an api where all non keyword arguments are ignored, except the first one preferred?
> (obj, *_, group='posterior', coords=None, dims=None)
*Before change*
> Fix bug where argument was ignored

- arviz/utils/utils.py
- arviz/utils/xarray_utils.py
abstractstaticmethod is deprecated for reference
https://docs.python.org/3/library/abc.html#abc.abstractstaticmethod
> Add some minor fixes

- arviz/utils/xarray_utils.py
- requirements-dev.txt
This will first try to extract with parameters and  `permuted=False`. In older versions, it will return numpy.array and in later versions a dictionary. If a dictionary is not seen, it will extract again, but permuted=True and then goes to reorder permutation.
Also added `lp` back to sample_params, it went missing after the "rebase".
> support PyStan version < 2.18

- arviz/plots/parallelplot.py
- arviz/plots/plot_utils.py
- arviz/tests/test_plotutils.py
- examples/parallelplot.py
Looking for two pieces of feedback.
1. Is the approach palatable? 
2. This approach won't work with numpy array inputs at time of writing.numpy_to_data array doesn't have a mechanism for the user to specific sample_stats. Is that an immediate problem?
If this is headed in the right direction though I can clean this up e.g. make functions to add to plot_utils  etc
> Implement InferenceData with ParallelPlot

- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/parallelplot.py
- arviz/plots/plot_utils.py
- arviz/tests/test_plotutils.py
- arviz/tests/test_xarray_utils.py
- arviz/utils/xarray_utils.py
- examples/parallelplot.py
Same question as before though! Why force people to use keyword argument?
> Fix extra argument behavior

- MANIFEST.in
- arviz/inference_data.py
After about 30 tries, I think `autoclose=True` is what was needed to get everything to work on travis. I can not recreate the problem locally (I opened both datasets 100 times in 4 python processes), but this may get docs to build again.
Note that the build should succeed, but we still need to check the travis logs to make sure the docs actually built.
> Add manifest to include data, autoclose netcdf

- arviz/inference_data.py
- scripts/create_testenv.sh
This fixes #202 on my machine. I will check travis logs to see if it fixes it there, too.
> Open dataset in context manager

- README.md
Some minor edits, but mostly adding a gallery to the readme. 
Note that I am linking the images directly to the documentation, instead of internally into the github repo. This is a little risky (if the documentation goes down, the README looks bad), but makes the README portable: the images will still display on pypi, for example.
You can see it at https://github.com/ColCarroll/arviz/tree/pretty-docs
> README gallery

- arviz/plots/forestplot.py
This fixes a problem where 
```python
az.forestplot({
'x': np.random.randn(100),
'y': np.random.randn(100),
})
```
does not work, because the distance between chains is NaN, which makes the distance between variables NaN.
> Fix divide by zero in forestplot

- arviz/tests/test_xarray_utils.py
- arviz/utils/xarray_utils.py
Enable more flexible usage for dims and coords.
This PR enables that user can input names only to specific dims or coords.
If dims is None or not defined, it will use the default name, and if coord is not defined, it creates the default coord.
> Fix dims and coords

- arviz/plots/pairplot.py
- examples/pairplot.py
Fixes https://github.com/arviz-devs/arviz/issues/212
Example Plots, It's easy enough to change the spacing if someone has a strong preference.
One thing to note is that there's some strange behavior with the y axis label positions. If this is problematic I create an issue.
> Update Pairplot example and spacing

- examples/pairplot.py
Coordinates were defined, but not used in the example!
> Use coordinates in pairplot

- arviz/plots/pairplot.py
- examples/hexpairplot.py
Address @ColCarroll's comment about pairplot code duplication
Tighten up pairplot spacing due to personal preference
> Pairplot dedup

- arviz/plots/plot_utils.py
Per at @ahartikainen comments make the labels a little nicer.
Still not great, but for a two character change I think this is moving the labels in the right direction.
I haven't checked all the plots yet but below are examples from pairplot.  They're getting cut off a little but If they generally look good I can fix this and check more plots.
> [WIP] Break axes labels at selection

- arviz/utils/xarray_utils.py
- schema.md
I pulled this out of a larger PR I am working on to port diagnostics and stats to work with xarray. This takes `utils.log_post_trace`, and extracts it into the xarray object when reading a pymc3 object in.  @ahartikainen perhaps this could be added to `pystan` by having an argument giving the name of the generated quantity?
This implementation takes the coordinates for the observed variable, if the exist, and apply it to the likelihood.  For example, in the 8 schools model, the likelihood is 4 x 500 x 8 (chain x draw x school).
> Add log_like to pymc3 sample_stats

- arviz/plots/__init__.py
- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/kdeplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/violintraceplot.py
Sometimes I find useful to have access to `fast_kde`, at the sometime it should not be of interested to most users hence the underscore.
> expose fast_kde

- arviz/utils/xarray_utils.py
User can give log_likelihood value as 
- str--> parameter in fit
- list / numpy array --> assumes same shape and sort order as extract gives
- 2.18+ --> permuted=False, (draws, chains, *shape)
- 2.17 and earlier --> permuted=True, (draws*chains, *shape)
Includes also small fixes for extraction process, if chains == 1.
> add log_likelihood for pystan

- arviz/plots/jointplot.py
- arviz/plots/pairplot.py
- arviz/plots/parallelplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/plots/traceplot.py
- arviz/tests/test_plotutils.py
Fix for https://github.com/arviz-devs/arviz/issues/213
If you guys like how this looks I'll change all the other plots to this pattern. Did a couple as an example
```
data = az.load_arviz_data('non_centered_eight')
az.traceplot(data, var_names=('theta_t'), coords={'theta_t_dim_0': [0, 1, 100]})
az.traceplot(data, var_names=('theta_t'), coords={'theta_t_dim_0_t': [0, 1]})
```
> Add nicer exception message for mistake in coords argument

- arviz/data/convert/from_pystan.py
- arviz/tests/helpers.py
- arviz/tests/test_data.py
- arviz/tests/test_plots.py
Using a pattern like
```python
data = az.pystan_to_inference_data(fit=fit, 
observed_data=['y'], 
coords={'school': schools},
dims={'theta': ['school'], 'y': ['school']})
```
throws an exception without this change.
> Allow observed data to inherit dims

- arviz/plots/pairplot.py
- arviz/plots/parallelplot.py
- arviz/plots/plot_utils.py
- arviz/tests/test_plot_utils.py
Let's go with the odict. It is easiest solution.
At least I usually assume that the order of input equals output.
I streamlined a few functions, nothing big.
> fix dict order with OrderedDict and streamline plot_utils functions

- arviz/data/__init__.py
- arviz/plots/__init__.py
- arviz/stats/__init__.py
I noticed that it was possible to have access to numpy and pandas from ArviZ or that we have, for example  `jointplot` and `plot_joint` at the same level. This fix it. Not sure if this is the best way, but it's one way :-)
> clean namespace

- examples/plot_kde_2d.py
Adding an example of a 2d kde plot. I'll add another that actually has correlated variables later, but this is visually pleasing. It will change on every commit.
> Add 2d kde example

- arviz/plots/pairplot.py
- requirements.txt
This gets rid of a warning, and trying a few different sizes it looked reasonable.
Here's the new version of the example:
Here's the version on master:
> Use constrained_layout in plot_pair

- arviz/tests/test_plots.py
Makes it possible to know what object the attr is without having to run a debugger or read across modules
> Rename Class fixture attrs to be more descriptive

- arviz/tests/test_plots.py
One question I have,
Does it make sense to have all the plot tests take a pymc3.MultiTrace and a StanFit4Anon model as an input, and instead have az.InferenceData as an input?
I ask because these objects get converted to InferenceData right at the top of most plots, and I vaguely feel like we should have `(pymc3.MultiTrace, StanFit4Anon) -> Inference Data` be its own test and decouple the object conversion from "does it plot" test?
I could make arguments about repeated computation, and more atomic tests, but if someone has strong(er) feelings let me know.
> Update AutoCorrPlot test

- arviz/data/__init__.py
- arviz/data/converters.py
- arviz/data/io_emcee.py
- arviz/plots/pairplot.py
- arviz/tests/helpers.py
- arviz/tests/test_data.py
- arviz/tests/test_plots.py
- requirements-dev.txt
This adds support for [emcee](http://dfm.io/emcee/current/), and adds a model to the test suite.
I ended up not adding test support to too many plots: `emcee` does not "know" the names of its variables, so it is hard in `test_plots` to reuse the machinery too much. The test coverage for `io_emcee.py` is still 94% - I will add a small test to throw the two `ValueErrors` that are missing.
Note that now arviz can mostly recreate the plots from http://dfm.io/emcee/current/user/line/ :
```python
from arviz.tests import helpers
az.style.use('arviz-darkgrid')
sampler = models['emcee']
data = az.from_emcee(sampler, var_names=['ln(f)', 'b', 'm'])
az.plot_trace(data, trace_kwargs={'color': 'k'})
```
```python
az.plot_pair(data, plot_kwargs={'c': 'k', 'alpha': 0.05})
```
> Add emcee support

- doc/conf.py
This fixes the build, I think. Going to merge right in and see if it actually does, since this can only be checked on master, and won't hurt any functionality. 
I can not find any references to what this extension did, but can confirm it is not exposed on matplotlib 3.0 (which is what breaks the build).
> A sphinx extension disappeared, but it does not matter

- arviz/data/__init__.py
- arviz/data/converters.py
- arviz/data/io_pyro.py
- arviz/tests/helpers.py
- arviz/tests/test_data.py
- arviz/tests/test_plots.py
- requirements-dev.txt
- scripts/create_testenv.sh
This adds pyro support. It is missing tests, but it is ready to be tested as soon as https://github.com/uber/pyro/issues/1426 is settled.
I have run this all manually, and it does ok. The below code gets you a centered eight schools model on this branch.
```python
from arviz.tests import helpers
posterior = helpers.pyro_centered_schools(helpers.eight_schools_params(), 500, 500)
schools = np.array(['Choate', 'Deerfield', 'Phillips Andover', 'Phillips Exeter', 'Hotchkiss', 'Lawrenceville', "St. Paul's", 'Mt. Hermon'])
data = az.convert_to_inference_data(posterior,
coords={'school': schools},
dims={'theta': ['school'], 'obs': ['school']})
data
```
```
Inference data with groups:
> posterior
> observed_data
```
> Add pyro converter

- requirements.txt
- setup.py
This uses https://github.com/pypa/pip/issues/5761 to install matplotlib first. Also pins to at least matplotlib 3.0, since there are some `constrained_layout`s in there.
> Update install order

- arviz/tests/conftest.py
- arviz/tests/test_plots.py
The code here lets you save plots on testing. If this functionality and interface is acceptable I'll write up documentation and submit in another PR. 
Can you guys try this out and let me know what you think? I have not tested on Windows yet but I'm pretty sure I handled all the problems that would arise from the file system being locked from people leave images open, or leaving Windows Explorer open in the images directory
I want to make it possible to develop plots for ArviZ in the following way.
1. Think of idea for a plot addition, feature, change, or new plot entirely
2. Write code in arviz
3. Write some side code to verify your plot is working
4. Write a test to generate image your code is working as expected
5. Skip step 3 because by writing the test you can generate the image and …
> Save plots on testing

- arviz/plots/posteriorplot.py
This code used to throw an exception for `fig` being undefined, and another for passing `linewidth` twice. It now runs fine:
```python
fig, ax = plt.subplots(nrows=2, ncols=3, figsize=figsize, constrained_layout=True, sharex=True)
az.plot_posterior(rugby, var_names=['atts'], textsize=20, linewidth=6, ax=ax)
```
> Allow passing axes and linewidth to plot_posterior

- arviz/stats/diagnostics.py
- arviz/stats/stats.py
* Summary was failing for single chain posteriors
* Change the format for the hpd to only print significant digits
* Shorten some names (standard deviation --> sd, gelman-rubin statistics --> gelman-rubin). Why we change r-hat? It was not the proper name?
* add round_to argument (default to 2)
* I also change the indentation. Sorry about this, but I really dislike how the code was formatted with lines exclusively for parentheses and code indentation not matching previous level.
> fix summary for single chain and minor aesthetic tweaks

- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- examples/plot_compare.py
- examples/plot_forest.py
- examples/plot_forest_ridge.py
- examples/plot_kde.py
- examples/plot_pair.py
- examples/plot_pair_kde.py
- examples/plot_parallel.py
- examples/plot_posterior.py
- examples/plot_ppc_cumulative.py
- examples/plot_violin.py
I made several few changes, like trying to make some of the plots look nicer, being consistent with quotes marks, use list to pass `var_names` instead of tuples (I think this is less prone to errors and also the docs says that a list is expected).
> minor tweaks to examples and plot_posterior docstring

- examples/plot_pair.py
Typo got into the examples, and broke docs.
> Fix examples

- arviz/plots/khatplot.py
Addresses #359. My new approach only autoscales the markersize if it has not been explicitly specified by the user. Differently put: a user-specified markersize has preference over markersizes determined via autoscaling, otherwise autoscaled markersizes are used (as before).
> fix: markersize argument is unused for khat plots

- arviz/data/__init__.py
- arviz/data/datasets.py
- arviz/data/io_netcdf.py
- arviz/plots/parallelplot.py
- arviz/tests/test_data.py
This design borrows heavily from scikit-learn. 
I trained and uploaded a model [from the pymc3 docs to figshare](https://figshare.com/articles/radon_nc/7215344), and added the ability to download it using arviz. The first usage takes a little while, the second usage is cached. I think this feature could allow sharing models trained in many different libraries, which is super exciting.
Here is what the new "UI" looks like. Also pinging @fonnesbeck in case he has feedback on the description of the radon model (or other concerns):
```python
print(az.list_datasets())
```
```pythontb
centered_eight
==============
A centered parameterization of the eight schools model. Provided as an example of a
model that NUTS has trouble fitting. Compare to …
```
> Start model zoo

- arviz/plots/ppcplot.py
Adds api examples for the plot_ppc function. Closes #355 
Let me know if there are edits/other examples you want added. 
In my html builds, the legends were defaulting quite large and covering up a lot of the plots. I also used the provided radon example data rather than the eight schools since the distributions are less wonky and make for a cleaner example in my opinion. Let me know if you would prefer the eight schools to fit with the other examples on the site.
> DOC: add api examples for plot_ppc. #355

- arviz/stats/stats.py
- arviz/tests/test_stats.py
This add the option to smooth the output of a hpd, I hope this helps to get nicer plots and less confused students/audience. I did not do extensive testing but seems that the parameters I am using for `Savitzky-Golay` generally work, but I am open to suggestions. Should we let the user select those parameters?
> smooth hpd

- arviz/plots/traceplot.py
- arviz/tests/test_plots.py
Fixes #385 
This adds vertical dashed lines wherever there are divergences. I have turned it on by default mostly to be provocative - I'm ok to have it off by default.  I sort of like that the markers are visually distracting whenever you *should* be distracted by divergences.
A lot of the shuffling of the code was done so that these lines (and the `lines` argument) would not change the x or y limits of the plots. Note that this happens on master right now!
Here is an example of the output for the centered and non-centered eight schools:
> Trace divergence

- arviz/plots/kdeplot.py
Changes:
* Rugplot are plotted below zero (avoid overlapping with the KDE).
* add a new keyword to `rug_kwargs` `space`, this keyword control the location of the rugplot (as a proportion of `max(density)`), this also allows to have more than one rugplot with-out overlapping.  See this example:
> KDE: rugplot position

- .pylintrc
- arviz/__init__.py
- arviz/tests/helpers.py
Generating models takes a long time in tests, providing messages should help with understanding status
> Add logging to test helpers model generation

- arviz/plots/densityplot.py
This permits plot_density to be used to, e.g., plot density
information for prior samples.
> Add optional 'group' param to plot_density.

- arviz/__init__.py
- setup.py
Following discussion with @ahartikainen this PR proposes an alternative way to make ArviZ styles available without the need to copy files to matplotlib config folder. This should fix #377
> make arviz styles available without copy them

- arviz/plots/styles/arviz-colors.mplstyle
- arviz/plots/styles/arviz-white.mplstyle
- arviz/plots/styles/arviz-whitegrid.mplstyle
- examples/styles.py
Also adds one example and increase the default dpi from 72 to 100.
The `arviz-white` style is for those that dislike having a grid and a background (for _strict Tufte followers_), the `arviz-colors` style is for those that want to any style they might like but with our color discrete pallet.
> Add arviz-white and arviz-colors styles

- arviz/plots/styles/arviz-white.mplstyle
- examples/styles.py
This creates a single figure with subplots with different styles. Also adds the correct parameters for `arviz-white` style.
> make single figure, fix arviz-white style

- doc/_static/custom.css
I think the headers in our docs seem a bit large. Let me know if anyone agrees
**Current**
**Resized**
> Resize headers in Sphinx docs

- arviz/plots/pairplot.py
- arviz/tests/test_plots.py
This removes the need to use gridspec and use `plot` instead of `scatter`. I did not run a formal benchmark, but it seems to run faster now. I also changed how divergences are rendered and now the auto-scaling works better.
some pics :-)
> plot_pair: Refactor code and minor tweaks

- arviz/plots/kdeplot.py
Before this PR,
to get a plot like this one:
One should explicitly pass the axes to `plot_kde`, now we can just write
```python
plt.figure(figsize=(10,4))
az.plot_kde(data1, rug=True)
az.plot_kde(data2, rug=True, plot_kwargs={'color':'C1'});
plt.yticks([])
```
or 
```python
_, ax = plt.subplots(figsize=(10,4))
az.plot_kde(data1, rug=True)
az.plot_kde(data2, rug=True, plot_kwargs={'color':'C1'});
ax.set_yticks([]);
```
While being there :-) I made another change now `fill_last` argument also affects the countour lines, when `fill_last = False` we get:
instead of:
> get axes from current figure

- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/posteriorplot.py
I add `wrap=True` to several plots, as I realize tittle get cropped for the saved figures (but not to the figures rendered inside notebooks)
> wrap titles

- arviz/plots/plot_utils.py
- arviz/plots/ppcplot.py
- arviz/tests/test_plots.py
This pull request adds two new sets of features to the plot_ppc function:
1. Variable subsetting: Added var_names, coords, and flatten parameters to allow for sub-selection and gridding of variables across dimensions.
2. Plot style control: Added obs_plot_style, pp_plot_style, and pp_flatten parameters to allow for better control of plotting styles. This was particularly in response to the "wonkiness" of density plots for datasets with few observations (like the current eight schools example).
Needs more work and clean up to be merged, but first wanted to get feedback on the new API design approach. Do these changes seem reasonable? Is there a better way to do it?
See below for examples and see the updated docstring for more in depth parameter descriptions.
> WIP: Add parameter indexing & plot style support to plot_ppc #375

- .travis.yml
- doc/conf.py
Docs are currently broken. This fixes the docs on my local machine. I don't know why this only popped up now, but probably good to add the root directory to the sphinx build.
This looks like a big PR because `black` ran on `conf.py`, but the only real change is 
```python
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
```
which is a portable way to add `../` to the path.
> Add root directory to conf.py

- arviz/plots/compareplot.py
- arviz/plots/energyplot.py
- arviz/plots/jointplot.py
- arviz/plots/khatplot.py
- arviz/plots/pairplot.py
- arviz/plots/parallelplot.py
- arviz/plots/plot_utils.py
- arviz/plots/violinplot.py
This fixes a few layout problems with titles and labels running off the side of the plot.
For example, the `plot_ppc` docs currently look like this:
and with this change look like this:
> Use constrained layout everywhere

- arviz/data/io_pyro.py
As per #462 - we should only expand the dimension of the samples if the number of chains is 1. Please note I have not tested this for pyro versions less than 0.3.
For the example in the #462, this now correctly prints:
```python
>>> az.summary(data)
mean    sd  mc error  hpd 3%  hpd 97%  eff_n  r_hat
alpha    45.46  0.08       0.0   45.30    45.59  142.0   1.00
beta[0]   1.25  0.08       0.0    1.11     1.41  164.0   1.01
beta[1]   2.21  0.09       0.0    2.05     2.40  141.0   1.00
sigma     0.79  0.06       0.0    0.69     0.89   77.0   1.00
```
when running with 2 chains.
> fix for from_pyro with multiple chains

- .coveragerc
- .travis.yml
- requirements-dev.txt
- scripts/Dockerfile
- scripts/create_testenv.sh
Trying to get testing to be done in containers
> [WIP] Add Docker Testing to travisCI

- .pylintrc
- .travis.yml
- arviz/data/converters.py
- arviz/data/io_pystan.py
- arviz/tests/helpers.py
- arviz/tests/test_data.py
- scripts/create_testenv.sh
Support PyStan3
Automatic dtypes and `observed_data` needs `posterior_model`.
This PR implements the same groups as does PyStan 2.x code.
> Support PyStan3

- arviz/plots/forestplot.py
- arviz/stats/__init__.py
- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/tests/test_diagnostics.py
- doc/api.rst
Update R-hat calculation to use Split R-hat described in BDA3.
Follows calculation done in https://github.com/stan-dev/pystan/blob/develop/pystan/_chains.pyx
> Use Split R-hat

- paper/paper.md
Moved funding bullet up which for some reason fixes plots. Let me know if this is acceptable.
Rendered PDF is attached
[paper.pdf](https://github.com/arviz-devs/arviz/files/2722088/paper.pdf)
Rendered using pandoc 1.19.2.4
```
pandoc --filter pandoc-citeproc --bibliography=paper.bib  --variable papersize=a4paper -s paper.md -o paper.pdf
```
[paper.pdf](https://github.com/arviz-devs/arviz/files/2722091/paper.pdf)
Commit https://github.com/arviz-devs/arviz/pull/484/commits/5e1322c0d9268032fb3b636897277701258f1722
> Fix example gallery in paper

- doc/_static/custom.css
- doc/conf.py
- doc/notebooks/XarrayforArviZ.ipynb
Will add InferenceData tutorial in header to meet paper review feedback.
In making this documentation I tried first creating a Tutorial page like Seaborn
https://seaborn.pydata.org/tutorial.html
However it seems getting to this will require more work. Seaborn doesn't use the nbconvert plugin, instead providing its own Makefiles and scripts that convert the notebooks to .rst and .html at the appropriate times
https://github.com/mwaskom/seaborn/blob/master/doc/Makefile
https://github.com/mwaskom/seaborn/tree/master/doc/tools
https://github.com/mwaskom/seaborn/blob/master/doc/tutorial/Makefile
I think it would be great to implement this eventually, but for now just want to get the existing tutorial visible for the paper review
> Add InferenceData tutorial in header

- requirements-dev.txt
Pytest updated to version 4.1.0 which is causing failures with coverage
Pinning version for now and can open issue ticket so we remember to check on this every now and then
Additional details for future reference
https://docs.pytest.org/en/latest/changelog.html
> Pin pytest version to avoid coverage exceptions

- arviz/plots/kdeplot.py
- arviz/tests/test_plots.py
- examples/plot_kde_quantiles.py
This add the option to get a KDE segmented into quartiles (or more general quantiles). There are still a few things to fix and improve
> KDE: Display quantiles

- arviz/plots/forestplot.py
- arviz/stats/__init__.py
- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/tests/test_diagnostics.py
Trying to make it more clear to users and newcomers to Bayesian methodology what calculation is being done and where to look for further reference
Review requested more for the idea of the change, and less so the code.
I can add deprecation or rename warning to `n_effective` to make this a non breaking change
> Rename N_effective to S_effective

- arviz/data/__init__.py
- arviz/data/io_dict.py
- arviz/tests/test_data.py
Implements `from_dict` function that follows the format in other `from_xyz`.
This makes it easier to import raw numpy data.
> From dict function

- requirements.txt
Numpy 1.16 breaks Theano / PyMC3
> Force numpy 1.15 until pymc3 is fixed.

- arviz/data/io_pymc3.py
I am not sure how this worked in the past, but it looks like we definitely want `pymc3.util` (https://github.com/pymc-devs/pymc3/blob/master/pymc3/util.py) instead of `pymc3.utils` (which resolves to `pymc3.glm.utils`, and does not have `get_default_varnames`).
> Fix pymc3 typo

- arviz/plots/kdeplot.py
- arviz/tests/test_utils.py
- arviz/utils.py
- requirements-dev.txt
adds the conditional_jit decorator that works only if numba is installed. I applied the decorator to speed-up _fast_kde. I guess other functions (stats, diagnostics) could benefit more from using numba.
> add conditional_jit decorator and speed up _fast_kde 2x

- arviz/plots/forestplot.py
- arviz/tests/test_plots.py
The new argument rope adds a shaded region of practical equivalence for all displayed variables in forestplot, shade is controlled by rope_alpha (default =.5). Contrary to posteriorplot rope can only be a tuple of length 2.
Not big but it is highly useful for me hence I assume it should be useful for others too.
> Added rope to forestplot.py in forestplot()

- arviz/plots/kdeplot.py
- arviz/plots/ppcplot.py
- arviz/tests/test_plots.py
Adds support for multichain ppc.
Also implements jitter for scatter and changes alpha defaults for scatter.
> Support multichain ppc in plot_ppc

- arviz/data/io_dict.py
See also #539 .
Trailing commata in combination with keyword-only function definitions are only supported in Python >= 3.6 and thus break support for Python3.5.
As pointed out in #539, this is a problem introduced in `black` and subject to an issue there as well.
This PR removes trailing commas in `arviz/data/io_dict.py` manually. After these changes, `python -c "import arviz"` works without error.
> Remove trailing commata in `arviz/data/io_dict.py`

- .travis.yml
- arviz/tests/test_data.py
We didn't have python arg set-up. (`PYTHON_VERSION=3.6 `)
Which meant that this code was executed
```
PYTHON_VERSION=${PYTHON_VERSION:-${TRAVIS_PYTHON_VERSION:-3.6}}
```
> Fix docker python version

- arviz/data/__init__.py
- arviz/data/inference_data.py
- arviz/tests/test_data.py
This PR implements a simple group-level addition for InferenceData objects. The addition is only supported with unique groups
A._groups == ["posterior", "posterior_predictive"]
B._groups == ["prior", "prior_predictive"]
X._groups == ["prior"]
C = A + B
C = az.concat(A, B)
C = az.concat((A, B))
C._groups ==["posterior", "posterior_predictive", "prior", "prior_predictive"]
az.concat(A, B, inplace=True)
A._groups ==["posterior", "posterior_predictive", "prior", "prior_predictive"]
A + "hello" --> TypeError
B + X --> NotImplementedError
If `copy=True` function will `deepcopy` groups to a new location (this means that if `inplace=True` then first object's groups are not touched). Otherwise, a reference is passed to a new group.
> az.concat and __add__ - Simple group level addition

- arviz/plots/plot_utils.py
- arviz/tests/test_plot_utils.py
Fixes #554. My local environment is a little broken, so I want to make sure unittests pass while I write a test for this case. This works on the examples from the issue, though.
```
data = az.from_pymc3(trace=trace, coords={'schools': list('abcdefgh')}, dims={'theta': ['schools']})
az.plot_forest(data, var_names='theta')
```
> Maintain order of variables in xarray_var_iter

- arviz/plots/ppcplot.py
- arviz/tests/test_plots.py
Some examples
`kind=density`
`kind=scatter`
`kind=cumulative`
`kind=density` discrete variables
> add animations to plot_ppc

- .travis.yml
- arviz/tests/conftest.py
Make dir in test_images (which raises OSError. Btw this is a good design, the user can make "old" folder for old images while testing)
Use khat to test saving. It makes only one plot.
> Update conftest testing

- arviz/plots/plot_utils.py
- arviz/tests/test_plot_utils.py
Previously the order returned was always alphabetical due to use of np.unique(). Now the order of the provided coords are respected.
> Fix to plot ordering

- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/jointplot.py
- arviz/plots/pairplot.py
- arviz/plots/parallelplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/ppcplot.py
- arviz/plots/traceplot.py
- arviz/plots/violinplot.py
- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/tests/test_utils.py
- arviz/utils.py
This allow to pass a variable to `var_names` and get all the variables except the one that was passed.
Thus if `data` is a model with variables names ['mu', 'theta', 'tau']
```python
az.plot_joint(data, var_names=['~theta']);
```
returns
One caveat is that variables names are then no allowed to starts with `~`.
> negate variable names

- arviz/plots/forestplot.py
- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/tests/test_diagnostics.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats.py
This PR makes ess to return float if NaN is seen.
Until there exists a way to return integer dtype with NaN, this is the best option.
Let's follow how xarray evolves with this issue. https://github.com/pydata/xarray/issues/1194
Also I noticed that there was many `n_eff` left so I changed them to ess.
> Fix nan handling and fix n_eff to ess

- arviz/data/io_pystan.py
- arviz/tests/test_data.py
Fixes bug where PyStan<=2.17 was unpacking in wrong locations due to the difference between PyStan 2.18 and 2.17.
> PyStan 0-based indexing vs 1-based indexing

- arviz/plots/kdeplot.py
- arviz/tests/test_plots.py
This fixes #581. Also add tests and add `xmin` and `xmax` arguments to `_fast_kde`. After internal discussion we decided not to add xmin-xmax arguments to `plot_kde`.
> fix kde scaling

- arviz/plots/traceplot.py
I was not able to reproduce the error reported at #585, but this fix may fix #585 or at least a related problem.
> fix xticks for discrete variables

- arviz/stats/stats.py
- arviz/tests/test_stats.py
This PR enables one to use a dictionary in stat_funcs. This way the user can name the functions and use lambda with the correct name.
stat_funcs=[np.std]
stat_funcs={"std" : np.std, "std_ddof1" : lambda x: np.std(x, ddof=1)}
> Add dictionary option for stat_funcs in summary

- arviz/plots/compareplot.py
- arviz/plots/kdeplot.py
- arviz/stats/stats.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats.py
This PR gives three options for scaling
- `deviation` (default) = -2
- `log` (following Vehtari et al.) = 1
- `neglog` = -1
This also adds `loo_scale`/`waic_scale` column for the results.
I also added `kss` if user wants elementwise results. This makes it easier to use `kss`.
> Increase loo-results and select scale

- arviz/data/inference_data.py
- arviz/data/io_netcdf.py
- arviz/tests/test_data.py
> Improving the behaviour of an empty InferenceData object. (Issue no 486).

- arviz/plots/kdeplot.py
- arviz/plots/posteriorplot.py
- arviz/tests/test_plots.py
Made the following changes:
* Using inference data or xr.dataset with plot_kde now raises an error prompting the user to use plot_posterior instead.
* Rug plots displayed by default for plot_posterior plots.
* Not included the tests yet.
> Addressing issue number #470 (using plot_kde with inference data object) 

- arviz/plots/kdeplot.py
Currently `plot_kde` fails if all the elements of the input array are `nan` or `inf` or exactly the same number, or for very short array (less than 3 or so). Functions like `plot_trace` will fail for those cases too, and only variables before the failing point will be plotted.
With this PR if `plot_kde` fails (at least for the cases mentioned before.) we get an empty plot and a warning message.
> kde warning and empty plot

- CONTRIBUTING.md
I am no docker expert, but as I am trying to develop and test arviz using it, I think it will be useful to update the instructions with the things I have had to do different from what is written. 
I updated some filenames which were incorrect, and some basic instructions on how to run a notebook. `jupyter` is not installed by default in the docker image, therefore one of the steps is installing it, however, the docker image could also be modified.
Related to #421.
> Update Docker instructions

- arviz/plots/forestplot.py
I added OrderedDict module from collections to keep the structure of the InferenceData object. This applies to both the variable names and the dimensions within the variable names. Fixes #613
> Added orderedDict to forestplot

- arviz/tests/helpers.py
- arviz/tests/test_data.py
In order to adress Issue #390 I started creating a function that performs multiple `hasattr` checks and returns a list of tuples containing `(object, attribute)` for the failed tests, as proposed. I have included an extra argument `parent` to account for the fact that most of the checks are on the same object and/or on childs of the same object. 
I have replaced one of the multiple checks instances for a call to this helper function, to show its possible usage. I have used `assert len(failed_checks) == 0` instead of `assert failed_checks == []` because its message when failing is much more clear to me:
**`len == 0` message**
E  AssertionError: assert 2 == 0
E    +  where 2 = len([(<xarray.Dataset>\nDimensions:  (A_dim_0: 2, B_dim_0: 5, B_dim_1: 2, chain: 2, draw: 10)\nCoordinates:\n  * …
> Helper method for tests

- arviz/plots/__init__.py
- arviz/plots/rankplot.py
- arviz/tests/test_plots.py
This implements `plot_rank`, as described in #621. This still lacks tests, but wanted to get comments on some styling choices I was already making, specifically:
1. Dotted line in the background to show what a uniform histogram would look like.
2. All chains plotted in one axis
3. Using `bins='auto'` by default. In the paper, it looks like a lot of bins were chosen, but I do not understand why. You can replicate that behavior by manually passing a number of bins (see examples below).
It might make sense to also make this an optional panel in a traceplot, in which case the "artist" should get factored out.
```python
data = az.load_arviz_data('centered_eight')
az.plot_rank(data, ['mu', 'tau', 'theta'], coords={'school': ['Choate', 'Deerfield']})
```
```python
data = …
```
> Add rankplot

- doc/index.rst
I *thought* it looked wrong, but kept looking for a misspelling (lot's of "L"s to double or not double), and didn't notice it was backwards.
> Colin's name was backwards

- doc/api.rst
- examples/plot_rank.py
This adds an example, and also adds it to the api docs (which includes inline examples).
> Add rankplot to docs

- arviz/plots/kdeplot.py
- arviz/plots/pairplot.py
- arviz/tests/test_plots.py
It should fix the issue with missing divergence data (I choose to use a `warnings.warn` instead of logging following #620) and added kwarg arguments for contourf and pcolormesh in `plot_kde`.
> Pair plot fixes and kde extra options. Fixes #602

- arviz/plots/kdeplot.py
This commit fixes the legend display in `plot_kde` as discussed in #643. The issue of plot_energy legend has not been resolved yet.
> Improving the legend display in plot_kde and plot_energy. Fixes #643

- .pylintrc
- arviz/data/__init__.py
- arviz/data/converters.py
- arviz/data/io_cmdstan.py
- arviz/data/io_cmdstanpy.py
Implements `from_cmdstanpy`
Also fixes `convert` function to correctly handle different special groups and enables also `from_cmdstan` if input is a `list` or `str` that endswith `.csv`.
> implement from_cmdstanpy

- arviz/data/__init__.py
- arviz/data/io_netcdf.py
- arviz/tests/test_data.py
This PR could be merged after the release of 0.4.
> Removed load_data & save_data functions and tests. Fixes #495

- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- doc/conf.py
Minor fixes on stats module docs and adding examples. Fixes #631
> Stats docs

- arviz/plots/plot_utils.py
- arviz/plots/traceplot.py
- arviz/tests/test_plots.py
For now still minor fixes. Still not gone into facet/compact styles. Should fix #654.
**EDIT**
Already gone into facet/compact styles. Reviews and advise welcome. The idea is to end up fixing both #94 and #609.
> Traceplot fixes

- arviz/data/io_pymc3.py
Fixes #682
This fixes a bug that kept the shared theano array after `np.atleast1d`.
This PR checks first if value has `get_value` and transform theano array to numpy array if `get_value`  is true.
I let our pymc experts to fix this implementation and also decide if other methods need to be fixed.
> Handle pm.Data on observed data

- arviz/data/io_pymc3.py
This fixes the following warning whenever `from_pymc3` is called: 
```
/arviz/arviz/data/io_pymc3.py:56: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
chain_likelihoods.append(np.stack(log_like))
```
> Fix warning from io_pymc3

- arviz/data/inference_data.py
- arviz/data/io_emcee.py
- arviz/tests/helpers.py
- arviz/tests/test_data.py
I have started working on some emcee related improvements. It all started because of a warning about the "draws" and "chains" of the observed data, and little by little I started adding more functionalities:
* observed data is no longer created via a call to `dict_to_dataset`, thus, it won't have draw and chain dims anymore.
* `from_emcee` now has support for blobs, allowing to easily store the log_likelihood, posterior_predictive... I have tested it in both emcee2 and 3 locally, I will add tests and examples when I find some time.
* I added a `.sel()` method to InferenceData objects. It is basically thought for performing a burn-in on emcee objects (emcee has no warm-up nor burn-in by default, so at some point, the first iterations must be removed). It only takes kwargs, loops over all …
> Emcee improvements

- doc/logo/generate_logo.py
Add `clip_on=True` so ArviZ text doesn't go outside the logo area
> Clip text in logo

- arviz/plots/__init__.py
- arviz/plots/elpdplot.py
- arviz/plots/plot_utils.py
- arviz/plots/pointwiseelpdplot.py
- arviz/stats/__init__.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats.py
- arviz/tests/test_stats_utils.py
- doc/api.rst
PR to improve the output of waic and loo to make it more verbose and to create the pointwise elpd comparison plot. Will fix #496 and will fix #660.
This first version of the plot already works, but there is still much work needed.
Data from the toy model in [this notebook](https://github.com/OriolAbril/Bayesian-Inference-examples/blob/master/Binomial_on_2D_data/binomial_on_2D_data_intention_pystan.ipynb). This was generated with `color="river_distance"` and `legend=True`.
Added a `threshold` argument in order to show labels of point further away than threshold times elpd_i.std(). In the example, `threshold=1` to force showing the labels.
See #501 for some more detail.
Everything working after some corrections, still debating between reshaping pointwise loo/waic to original shape or work …
> pointwise elpd diagnostics (text formatting and plot)

- arviz/plots/elpdplot.py
Forced axis sharing so that axis ticks are coherent with the data. Axis were not shared, and there was no guarantee that the elpd difference between different models will be on the same scale. 
I also modified the constrained_layout/tight_layout options, I think now all cases use constrained layout if possible and if not, tight_layout is called after plotting.
> Fix plot_elpd  axis

- requirements-dev.txt
tfp 0.7 has just been released, so now tensorflow 1.14 is a requirement
> CI broken again

- arviz/data/io_pymc3.py
- arviz/tests/test_data_pymc.py
`form_pymc` currently stores all posterior predictive samples in 1 chain. Therefore, the default case, where an array of shape `(nchains*ndraws, *shape)` is returned, the posterior_predictive dataset has shape `(1,nchains*ndraws, *shape)`, instead of being `(nchains, ndraws, *shape)` (which would be the same shape as the log_likelihood for instance). 
I have modified for it to work in the following cases:
* `(nchains, ndraws, *shape)` -> `(nchains, ndraws, *shape)`
* `(nchains*ndraws, *shape)` -> `(nchains, ndraws, *shape)`
and for nsamples different than nchains*ndraws:
* `(nsamples, *shape)` -> `(1, nsamples, *shape)` plus a `logging.warning`
> Improve pymc posterior predictive handling

- arviz/plots/posteriorplot.py
- arviz/tests/test_utils.py
- arviz/utils.py
Uses the code from #705, but re-simplifies the API to have only the single formatting option. Right now formatting will be the integer part or `round_to`, whichever is bigger.
@rpgoldman tagging you in case you have opinions.
```python
az.plot_posterior(data, ['mu', 'tau']);
```
```python
az.plot_posterior(data, ['mu', 'tau'], round_to=0);
```
```python
az.plot_posterior(data, ['mu', 'tau'], round_to=5);
```
> Centralize number formatting.

- arviz/plots/__init__.py
- arviz/plots/essplot.py
- arviz/stats/diagnostics.py
- arviz/tests/test_diagnostics.py
- arviz/tests/test_plots.py
- doc/api.rst
Add the plots for new ess (#621).
Example plots on the centered eight dataset. The default appearance is quite simple:
But it can be customized to look like the plots in the reference paper for example:
I have set the same default appearance for both quantile and local, differing from the paper, because I think that using a hist like plot can be misleading. Now the only difference is the ylabel, which can be confusing to someone not familiar with this kind of plots. Would you rather have different appearance between quantile and local ess plots?
> New ess plots

- arviz/plots/__init__.py
- doc/api.rst
- examples/plot_elpd.py
- examples/plot_ess_evolution.py
- examples/plot_ess_local.py
- examples/plot_ess_quantile.py
I also sorted alphabetically both the functions in the `api.rst` file and in `plot/__init__.py` to ease the comparison.
> Add missing examples and functions in api [GSoC]

- arviz/plots/traceplot.py
I modified `theta_t_dim_0` to `school`, and I did not realize it broke the traceplot docs because I forgot to delete the generated folder from a previous doc build.
> Fix docs example due to modified coord name

- arviz/data/io_pymc3.py
- arviz/tests/test_data_pymc.py
Fixes the problem, when MultiObservedRV does not contain observations (DensityDist)
See https://discourse.pymc.io/t/pm-traceplot-error/3524
> No observations in MultiObservedRV

- arviz/stats/diagnostics.py
- arviz/tests/test_utils.py
- arviz/utils.py
This looks a little complicated, but my goals were:
1. Docs should appear on decorated functions
2. Toggling `az.Numba.enable_numba()` and `az.Numba.disable_numba()` should work
3. Limit overhead when using numba (since that's the point)
The first is done with `functools.wraps`
The second is done in `__call__` in `maybe_numba_fn`
The third is done using a lazy property: it compiles the first time it is called, and then is an attribute lookup. This might be overkill, I feel least strongly about that. The alternative would evaluate something like `if self._numba_fn is None:` on every function call, which is not a ton of overhead.
There is one failing test with a lot of monkeypatching!
> Update conditional_jit wrapper

- arviz/__init__.py
- arviz/plots/khatplot.py
- arviz/utils.py
- doc/_templates/class.rst
- doc/api.rst
- examples/plot_khat.py
```python
plt.plot(...) # inline
with interactive_backend():
plt.plot(...) # interactive
plt.plot(...) # inine
```
For now, a prototype of this class is present in ArviZ home. It seems to work, I will be on the lookout for issues. 
I decided not to use CamelCase even though it is implemented as a class because most context managers are in lowercase. One example is `matplotlib.rc_context` itself. `interactive_backend` is based on `rc_context` and in addition, `rc_context` is the reason why it is defined as a class and not with `contextlib`.
* Add hover labels to `plot_elpd`? If eventually added, they will be added in a following PR.
> Khat plot: hover tweaking [GSoC]

- arviz/plots/compareplot.py
- arviz/stats/stats.py
Fix #733
Also in case people do crazy stuff like sorting the compare DataFrame, `plot_compare` will resort the DataFrame by default, so the plot makes sense.
> make order of model in compare df explicit

- arviz/data/datasets.py
I have verified this works locally. The description of the dataset is in the PR:
>The Six Nations Championship is a yearly rugby competition between Italy, Ireland,
Scotland, England, France and Wales. Fifteen games are played each year, representing
all combinations of the six teams.
This example uses and includes results from 2014 - 2017, comprising 60 total
games. It models latent parameters for each team's attack and defense, as well
as a parameter for home team advantage.
See https://docs.pymc.io/notebooks/rugby_analytics.html by Peader Coyle
for more details and references.
I have also updated `load_arviz_data` so calling it with no parameters returns a dictionary, which makes it a little easier to work with.
Previous behavior was to throw a `ValueError` with the information in it.
> Add rugby dataset

- arviz/data/datasets.py
This adds two synthetic datasets to figshare, and then to arviz. They are both synthetic datasets, and described in the PR. Fixes #242. 
Will merge before scipy sprints start if there are no objections in the meantime.
> Add regression datasets

- arviz/stats/stats.py
Should fix #740 for multidim objects (their log_likelihood has shape `chain, draw, *shape` where `*shape` is `>=2D`.
> Fix az.compare for multidimensional obsects

- arviz/data/converters.py
- doc/api.rst
Small fix, this should only affect the convert functions and the `from_cmdstanpy` already works.
RunSet --> StanFit
CmdStanPy is now in pypi https://pypi.org/project/cmdstanpy/
> Update CmdStanPy fit class name

- arviz/stats/stats.py
I didn't like the warning message having a bunch of line breaks like this
So I made some changes
> Add line break fix for warning

- arviz/tests/helpers.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats.py
Following #748, this PR adds test on multidimensional objects `shape(log_likelihood) = (chain, draw, dim1, dim2)` to `test_stats.py`, in order to find issues like #740 in CI tests. Thus, `compare`, `waic`, `loo`, and `loo_pit` are now tested on the `centered_eight` data and on the `multidim_models` fixture
> Add multidim tests to test_stats [GSOC]

- arviz/plots/forestplot.py
Fixes https://github.com/pymc-devs/pymc3/issues/3515. I am not sure if just like this is enough or if we have strong aesthetic arguments against grid lines in forestplot. It can always be sub-seeded to a `grid` argument defaulting to false.
> grid lines in plot_forest

- arviz/plots/ppcplot.py
- arviz/tests/test_plots.py
Add `ax` argument to `plot_ppc`. I have added checks for the number of axes and for having all axes in the same figure when `animated=Ture` in `plot_ppc` and tests to assert both the new argument and the checks work.
> Add ax argument to plot_ppc

- doc/api.rst
`az.effective_sample_size` was removed in #770, but it was still listed in the api section of the docs.
> Remove effective sample size from docs

- arviz/plots/essplot.py
- arviz/plots/mcseplot.py
I don't know why I thought `argsort` could be used for ranking data. Today I have realized that the rug values were not placed where they were supposed to be. Now they are.
> Fix issue with rug values in plot_ess and plot_mcse

- arviz/plots/essplot.py
- arviz/plots/forestplot.py
- arviz/plots/kdeplot.py
- arviz/plots/khatplot.py
- arviz/plots/parallelplot.py
- arviz/plots/plot_utils.py
- arviz/plots/rankplot.py
- arviz/stats/diagnostics.py
- arviz/stats/stats_utils.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats_utils.py
- arviz/tests/test_utils.py
- arviz/utils.py
- benchmarks/benchmarks.py
This optimizes `_fast_kde_2d`. `_fast_kde` was already optimized via the `conditional_jit` on `np.histogram` which greatly reduced my work with plots. This should optimize a lot of other plots as many of them are built on top of `plot_kde`. A few minor additions on the remaining plots and plot_utils need to be added. A caveat though, in most of the cases of plots, the bottlenecks are matplotlib plotting methods which are not compatible with numba `no-python` mode. I am however, trying my best to optimize the plots as much as possible :).
> Numba-plots

- arviz/__init__.py
- arviz/data/inference_data.py
- arviz/data/io_netcdf.py
- arviz/plots/elpdplot.py
- arviz/rcparams.py
- arviz/stats/stats.py
- arviz/tests/test_diagnostics.py
- arviz/tests/test_plots.py
- arviz/tests/test_rcparams.py
- arviz/tests/test_stats.py
- arvizrc.template
- doc/api.rst
- doc/conf.py
Set ArviZ global options as rcParams, following the behaviour of matplotlib's rcParams. The idea is to have a slightly simplified version of matplotlib's implementation. For now and as an example, only 3 parameters are present. This PR itself can be used to propose and discuss other possible global parameters.
Closes #609 and closes #706.
Below I will write (and keep updating the list) to check that all relevant functions and docs have been updated:
rcParams modification and loading from different folders and files should already work. However, all of it is still preliminary. The folders do not make much sense yet, the parameters can be modified in `az.rcParams` but the functions have not been updated yet either... Please review and comment.
> [WIP] Set up ArviZ rcParams

- arviz/plots/ppcplot.py
This changes how we compute the posterior predictive mean when `kind='density'`. Currently we do a KDE using all the posterior predictive samples as input. With this PR we average the (binned) densities. In an ideal world this should be equivalent, but in practice there are some generally (small) differences. 
One problem with the current implementation is that we could have something like this
The mean is not _inside_ the _envelope_ defined by the individual pp samples. This picture is from Chris Fonnesbeck.
In the following examples I reproduce the same effect, although with a less obvious effect, please zoom-in or use a very wide screen :-). The blue lines are the pp samples, the orange lines are the mean using the KDE (over all the pp samples) and the green lines are the average of …
> plot_ppc: change mean computation

- arviz/plots/loopitplot.py
- arviz/tests/test_plots.py
At first I decided to not include the variable name in the LOO-PIT plot, but I am changing my mind. I have not followed plot_ppc and used the var_name as xlabel, because unlike there, the x values are not variable values. I am inclined towards adding the name in the legend, but the title could also be an option. Now it looks like this, it is a minor change.
> Add var name in LOO-PIT legend [GSOC]

- arviz/data/io_pymc3.py
`from_pymc` would overwrite the "log_likelihood" dimensions defined in "dims" parameter, which in multivariate cases where the shape of the observations and of the log likelihood is different gives an error of wrong number of dimensions. 
I have left using the same dims as the observed data as a default, which in most cases is the case, but giving preference to "log_likelihood" dimensions defined in the dims argument in case they are present.
I am not sure if there should be a test for this, I can add one.
> fix from_pymc bug for multivariate observations

- arviz/stats/stats.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats.py
Methods that require stacking chains and draws will now expect a "sample" dim, following "chain" and "draw" dim names.
> rename "samples" dim to "sample" for coherence

- arviz/plots/plot_utils.py
- arviz/plots/ppcplot.py
- arviz/plots/rankplot.py
As discussed in slack, this PR will try to improve performance (mainly RAM usage, but in some cases, execution time will improve too) by preallocating large arrays instead of having them grow inside loops.
> preallocate potentially large arrays

- scripts/create_testenv.sh
~~This should fix pytorch installation.~~ Problem was not actually with pytorch installation, but I think the changes are still useful.
I have seen that version 1.2.0 has just been released, and with it, recommended method shown in their website has been modified too. In my opinion, now it is quite more sensible and it should install cpu wheel of latest version automatically, so pytorch_version env variable will only be used for old versions and we will always be running tests on latest pytorch, no need to update it manuallly from time to time. We may have the same trouble as with tfp if pyro and pytorch releases are not coordinated though.
> Modify pytorch installation in create env script

- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/elpdplot.py
- arviz/plots/essplot.py
- arviz/plots/mcseplot.py
- arviz/plots/pairplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/plots/ppcplot.py
- arviz/plots/rankplot.py
- arviz/plots/traceplot.py
- arviz/plots/violinplot.py
- arviz/rcparams.py
- arviz/tests/test.rcparams
- arviz/tests/test_plot_utils.py
- arviz/tests/test_plots.py
- arviz/tests/test_rcparams.py
Integrates "plot.max_subplots" with all plotting functions. It works on a subplot basis with 3 exceptions:
* In traceplot, the thershold is interpreted as a limit on the variable number, thus, the total number of subplots can be the double of "plot.max_subplots" as there are 2 subplots per variable.
* In plot pair and plot elpd, as they plot on a pairwise basis using a square grid, the limit is implemented truncating on the number of "filled" plots. Some examples: 5 variables to be plotted generate a 4x4 grid, with 1, 2, 3 and 4 plots per row, a total of 10 "filled" plots. Therefore, `"plot.max_subplots"=8` would plot 3 variables, even though they generate 6 "filled" plots because it actually generates 9 subplots.
Comments on improvements on the warning messages are particularly …
> implement plot.max_subplots rcParam in all functions

- requirements-dev.txt
> fix how pymc3 is specified in extras_require

- arviz/plots/posteriorplot.py
This fixes two warnings in the docs. It was pointed out that the documentation is currently borked, so I may merge this if tests pass in hopes of fixing the docs. If that doesn't work, I can do it manually.
> Fix docstring for posteriorplot

- doc/conf.py
I recreated the doc problem locally, and this fixed it. It was a problem going from Sphinx 2.1.2 to 2.2.0. I am still ok leaving Sphinx unpinned, since it is sort of nice being forced to use the latest.
> New sphinx wont make directories

- arviz/plots/posteriorplot.py
- arviz/tests/test_plots.py
closes #513 
This do not reduce the weirdness but clarifies how to use the `dict` option and allows  to pass a `list`, that may be simpler in many cases.
> plot_posterior: specify ref_val using a list and add example of how to use a dict

- arviz/plots/posteriorplot.py
One of the examples in `plot_posterior` related to `ref_val` usage raised an error and the image was not shown.
> Fix warning in ref_val example of plot_posterior

- arviz/data/inference_data.py
- arviz/data/io_emcee.py
- doc/_templates/class_members.rst
- doc/api.rst
Fixes #711. 
This PR adds an entrance to the API section named InferenceData which links to the following page:
At the same time, each entrance listed in the Methods section links to a page for each method. The one for `sel` looks like this:
This is achieved using the `class_members` template (as opposite to the `class` template used for `Numba` or `interactive_backend` classes). It also extends the documentation on `InferenceData` and its `__init__` and `sel` mehtods.
> Add InferenceData class to docs

- arviz/data/io_pymc3.py
Importing from PyMC3 in the absence of a posterior trace works  poorly -- `from_pymc3` uses its posterior trace argument, and a backdoor into the PyMC3 model object to inform its translation.  If the posterior trace is missing, it doesn't have enough information to interpret the posterior or prior trace dictionaries.
But one *definitely* needs these because out-of-sample prediction from a model may yield traces of different shape than the posterior trace.
This attempts to fix by allowing the user to specify a pymc3 model to `from_pymc3`.
> Improve import of posterior and prior predictive traces from PyMC3

- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/hpdplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/plots/violinplot.py
- arviz/stats/stats.py
- arviz/tests/test_plot_utils.py
- arviz/tests/test_plots.py
- arviz/tests/test_stats.py
- arviz/tests/test_utils.py
- arviz/utils.py
Introduces a new argument `multimodal` to `az.hpd`, if `True` (defaults) it may compute more than 1 hpd interval if the distribution is multimodal and the modes are _well separated_. For `plot_posterior` `multimodal = True` by default and we may get something like:
if `multimodal = False` (or the older behaviour)
For all other functions/plots, like `summary`,`plot_forest` etc  `multimodal = False`, mainly because at the moment I am not sure how to handle more than one interval.
> Hpd intervals

- arviz/tests/test_data_pymc.py
~Fixes #822~ and adds a test to check behaviour of `from_pymc3` when trace is `None`.
EDIT: Only adds the test as a follow-up to #833.
> Add tests for adding posterior_predictive without trace

- .travis.yml
- arviz/data/io_pyro.py
- arviz/tests/helpers.py
- arviz/tests/test_data_pyro.py
- azure-pipelines.yml
- doc/notebooks/InferenceDataCookbook.ipynb
- requirements-dev.txt
Addresses #845. In this PR, I added
+ posterior_predictive
+ diverging stat
+ prior + prior_predictive
and remove `observed_data` because it is not accessible for now (will support it for the next Pyro release).
It is pretty complicated to make it compatible with the old Pyro API so I also drop that support.
cc @OriolAbril
> Update for pyro 0.5

- arviz/plots/distplot.py
- arviz/plots/forestplot.py
- arviz/plots/jointplot.py
- arviz/plots/plot_utils.py
- arviz/tests/test_plot_utils.py
- arviz/tests/test_plots.py
- examples/plot_forest.py
- examples/plot_forest_ridge.py
Most `plot_xyz` have `coords` and `ax` arguments, but there are some exceptions. This PR intends to add these arguments in all functions (if they make sense, `plot_compare` will continue not having `coords` argument). 
I have started with `plot_forest`, fixes #813. Similarly to what happened in `plot_density`, it can also accept a list of inferencedata objects, so I modified `get_coords`. I set it to accept 3 combinations: 
* dataset and coords dict, 
* list of datasets and coords dict
* list of dataset and list of coords dicts
This allows to handle idata objects with different dimensions, but I am not totally convinced by this approach. Any ideas will be welcome.
`ax` argument added to `plot_joint`
> Add coords and ax arguments to all plotting functions

- arviz/data/io_tfp.py
I a basically pushing this PR to see if it would fix #456, I have not had time to do much testing, I'll try to in the following days. If somebody feels like giving it a try in the meantime feel free!
> Add chain_dim as from_tfp argument

- arviz/data/__init__.py
- arviz/data/base.py
- arviz/data/converters.py
- arviz/stats/stats.py
- arviz/tests/test_data.py
- Revise the documentation string to explain that it returns either a
DataFrame or a DataSet.
- Add some type information.
- Add coords and dims arguments.
> Extend the summary function.

- arviz/plots/plot_utils.py
- arviz/plots/rankplot.py
- arviz/tests/test_plots_matplotlib.py
... and few other minor changes.
`kind = "bars"`
`kind = "vlines"`
When using `vlines` we have `ax.set_ylim(0, all_counts.mean() * 2)`, that is the height is 2 times the value of `ref_line`. This makes easier to see if a deviation is "large" or not.
in a next PR I would like to add the ranks (probably with the vlines as default) to trace plot, something like this:
or with `bars`
> add vlines to rank plot

- arviz/stats/stats.py
- arviz/tests/test_stats.py
`loo` currently checks if `posterior` is in the `InferenceData` near the beginning of the method, even though it is only needed if `reff` is not provided. This PR makes it so `posterior` is only required if `reff` is not provided.
> Don't require posterior in loo if not used. Also make errors more dispassionate.

- README.md
- arviz/plots/rankplot.py
- doc/index.rst
It also fixes the example of plot_rank with vlines which I saw was not working
> Add ArviZ.jl to readme and docs

- arviz/rcparams.py
- arviz/tests/test_rcparams.py
- arvizrc.template
Related to #792 and to #877.
Adds parameters `plot.backend`, `plot.point_estimate`, `stats.credible_interval` and `stats.ic_scale` to rcparams dict. However it does not modify the functions to use them. I think that now than most if not all plots will be tinkered with it is a good moment to get everything ready so that integrating rcparms is only calling them.
Handling of none is tricky. For instance, `None` is a valid value of `plot.point_estimate` meaning no point estimate. In this cases, I propose setting the default to `"auto"` so that auto means look up the value in rcparams. In general, using `None` as look up rcparams should be fine.
> Add more parameters to rcparams

- arviz/rcparams.py
- arviz/tests/bad.rcparams
- arviz/tests/test.rcparams
- arviz/tests/test_rcparams.py
Also increases testing of rcparams
> Make rcparams more robust and explicit

- arviz/data/io_numpyro.py
- arviz/data/io_pymc3.py
- arviz/data/io_pyro.py
- arviz/tests/test_data_numpyro.py
- arviz/tests/test_data_pymc.py
- arviz/tests/test_data_pyro.py
Currently, pymc3 and pyro store both prior and prior predictive in the `prior` group. This aims to fix the issue when possible.
Only ~numpyro~ and ~updating docs (cookbook and schema example) is missing.~
EDIT: 
numpyro is done and the schema is still in a too early phase, I don't think we need to update the examples every PR
> separate prior from prior predictive variables

- arviz/data/inference_data.py
- arviz/tests/test_data.py
Fixes #907. I have added a unit test which catches this error (as the concat would only catch the last group it iterated over).
> InferenceData keeps all groups

- CONTRIBUTING.md
We found in testing that you need to slightly modify the commands used for opening a Jupyter notebook hosted in Docker so that it loads the correct version of Python (with all the packages from `requirements.txt`). This does the proper opening. Fixes #936 .
> Swap out docker jupyter commands, fixes #936

- arviz/stats/stats.py
- arviz/tests/test_stats.py
Sometimes I do not want summary to return diagnostics, one use case is when teaching. Showing diagnostics but deferring explanations generates anxiety. I guess there are many other use cases so the PR :-)
> Summary: add option to return diagnostic, stats or both (default)

- requirements.txt
Python 3.7 + jax + numpy 1.18 have some problems, let's constrain numpy version until this bug has been fixed by jax -package.
> constrain numpy version temporarily

- arviz/data/io_pyro.py
- arviz/tests/helpers.py
- arviz/tests/test_data_pyro.py
- doc/notebooks/InferenceDataCookbook.ipynb
This PR addresses the remaining issue of #853. Users can get information criterions with from_pyro now.
> Support log_likelihood and obs data for pyro io

- arviz/data/io_cmdstanpy.py
When extracting *prior* samples from cmdstanpy output, the call to `_unpack_frame()`, *posterior* samples were being unpacked. I fixed this so that prior samples are unpacked.
> Fixed bug in extracting prior samples for cmdstanpy.

- arviz/plots/backends/__init__.py
- arviz/plots/plot_utils.py
- arviz/stats/stats.py
- arviz/tests/test_utils.py
- arviz/utils.py
This PR creates ColumnDataSource from the inference_data.
utils:
function to transform inference data groups to dictionary (flattened against selected dimensions)
backends:
function to create CDS object. Data as DataFrame.
The main idea is to create CDS either from `posterior_groups` or `prior_groups` so a user can plot multiple bokeh plots with the same CDS, which enables linked select.
> infrerence_data to ColumnDataSource (bokeh)

- arviz/stats/diagnostics.py
- arviz/tests/test_diagnostics.py
Correction for bfmi formula implementation according to page 7 of [this paper](https://arxiv.org/pdf/1604.00695v1.pdf).
Fixes #858.
> Correct bfmi denominator (fixes #858)

- arviz/utils.py
Removed parallel arguement from numba @conditional_jit in arviz.utils.full
fixes #904
> Remove parallel from arviz.utils.full (fixes #904)

- arviz/plots/backends/__init__.py
- arviz/tests/test_utils.py
- arviz/utils.py
Renamed ```flat_inference_data_to_dict``` to ```flatten_inference_data_to_dict```.
fixes #999
> rename flat_inference_data_to_dict (fixes #999)

- arviz/plots/backends/bokeh/ppcplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/ppcplot.py
> [WIP] Add group argument in plot_ppc (fix #1002)

- arviz/plots/__init__.py
- arviz/plots/backends/bokeh/densityplot.py
- arviz/plots/backends/bokeh/forestplot.py
- arviz/plots/backends/bokeh/posteriorplot.py
- arviz/plots/backends/matplotlib/densityplot.py
- arviz/plots/backends/matplotlib/forestplot.py
- arviz/plots/backends/matplotlib/loopitplot.py
- arviz/plots/backends/matplotlib/posteriorplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/backends/matplotlib/violinplot.py
- arviz/plots/densityplot.py
- arviz/plots/kdeplot.py
- arviz/plots/loopitplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/tests/test_diagnostics.py
- arviz/tests/test_plots_bokeh.py
- arviz/tests/test_plots_matplotlib.py
Fixes #992 . The following changes are made:
> Solve issue #992 : Integrate point_estimate with rcParam

- CHANGELOG.md
- arviz/data/__init__.py
- arviz/data/base.py
- arviz/data/inference_data.pyi
- arviz/data/io_pymc3.py
- arviz/tests/test_data_pymc.py
In this approach, unlike the one outlined in the schema, the `constant_data` contains the constant data used to generate the *predictions* not to generate the posterior_trace.
This could be modified, but I took this decision because the posterior trace used to generate the predictions in general CANNOT be the same as the posterior trace created by pymc3.sample() -- variables whose shape depends on the shape of the constant data or the observations must be removed.
> Populate InferenceData with out-of-sample prediction results from PyMC3 predictive samples

- arviz/plots/backends/bokeh/violinplot.py
- arviz/plots/backends/matplotlib/violinplot.py
- arviz/plots/violinplot.py
The "violin" plot had problem for discrete variables. This fix it and also add the option to display a jittered "rug" plot (defaults to False).
I still needs to add the "rug" for bokeh
> Violinplot:  fix histogram, add rug

- arviz/plots/jointplot.py
- arviz/plots/ppcplot.py
- examples/matplotlib/mpl_plot_ppc.py
> [WIP] Add group argument to plot_joint

- CHANGELOG.md
- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/plots/hpdplot.py
- arviz/plots/loopitplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/violinplot.py
- arviz/stats/stats.py
Fixes #986 . The param credible_interval takes default value from rcParam.
> Integrated credible_interval with rcParam

- arviz/data/base.py
- arviz/data/io_dict.py
- arviz/data/io_emcee.py
- arviz/plots/backends/bokeh/elpdplot.py
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/backends/matplotlib/elpdplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/densityplot.py
- arviz/plots/pairplot.py
- arviz/plots/plot_utils.py
- arviz/plots/traceplot.py
- arviz/tests/test_data.py
- arviz/tests/test_data_emcee.py
- arviz/tests/test_plot_utils.py
- arviz/tests/test_plots_bokeh.py
- arviz/tests/test_plots_matplotlib.py
This addresses issue #104, by converting every instance of `SyntaxWarning` in the codebase into `UserWarning`. (There are only 23 instances in the end, not the 54 I initially thought; I don't know how I came up with 54 yesterday when I opened the issue!)
For the record, here's the command I ran to do this:
```shell
$ grep -rl SyntaxWarning . | xargs sed -i '' 's/SyntaxWarning/UserWarning/g'
```
Tests are passing locally in docker following the instructions in `CONTRIBUTING.md`, as is pylint.
> Convert all instances of SyntaxWarning to UserWarning

- arviz/data/io_pyro.py
This resolves the issue raized at pyro [forum](https://forum.pyro.ai/t/the-arviz-function-from-pyro-has-mismatching-dimensions/1515). In Pyro, each variable dimension should be declared as `independent` or `dependent`. MCMC class relaxes this restriction a bit so some incorrect Pyro models still work. However, utilities such as `get_vectorized_trace` (used in `sample_stats_to_xarray`) require that declaration. This PR disables log_likelihood computation for those incorrect Pyro models. Because there are many reasons to trigger the issue, I  add a universal `try ... except ...` here to capture all of them.
> not compute log_likelihood if vectorized trace cannot be obtained in Pyro

- paper/paper.md
I'm doing some analyses of all JOSS papers, and discovered that the `yaml` header of yours is not quite formatted properly - there was a stray white space following the end `---`, which this PR fixes.
> Fix yaml formatting in paper.md

- CHANGELOG.md
- arviz/plots/posteriorplot.py
> Integrate point estimate posterior plot

- CHANGELOG.md
- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
- arviz/tests/test_diagnostics.py
- arviz/tests/test_stats.py
- arviz/tests/test_stats_utils.py
I also moved some functions (`_sqrt`,  `_angle`, `_circfunc`, `_circular_standard_deviation`) from `diagnostics` to `stats_utils`. The original motivation was to reproduce and example from statistical rethinking [code 7.42](https://github.com/pymc-devs/resources/blob/master/Rethinking_2/Chp_04.ipynb).
> add skipna argument to hpd and summary (only for stats)

- arviz/data/io_pymc3.py
- arviz/tests/test_data_pymc.py
> Bug fix of PyMC3 model that contains Potential

- CHANGELOG.md
- arviz/plots/hpdplot.py
plot_hpd performs a linear interpolation before smoothing a hpd interval. This fix ensures that the points were the interpolation is evaluated are "inside" the data. 
Before
after
> ensure interpolation for plot_hpd always works

- arviz/data/io_pymc3.py
If sampling in pymc3 is aborted with Ctrl-C, it might create a trace that does not include chain 0.
> Fix arviz conversion of incomplete pymc3 traces

- .travis.yml
- CHANGELOG.md
- arviz/data/io_numpyro.py
- arviz/data/io_pyro.py
- arviz/tests/test_data_numpyro.py
- arviz/tests/test_data_pyro.py
- azure-pipelines.yml
- requirements-dev.txt
Follows #796, for Pyro and NumPyro: I added "log_likelihood" to InferenceData, and added tests for multiple observed variables. 
Thanks for a Pyro/NumPyro expert to review this (@fehiepsi maybe?). Indeed, I am not entirely sure about the Pyro part: the test_multiple_observed_rv fails if y2 and y1 have different dimensions. 
For the rest, I copied io_pymc3.py, in particular for coord_name and dims.
Sorry in advance for the possible mistakes, it's my first commit.
> Move pointwise log likelihood data to log_likelihood group (Pyro + NumPyro)

- CHANGELOG.md
- arviz/plots/backends/bokeh/densityplot.py
- arviz/plots/backends/bokeh/posteriorplot.py
- arviz/plots/backends/matplotlib/densityplot.py
- arviz/plots/backends/matplotlib/posteriorplot.py
Hello everyone. I have made some changes in density and posterior plot. Bins were not computed using the `get_bins` function. Also `plot_density` did not take the `ax` argument.
Before
After
> use get_bins function to compute bins for density and posterior plot

- CHANGELOG.md
- arviz/data/io_pymc3.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/ppcplot.py
- arviz/tests/helpers.py
- arviz/tests/test_data_pymc.py
Try to improve handling of prior groups and observed data in `io_pymc3`. Related to #1002. It introduces an important change in behaviour, it proposes to exclude the `observed_data` group whenever predictions are present. @corriebar @rpgoldman 
I also extended tests on `io_pymc` and improved the helper function `check_multiple_attrs`.
And finally, ~how do you feel about deprecating the use of `from_pymc3` without model nor trace (or even without model). I was thinking on adding a warning.~ For now not using a model nor trace will raise a pending deprecation warning as a start. @canyon289 @aloctavodia @ColCarroll 
Related to #939. 
PR format?
> extend model arg usage in io_pymc3 to fix plot_ppc with prior

- CHANGELOG.md
- arviz/plots/compareplot.py
- arviz/plots/elpdplot.py
- arviz/rcparams.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
- arviz/tests/test_plots_bokeh.py
- arviz/tests/test_plots_matplotlib.py
- arviz/tests/test_stats.py
- arvizrc.template
Use loo as  a default cross validation method.
Use log -scale as a default cross validation scale.
This is to make our results compatible with R ecosystem (loo) by default.
PR format?
> Update cross validation defaults: loo and log -scale

- arviz/stats/stats.py
`hpd` makes a redundant copy for the unimodal use case since the input array is not being modified. 
Wrote some code just to double check:
```
a = np.random.random((5000,))
b = a.copy()
hpd(b, 0.9)
assert np.array_equal(a, b)
```
> Remove hpd redundant copy

- CHANGELOG.md
- arviz/data/io_pyro.py
Currently, ```io_pyro``` adds an extra dim to the data variables in ```prior```. This is because the pyro data is 2D (column vector) and calling ```expand_dims``` on this creates a 3D variable with an unwanted dim.
This is to fix that behaviour.
> Fix io_pyro prior dims

- README.md
- codecov.yml
- doc/index.rst
I'd like to force codecov to wait before commenting. I find it can be quite confusing to new contributors to have a "this pr will decrease code coverage a 14%" for several minutes (from the end of base tests to the end of external tests)
Also updated the badge.
> Codecov follow-up

- CHANGELOG.md
- arviz/plots/backends/bokeh/traceplot.py
- arviz/plots/backends/matplotlib/traceplot.py
- arviz/plots/plot_utils.py
- arviz/plots/traceplot.py
- arviz/rcparams.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arvizrc.template
Fixes #837. Allows customization of properties to distinguish lines in the same subplot with all combinations of combine and compact. Introduces arguments `compact_prop` and `chain_prop` with format `(property_name, (value1, value2...))` to set color, linestyle, linewidth...
Matplotlib version is kind of working, only labels are missing, plot format is OK. Bokeh is still more preliminar. It would also be interesting to implement interactive legends in bokeh for traceplot, but I currently do not plan to do this here.
> Traceplot legend

- codecov.yml
`after_n_builds` is not valid in `comment` section. According to [codecov community](https://community.codecov.io/t/how-to-troubleshoot-ignored-yaml-file/1102/2), this should solve the issue (codecov is currently ignoring the yaml basically)
> Use valid codecov.yml

- arviz/data/io_pymc3.py
The check for whether the PyMC3 model has been found looked at the model variable, instead of the model property.
This fixes a false positive deprecation warning.
> Fix model warning.

- arviz/stats/stats_utils.py
Currently `az.hpd` uses a recursive pattern to compute hpd values for 1d or 2d arrays. It would be great to create an `_hpd` function that is then used by `az.hpd` via `wrap_xarray_ufunc` (like it is done with ess, rhat...). 
I have realized that `make_ufunc` does not support the function returning extra output dimensions, which would be needed for hpd to work and return a single array. This extends `make_ufunc` and improves slightly the defaults for `wrap_xarray_ufunc`. 
There is one drawback/divergence from the ufunc default arguments. `xr.apply_ufunc` performs a separate call of the ufunc for each data variable (in the case of datasets) but the kwargs passed to the ufunc are always the same for all data variables. This behaviour makes the `out` argument not usable when the shapes of …
> extend make_ufunc and improve wrap_xarray_ufunc defaults

- arviz/plots/autocorrplot.py
- arviz/plots/densityplot.py
- arviz/plots/essplot.py
- arviz/plots/mcseplot.py
- arviz/plots/pairplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/ppcplot.py
- arviz/plots/rankplot.py
- arviz/plots/violinplot.py
Previously, this specified the `ax` argument as taking an (optional)
axes.  This is incorrect: it takes a 2D array of axes or bokeh figures.
Perhaps we should explicitly point out that a 2D array is required.  The code requires *at least* 2D, but I'm not sure what would happen if one passed a higher-dimensional array.
> Revise docstring for plot_density().

- arviz/stats/stats_utils.py
- arviz/tests/base_tests/test_stats_utils.py
Regarding the tests and docstring for new kwarg 'out_shape' passed to `make_ufunc`
> Add test and docstring for out_shape kwarg

- CHANGELOG.md
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/pairplot.py
- examples/bokeh/bokeh_plot_joint.py
- examples/bokeh/bokeh_plot_pair_point_estimate.py
- examples/matplotlib/mpl_plot_joint.py
- examples/matplotlib/mpl_plot_pair_point_estimate.py
I added new examples for plot_pair. I tried to showcase in them the possibility of obtaining cornerplots, as mentioned in #1079. I also fixed some bugs. This PR solves #1105 . 
I tried to build the documentation locally, but I was having trouble with docker. I was later explained that this isn't a requirement.
> [WIP] add new examples for plot_pair

- CHANGELOG.md
- arviz/plots/densityplot.py
- arviz/plots/forestplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
`plot_density` and `plot_forest` both accept a list or tuple of InferenceData, but the `transform` argument was not iterating through the list or tuple when it should. This was causing something like `az.plot_forest(idata var_names=["a"], transform=scipy.special.expit)` to raise a `TypeError: ufunc 'expit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`.
I think the modifications I made will fix this issue -- please tell me if you have any comment.
Thanks and cheers 🖖
> Fix bug in `transform` arg when InferenceData is List or Tuple

- CHANGELOG.md
- arviz/data/io_pyro.py
- arviz/tests/external_tests/test_data_pyro.py
Add the following groups to `io_pyro`:
Tests:
> [WIP] Add new groups to io_pyro

- .azure-pipelines/azure-pipelines-external.yml
- examples/bokeh/bokeh_plot_joint.py
- examples/bokeh/bokeh_plot_pair_point_estimate.py
- examples/matplotlib/mpl_plot_pair_point_estimate.py
CI currently uses black as formatter, code is formatted but changes are not saved and bad formatting does not fail CI jobs.
> use black as linter

- CHANGELOG.md
- arviz/data/converters.py
- arviz/tests/base_tests/test_data.py
This PR is not related to any issue but, as Discussed in #1104 I have made changes to converter.py to allow dataarray input
Consider following code snippet-
`import arviz as az`
`import numpy as np`
`import xarray as xr`
`xarr=xr.DataArray(np.random.randn(6,2),name="nm",dims=('chains', 'draw'),coords={'draw':[1,2]})`
`az.plot_posterior(xarr,var_names="nm")`
`
**Output without changes-**  
Traceback (most recent call last):
> File "/home/smit/gsoc/repro.py", line 6, in <module>
az.plot_posterior(xarr,var_names="nm")
File "/home/smit/gsoc/local/arv/lib/python3.6/site-packages/arviz-0.7.0-py3.6.egg/arviz/plots/posteriorplot.py", line 184, in plot_posterior
data = convert_to_dataset(data, group=group)
File "/home/smit/gsoc/local/arv/lib/python3.6/site-packages/arviz-0.7.0-py3.6.egg/arviz/data/ …
> Allow xarray.Dataarray input to plots.

- .azure-pipelines/azure-pipelines-base.yml
- .azure-pipelines/azure-pipelines-external.yml
- .gitignore
- CHANGELOG.md
- arviz/tests/base_tests/test_diagnostics.py
- arviz/tests/base_tests/test_diagnostics_numba.py
- arviz/tests/base_tests/test_helpers.py
- arviz/tests/base_tests/test_plot_utils.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/base_tests/test_stats.py
- arviz/tests/base_tests/test_stats_numba.py
- arviz/tests/base_tests/test_utils.py
- arviz/tests/base_tests/test_utils_numba.py
- arviz/tests/external_tests/test_data_cmdstanpy.py
- arviz/tests/external_tests/test_data_emcee.py
- arviz/tests/external_tests/test_data_numpyro.py
- arviz/tests/external_tests/test_data_pymc.py
- arviz/tests/external_tests/test_data_pyro.py
- arviz/tests/external_tests/test_data_pystan.py
- arviz/tests/external_tests/test_data_tfp.py
- arviz/tests/helpers.py
- pytest.ini
When running all tests locally `ImportError`s are thrown if optional/extra dependencies are not installed. By skipping these tests when not installed, users can still run the entire test suite if desired. The entire test suite should still be run via CI.
This behavior is largely achieved by changing
```python
import xx
```
to
```python
xx = pytest.importorskip(xx)
```
which will try to import module `xx`, and will skip all tests in file if the module is not installed.
Individual tests may also be skipped using the decorator:
```python
@pytest.mark.skipif(importlib.util.find_spec("xx") is None, reason="xx tests only required for CI")
```
The last remaining issue is `numba`, which is used in 20+ tests, used in a variety of files. One option is to make `numba` an entry in …
> Skip tests for optional/extra dependencies when not installed

- arviz/data/converters.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/external_tests/test_data_numpyro.py
- arviz/tests/external_tests/test_data_pymc.py
> allow overlaid pairplots

- arviz/data/inference_data.py
- arviz/data/inference_data.pyi
- arviz/data/io_pystan.py
- arviz/plots/backends/__init__.py
- arviz/rcparams.py
- arviz/tests/external_tests/test_data_pystan.py
- arviz/tests/helpers.py
- arviz/utils.py
- arvizrc.template
Implement save_warmup for PyStan.
Adds `_groups_warmup` to `InferenceData`.
Warmup groups must start with `_warmup_`.
> Add warmup iterations and _group_warmup

- CHANGELOG.md
- arviz/plots/backends/bokeh/traceplot.py
- arviz/plots/backends/matplotlib/traceplot.py
- arviz/plots/traceplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- examples/bokeh/bokeh_plot_trace_bars.py
- examples/bokeh/bokeh_plot_trace_vlines.py
- examples/matplotlib/mpl_plot_trace_bars.py
- examples/matplotlib/mpl_plot_trace_vlines.py
Integrates rank plots into `plot_trace` via the new keyword `kind`, defaults to `kind=trace`
`kind=rank_vlines`
`kind=rank_bars`
> add option to display rank plots instead of trace

- CHANGELOG.md
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/pairplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This PR adds the argument `true_values` in `plot_pair`. It allows for scattering the true values of a variable as suggested in #1131.
> New argument for plotting true values in pairplots

- CHANGELOG.md
- arviz/data/io_dict.py
- arviz/data/io_numpyro.py
- arviz/data/io_pymc3.py
- arviz/data/io_pyro.py
- arviz/tests/external_tests/test_data_numpyro.py
Fixes #1030 
Add the following groups:
> [WIP] Add new groups to from_numpyro and from_dict

- CHANGELOG.md
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
- arviz/tests/base_tests/test_stats.py
This PR adds a reminder about log scale default and how it should be interpreted (higher is better) for `az.waic` and `az.loo`. This merely mirrors what we already say in the doc.
For `az.compare` I added a `UserWarning` following the change to log scale in 0.7.0. This adresses [this issue](https://github.com/pymc-devs/pymc3/issues/3874), and the warning will be temporary, as discussed in the issue.
In passing, I trailed all the white spaces before colons in the docstrings of `stats.py`. This messes up the formatting on the website.
I'm here for any change, and thanks in advance for the review 🖖
> Add warning for log scale default in compare/loo/waic functions

- arviz/stats/diagnostics.py
Small fixes to the ess docstring
> add local to docstring, and use lowercase for ess

- CHANGELOG.md
- arviz/plots/backends/matplotlib/posteriorplot.py
Fix bug in `plot_posterior` when show rcParam is set to true.
> hardcode show=False in plot_posterior subplots

- arviz/plots/pairplot.py
The `kind` argument to pairplot was incorrectly described in the docstring.  Fixed to point out that it can be a list of strings.
Also there was a deprecation warning whose logic was wrong -- a user could be warned about a deprecated argument that they did not use.
Changes too trivial to be worth a Changelong entry.
> Fix documentation and deprecation warning in pair plot

- arviz/plots/styles/arviz-darkgrid.mplstyle
- arviz/plots/styles/arviz-white.mplstyle
- arviz/plots/styles/arviz-whitegrid.mplstyle
Following discussion #1159 this adds viridis as the default cmap, except for `arviz-colors.mplstyle` that intentionally only modifies the color cycle.
> add viridis as default cmap

- CHANGELOG.md
- arviz/plots/kdeplot.py
- examples/matplotlib/mpl_plot_kde_2d_bis.py
Following #1157 this add examples to the docstring of `plot_kde` and a new example to the gallery. 
This also sets `fill_last=False` as the default, because nobody likes the previous setting :-)
> add examples to customize 2D KDE

- .pylintrc
- CHANGELOG.md
- arviz/data/base.py
- arviz/plots/autocorrplot.py
- arviz/plots/essplot.py
- arviz/plots/forestplot.py
- arviz/plots/jointplot.py
- arviz/plots/mcseplot.py
- arviz/plots/pairplot.py
- arviz/plots/parallelplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/ppcplot.py
- arviz/plots/rankplot.py
- arviz/plots/traceplot.py
- arviz/plots/violinplot.py
- arviz/stats/stats.py
- arviz/tests/base_tests/test_utils.py
- arviz/utils.py
- Currently, users can select variables entering `az.summary` and other plotting/diagnostics functions with the `var_names` kwarg. 
This selection must however be exact, meaning that if you have variables with similar names in your trace, you have to specify them all: `az.summary(idata, var_names=["alpha", "beta1", "beta2", "beta3"])`, which can be cumbersome for big models.
- This PR introduces the `filter_like` kwarg to allow users to select _all_ variables containing the given word. For instance, `az.summary(idata, var_names=["alpha", "beta"], filter_like=True)` would give the same result as above. This also works to _exclude_ variables with similar names: `az.summary(idata, var_names=["~beta"], filter_like=True)`
- `filter_like` defaults to `False` to ensure backwards-compatibility. …
> Add `filter` feature for `var_names`

- CHANGELOG.md
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/pairplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This PR addresses issue #1166. I also reduced marginal plot size in joint plots and changed the argument name `diagonal` for `marginals`.
> [WIP] Fix point estimate marker kwargs

- CHANGELOG.md
- arviz/__init__.py
- arviz/data/inference_data.py
- arviz/data/inference_data.pyi
- arviz/data/io_pymc3.py
- arviz/plots/backends/__init__.py
- arviz/tests/external_tests/test_data_pymc.py
- arviz/tests/external_tests/test_data_pystan.py
- arviz/utils.py
- scripts/container.sh
Support warmup groups in `from_pymc3`. It should already work, but I have not figured out the dependencies of the whole thing (it may only work on pymc3 master) nor added any test yet. 
Will fix #1146
> support warmup groups in from_pymc3

- CHANGELOG.md
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/khatplot.py
- arviz/plots/plot_utils.py
- arviz/tests/base_tests/test_plot_utils.py
This PR addresses issue #1169.
> Pairplot of two variables with bokeh

- CHANGELOG.md
- arviz/rcparams.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
- arviz/tests/base_tests/test_stats.py
- arviz/tests/base_tests/test_stats_utils.py
- arviz/tests/helpers.py
- arvizrc.template
Given the number of possibilities and the even larger number of things that can go wrong, I propose to add only a `var_name` argument (or `name`/`log_likelihood` to avoid confusion with `var_names` that can be a list) and force users to manually add the combined log likelihood data on which they want to calculate loo/waic to `log_likelihood` group. 
We could add some `var_names` arg instead and a `combine` arg to sum or concat or maybe even try to cover groupby too, but this will always be more limited that creating the new variable and it will also be more obscure (i.e. two variables with the default coord names `var1_dim_0` and `var2_dim_0` will be broadcasted to a 2d array when added because their coord names are different, if the user has to manually create the dataarray of pointwise …
> [proposal] support for IC with multiple variables

- CHANGELOG.md
- arviz/plots/backends/__init__.py
Fixes #1177 
Fix import when docstrings are missing.
> Fix empty docstring

- arviz/data/inference_data.py
- arviz/rcparams.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_rcparams.py
- arviz/tests/base_tests/test_utils.py
- arviz/utils.py
- arvizrc.template
Add metagroups rcParam (very open to better names!). The idea is to have a dictionary storing customizable aliases for lists of groups. This does not have many uses right now, but I think it will be really helpful to have once we start adding more methods to inference data objects. 
Unless there are some objections, I plan to update `InferenceData.sel()` and `to_cds` to use these metagroups.
Related to #1066 
This PR proposes some new features, all of them trying to make inferencedata objects more usable and closely related. 
Applies any function to multiple groups in the inference data object.
Applies an `xarray.Dataset` method to multiple groups in the inference data. This had the long term idea in mind to define methods like `load` or `mean` directly as attributes of inferencedata …
> Metagroups and InferenceData.map

- CHANGELOG.md
- arviz/plots/backends/matplotlib/densityplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
> fix passing axes to plot_density with several datasets

- CHANGELOG.md
- arviz/data/io_pymc3.py
bugfix for io_pymc3, there was one self.nchains that should have been self.ndraws. Fixes #1202
> fix bug in io_pymc3 and add warning for PyMC3<3.9

- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/traceplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Minor changes to matplotlib subplot handling in `plot_trace` and `plot_pair`. 
In `plot_trace` `plot.max_subplots` used to be checked on the number of rows in plot trace, this PR fixes it to check the actual number of subplots. 
I also checked the behaviour in plot_pair to check that it takes into account the actual number of _used_ subplots with or without marginals. I have also modified axes creation to avoid having extra blank spaces at the top and right of with `marginals=False` (see https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_pair.html for example)
> fixes to matplotlib subplot handling

- .azure-pipelines/azure-pipelines-external.yml
- arviz/tests/external_tests/test_data_pymc.py
We missed a bug that could have been caught testing on latest pymc3 release, given that we do have 2 external CI jobs, I have configured it so that one runs on master and another on latest release.
> test on both pymc3 master and release

- arviz/__init__.py
- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
This is a hotfix for #1208 
In short: When traces are sliced manually, the `n_draws` information is lost. With the latest arviz version, this breaks some PyMC3 tests and potentially user workflows.
These changes modify how `n_draws` is checked such that it falls back to the previous behavior when `n_draws` is unavailable.
> Deal with PyMC3 traces that do not contain n_draws information in the sampler report

- CHANGELOG.md
- arviz/__init__.py
- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
Slicing the trace from the end caused #1210.
This PR improves the test to detect the issue and implements the fix.
I feel bad for having to bump the version number again..
> Support pymc3 traces with no draws or no tuning

- CHANGELOG.md
- arviz/plots/kdeplot.py
This small text fix adds a reference to `plot_pair`, rather than just to `plot_posterior`, when
using `plot_kde` on `InferenceData`. This prevents people from trying and failing to use `plot_posterior` to plot 2D KDEs.
Shoutout and thanks to @OriolAbril, who helped me with finding that function on Gitter :)
> Add note on `plot_pair` to `plot_kde(InferenceData)` `ValueError`

- CHANGELOG.md
- arviz/plots/hdiplot.py
Fixes  #1193. 
Have corrected the capitalization inconsistency pointed out in the issue and added '.' wherever missing.
About updating the changelog, should I add it under v0.x.x Unreleased or under v0.8.3 (2020 May 28)? Kindly help out in that regard
> Fix inconsistent capitalization in plot_hdi docstring

- CHANGELOG.md
- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
closes #384. Data from `MultiObservedRV` will now be added to `observed_data` group by `from_pymc3`
> add MultiObservedRVs to observed_data

- GOVERNANCE.md
Added a very basic generic stub. Looked at other projects but most don't really have this section filled out. @fonnesbeck gave me some tips, and I looked at matplotlibs and it says to refer to a section that doesn't exist :)
https://github.com/matplotlib/governance/blob/master/governance.md
In general though I think there's two broad paths. We let the council decide how they want to do this, or we try and make strict now so the process is consistent across councils. Please share opinions if you have any.
The outcome of this is that we need to have a general process as well as responsibility holder, It doesnt need to happen before this PR is merged, but it does need to be communicated when we apply for financial sponsorship
> Add finances section

- CHANGELOG.md
- arviz/stats/stats.py
hpd forwarding to hdi has a bug where it ignores user arguments
Here's a small example
```
def function_1(value="a", **kwargs):
function_2(value="TheWrongVal", **kwargs)
def function_2(value=None, **kwargs):
print(value)
function_1("a")
function_1("test_val")
```
> Fix keyword ignores

- CHANGELOG.md
- arviz/plots/backends/bokeh/forestplot.py
- arviz/plots/backends/bokeh/hdiplot.py
- arviz/plots/backends/matplotlib/forestplot.py
- arviz/plots/backends/matplotlib/hdiplot.py
- arviz/plots/essplot.py
- arviz/plots/forestplot.py
- arviz/plots/hdiplot.py
- arviz/plots/loopitplot.py
- arviz/stats/stats.py
HDI is an acronym, so it should be capitalized. Currently, it is "HDI" in some places and "hdi" in others (e.g. `plot_forest`):
This PR makes capitalization consistent.
> Capitalized HDI everywhere it is used in text

- CHANGELOG.md
- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
if model is not passed explicitly, it is retrieved from the context and stored in self.model, however, currently we check coords/dims in model instead.
> fix io_pymc3 bug when model not passed explicitly

- CHANGELOG.md
- arviz/plots/pairplot.py
Fix the issue: the grid is overwriting points in pair plot. For example, in [the gallery example](https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_pair.html), blue points are separated into two pieces at grid lines.
> Change the default scatter_kwargs in pairplot

- CHANGELOG.md
- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
Also related (and blocker) of https://github.com/pymc-devs/pymc3/pull/3963
* will be in radon notebook
> allow from_pymc3 args to override model values

- CHANGELOG.md
- arviz/numeric_utils.py
Test failed in #1255 due to numpy latest version, 1.19, this should fix the issue.
> updates for numpy 1.19 compatibility

- CHANGELOG.md
- arviz/data/inference_data.py
> fix and extend idata.map docs

- arviz/plots/styles/arviz-darkgrid.mplstyle
- arviz/plots/styles/arviz-grayscale.mplstyle
- arviz/plots/styles/arviz-white.mplstyle
- arviz/plots/styles/arviz-whitegrid.mplstyle
This adds `constrained_layout=True` to all arviz styles. This was experimental as of matplotlib 2.2, we use >3.0. I've been using this for my plots for a few years with no problem.  I've included an example below. Notice the text boxes do not overlap with the subplots. 
Running 
```python
import matplotlib.pyplot as plt
az.style.use("arviz-darkgrid")
centered = az.load_arviz_data("centered_eight")
az.plot_trace(centered, var_names=["theta", "mu", "tau"], divergences=True);
```
Here is before the change:
Here is after the change:
> Use constrained layout in all styles

- CHANGELOG.md
- arviz/plots/backends/matplotlib/posteriorplot.py
> plot_posterior: fix overlap of hdi and rope

- CHANGELOG.md
- arviz/data/datasets.py
This PR adds a new inference data example. It contains circular variables, which will be useful for testing the new features developed in my GSoC 2020 project.
> Add Inference data example with circular variables

- examples/bokeh/bokeh_plot_bpv.py
Found out docs were broken because in the bokeh examples you have to return ax
Exploratory PR is here
https://github.com/arviz-devs/arviz/pull/1271
> Add missing ax that is breaking docs

- GOVERNANCE.md
Addressing NumFOCUS' first ask. Determine what is a core contributor and, how to become one, and what separates them from rest of community
Please feel free to edit this directly. These changes should be accepted by majority of council members. In other words my approval is not what matters here. The distribution of Council approvals does!
> [Discussion] Address Core Contributor portion of NumFOCUS feedback

- README.md
I think the xarray-backed trace data definition is actually a key part of the project and probably deserves to live in the one-liner project description.
> Add data storage to project description

- CHANGELOG.md
- arviz/plots/backends/bokeh/distplot.py
- arviz/plots/backends/bokeh/energyplot.py
- arviz/plots/backends/matplotlib/distplot.py
- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/plots/distplot.py
- arviz/plots/kdeplot.py
- arviz/plots/plot_utils.py
- arviz/tests/base_tests/test_plot_utils.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This PR adds circular histogram and circular KDE plot.
Histogram example (matplotlib):
Histogram example (bokeh):
Although with this code you can get a circular KDE, there are a couple of things to improve in the KDE that will result in better behavior in a circular setting. We are planning to follow on Tomas Capretto's work on KDE. You can read the details in his [report](https://tcapretto.netlify.app/files/report/).
> Add circular histogram and KDE plot

- arviz/plots/backends/matplotlib/jointplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/backends/matplotlib/rankplot.py
There are certain errors we need to fix
~~- [ ] Fix duplicate default parameter problem **(compatible with mpl<3.3.0)**~~
~~- [ ] fix changed return types (need to be careful to be compatible with previous versions of mpl)~~
I think the first two are fixed, but we need to update and fix the last point by thinking about how we define the default parameters. For example test are failing due to both `c` and `color` are defined. This used to be ignored, but in 3.1 it started to give a warning, and now it raises an exception.
Is there any mpl function we can use or do we want to manually create one. (There are not too many defaults we currently use). We also should use the main kw for each function. For example in color case, most mpl functions use color, but some use colors (e.g. vlines).
- …
> Partial mpl 3.3 fixes

- CHANGELOG.md
- arviz/plots/backends/matplotlib/distplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Plot-distribution bins argument error fixed. The plot_dist is given a numpy.ndarray and the bin size, which plots a histogram. The error was caused by the bins variable which was not a list to index, but by collecting the return value for bins after plotting this error is solved.
[Issue number #1306](https://github.com/arviz-devs/arviz/issues/1306)
Thank you so much for allowing me to work on this issue. I am new to open source, please let me know if the updates are correct and if I need to make any other changes.
> Dist plot error

- CHANGELOG.md
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats_numba.py
In this PR I changed the `az.summary` function to display statistics for circular variables more neatly. It is related to issue #339. 
`torsionals = az.load_arviz_data('glycan_torsion_angles')`
`az.summary(torsionals, circ_var_names=['tors'])` 
outputs:
> Adapt summary function to circular variables 

- .azure-pipelines/azure-pipelines-external.yml
- arviz/tests/base_tests/test_rcparams.py
- requirements-dev.txt
pytest said they fixed the pylint error but we're still seeing it. Kicking off CI to run see if unpinning works
https://docs.pytest.org/en/stable/changelog.html
> Fix ci pylint fail on pytest not callable error on markers

- arviz/plots/styles/arviz-grayscale.mplstyle
This is a small modification of the C0-C3  colors in arviz-grayscale. The C3 color was a little bit difficult to see specially if printed.
> new gray scale

- arviz/__init__.py
Gets rid of potentially confusing/annoying things like `az.os`. Not sure if there is a more pythonic way to do it.
> reduce namespace pollution

- .azure-pipelines/azure-pipelines-docs.yml
- arviz/stats/density_utils.py
Fixes #1340
PyMC3 installs ArviZ from PyPI, which caused docs to fail if there was a mismatch between PyPI ArviZ and GitHub ArviZ.
Tested with previous test PR.
> [bugfix] Install github ArviZ for documentation

- arviz/stats/stats.py
This PR fixes a bug in a warning message that causes ArviZ to instead throw a `TypeError`.
> Fix bug in warning that raises TypeError

- CHANGELOG.md
- arviz/plots/distplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Automatically convert list/tuple to numpy array in distplot.
The distplot requires a numpy array as input. It throws an exception if a list or tuple is given as input. In the current changes made any list/tuple passed as input is automatically converted to numpy array.
Issue number #1277
> Auto conversion of list to numpy array in distplot

- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- requirements.txt
I forgot to do this in previous PR.
> remove pin from mpl 3.3

- CHANGELOG.md
- arviz/data/io_cmdstan.py
- arviz/tests/external_tests/test_data_cmdstan.py
Some of the strip use was wrong, this PR replace these with regex.
> fix strip use

- CHANGELOG.md
- arviz/plots/__init__.py
- arviz/plots/backends/bokeh/separationplot.py
- arviz/plots/backends/matplotlib/separationplot.py
- arviz/plots/separationplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- doc/api.rst
- examples/bokeh/bokeh_plot_separation.py
- examples/matplotlib/mpl_plot_separation.py
The [separation plot](https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1540-5907.2011.00525.x) is a really interesting and simple way for assessing a model's fit when the outcome is binary. After fitting, model predictions are sorted and represented as vertical lines. When adding a color scheme that identifies the positive and negative class, for a good fit, we should see most of the instances of the positive class on the right hand side of the plot. That is, where the highest valued predictions are located.
``` python
idata = az.load_arviz_data('classification10d')
ax = az.plot_separation(
idata=idata, 
y='outcome',
y_hat_line=True,
expected_events=True,
figsize=(10, 1),
)
```
~It would be great if you could suggest how to choose default colors for this plot. Finally, I would like to …
> Separation plot

- examples/matplotlib/mpl_plot_hdi.py
In the [example](https://arviz-devs.github.io/arviz/examples/matplotlib/mpl_plot_hdi.html), there seems to be a desire to show the line from which `y_data_rep` is sampled, but it is not visible because the call to `az.plot_hdi` is after `plt.plot`, and its shaded region covers it. Switching the lines makes the yellow line visible.
> Make yellow line visible in matplotlib plot_hdi example

- arviz/stats/density_utils.py
Currently, the KDE returns a pdf with an area under the curve smaller than 1 if a narrower custom domain is specified.
This PR fixes that. 
**Old**
**New**
> Disable KDE domain narrower than data limits

- CHANGELOG.md
- arviz/utils.py
- requirements.txt
> fix css style

- CHANGELOG.md
- arviz/plots/backends/bokeh/forestplot.py
- arviz/plots/backends/matplotlib/forestplot.py
- arviz/plots/forestplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
> fix multi rope for forest plot

- CHANGELOG.md
- arviz/data/base.py
- arviz/data/inference_data.py
- arviz/data/io_dict.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/helpers.py
`idata.extend` does add the groups but does not edit the `_groups` attributes which makes `idata.posterior` to work but `posterior` is not shown when printing nor in the html repr.
> edit groups in idata.extend

- arviz/data/io_numpyro.py
- arviz/data/io_pyro.py
- arviz/stats/stats.py
A few minor fixes for type hint issues reported by mypy:
```
arviz/stats/stats.py:1133: error: Name 'Dict' is not defined
arviz/stats/stats.py:1133: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Dict")
arviz/data/io_pyro.py:21: error: Name 'Optional' is not defined
arviz/data/io_pyro.py:21: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")
arviz/data/io_numpyro.py:19: error: Name 'Optional' is not defined
arviz/data/io_numpyro.py:19: note: Did you forget to import it from "typing"? (Suggestion: "from typing import Optional")
```
I also replaced use of `builtins.callable` with `typing.Callable` in type hints since `mypy` doesn't consider the lowercase version a valid type:
```
arviz/data/io_pyro.py:22: error: …
```
> Add missing type hint imports, as suggested by mypy.

- arviz/tests/base_tests/test_diagnostics_numba.py
- arviz/tests/base_tests/test_plot_utils.py
- arviz/tests/base_tests/test_stats_numba.py
- arviz/tests/base_tests/test_utils_numba.py
Resolves the following type errors that mypy points out:
```
arviz/tests/base_tests/test_utils_numba.py:15: error: Argument 1 to "__call__" of "_SkipifMarkDecorator" has incompatible type "int"; expected "Union[str, bool]"  [arg-type]
arviz/tests/base_tests/test_plot_utils.py:203: error: Argument 1 to "__call__" of "_SkipifMarkDecorator" has incompatible type "int"; expected "Union[str, bool]"  [arg-type]
arviz/tests/base_tests/test_plot_utils.py:281: error: Argument 1 to "__call__" of "_SkipifMarkDecorator" has incompatible type "int"; expected "Union[str, bool]"  [arg-type]
arviz/tests/base_tests/test_diagnostics_numba.py:17: error: Argument 1 to "__call__" of "_SkipifMarkDecorator" has incompatible type "int"; expected "Union[str, bool]"  [arg-type] …
```
> Pass bool instead of int values to pytest.mark.skipif

- CHANGELOG.md
- arviz/data/base.py
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
Add `.to_dataframe` function to InferenceData. The result is a dataframe in a "wide" format.
This PR also adds `__getitem__` magic for the InferenceData.
> Add to_dataframe to InferenceData

- arviz/plots/backends/bokeh/densityplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
This PR resolves #1401 by removing the `squeeze=True` call to `create_axes_grid` within `plot_density` with the bokeh backend, which is contradicted by the later use of `.flatten`. It also adds missing `backend="bokeh"` kwarg to another bokeh test.
> Allow passing a single variable to plot_density with bokeh backend

- CHANGELOG.md
- arviz/static/css/style.css
- arviz/utils.py
The HTML repr for `InferenceData` reuses some of the classes of xarray's HTML repr for `xarray.Dataset`.
The `xr-sections` class determines the grid layout of the list of sections in the `Dataset` repr. However, the same class is applied to the list of groups in the `InferenceData` repr. The result is that the same grid layout is applied to both (note that the left-most and two right-most columns are the same width):
This isn't a problem in the arviz docs or Jupyter notebooks with the default theme, but a different Jupyter theme is used or the `InferenceData` HTML repr is used in a different page, then if the font size is too large, the group names can exceed the fixed width of the grid. This happens in the [ArviZ.jl docs](https://arviz-devs.github.io/ArviZ.jl/v0.4.5/quickstart/#Plotting-w …
> Prevent wrapping group names in InferenceData HTML repr

- CHANGELOG.md
- arviz/stats/stats.py
loo and waic had it removed already IIRC
> remove default scale warning in compare

- CHANGELOG.md
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
Add automatic group handling. Defaults to posterior, but works now with InferenceData without posterior (e.g. prior).
> add group info to summary

- CHANGELOG.md
- arviz/plots/distplot.py
I fixed a typo in `plots/distplot.py`, changing the description of a ValueError.
Fixes: #1413
> Fix typo in distplot.py

- CHANGELOG.md
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
There is a clause of `if y_str` to use `var_name` when getting the log_likelihood that corresponds to the observations but then uses `y` as `var_name` instead of `y_str`.
> fix typo in loo_pit

- CHANGELOG.md
- arviz/data/io_pystan.py
I have had some problems when saving to netcdf with the new extended attrs, seems related to https://github.com/pydata/xarray/issues/2868. This uses json.dumps to convert the nested objects to strings that can be stored in netcdf and if necessary recovered by parsing the json again.
> json dump nested dicts and lists attrs

- CHANGELOG.md
- arviz/plots/backends/bokeh/ppcplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/ppcplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
I also made a few other changes in bokeh, specially to use the matplotlib color and to make the scatter plot a little fit faster.
> plot_ppc add observed argument to (un)plot observed data

- CHANGELOG.md
- arviz/plots/backends/bokeh/violinplot.py
- arviz/plots/backends/matplotlib/violinplot.py
This was passing silently because with the default arviz styles plots are "despined" (or because nobody use `plot_violin`, haha)
Old matplotlib
New matplotlib
Old bokeh
New bokeh
Still don't know how to remove the space between subplots in bokeh, @ahartikainen?
> violinplot remove ticks and spines

- CONTRIBUTING.md
- README.md
- doc/source/conf.py
- requirements-docs.txt
Currently the 404 page only works for pages on the base directory, i.e. https://arviz-devs.github.io/arviz/badpage.html looks great and links work, but https://arviz-devs.github.io/arviz/api/badpage.html does not. Not sure if this is the ideal way to do this, but it seems to work, at least partially. 
It also fixes a couple links that were broken due to the reorganization.
> Documentation fixes

- CHANGELOG.md
- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/plots/backends/matplotlib/traceplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
I noticed that the KDE plot in `plot_trace` was not using the circular KDE function (#1284). I also fixed the labels so that both columns share the same units.
Degrees:
Radians:
> Fix labels and use circular KDE in plot_trace

- CHANGELOG.md
- arviz/data/base.py
- arviz/data/io_cmdstan.py
- arviz/data/io_cmdstanpy.py
- arviz/data/io_dict.py
- arviz/data/io_numpyro.py
- arviz/data/io_pymc3.py
- arviz/data/io_pyro.py
- arviz/data/io_pystan.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/external_tests/test_data_pymc.py
ArviZ schema recommends to use the same variable names in log likelihood group as the one in observed_data and posterior_predictive groups. This helps identifying to what terms does each pointwise log lik value correspond, and eases calculations like LOO-PIT. 
However, log likelihood and posterior predictive don't always have the same dimensions and shape. In multidimensional observations the _event_ dimensions (shape of a single _observation_) are reduced. The shape of posterior predictive is `(chain, draw, *batch_shape, *event_shape)` whereas for log likelihood it is `(chain, draw, *batch_shape)`, in scalar observations they are both the same, but for multidimensional observations such as multivariate normals or multinomials the two shapes are different and the converters error out. …
> skip "event" dims in log likelihood group whenever necessary

- CHANGELOG.md
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/pairplot.py
When plotting mixed variables plot_pair produced a wrong result, basically the type of the variable was taken from the first variable and applied to the rest.
> fix pair_plot for  mixed discrete and continuous variables

- CHANGELOG.md
- arviz/plots/backends/bokeh/compareplot.py
- arviz/plots/backends/matplotlib/compareplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Fix #1434 
When computing the "in-sample deviance" we were adding the wrong factor, except for the "deviance" scale.
> fix in-sample deviance

- CHANGELOG.md
- arviz/plots/backends/bokeh/posteriorplot.py
- arviz/plots/backends/matplotlib/posteriorplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/stats/stats.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Plot posterior fails if `nan` are present, this adds a skipna argument, defaults to False.
> add skipna argument to plot_posterior

- CHANGELOG.md
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
When using "bb-pseudo-bma" overflows could happen when a weight much more larger than the rest.
I found mistakes in stacking, the retains where not ok and the minimization always return the initial guess 1/(number of model)   oddly I know for sure it used to run OK. Anyway, this fix the problem and makes stacking the default method.
This also add a warning message that we changed the default method. I guess we should keep it at least during one release cycle.
> fix compare and make stacking default method

- CHANGELOG.md
- arviz/plots/backends/bokeh/rankplot.py
- arviz/plots/backends/matplotlib/rankplot.py
- arviz/plots/plot_utils.py
- arviz/tests/base_tests/test_plot_utils.py
Use a similar trick to the one used in `plot_bpv` for discrete variables.
Good sample
OLD
NEW
Bad sample (excess of 2s in one chain)
OLD
NEW
Bad sample (two different distributions)
OLD
NEW
As you can see with the old version discrete samples always look bad (and more or less the same). With the new version not only they look good when they should, they actually reflect the nature of problem with the sampling went wrong.
> Add support for discrete variables in rank plots

- CHANGELOG.md
- arviz/stats/stats.py
> fix hdi failure with boolean array

- CHANGELOG.md
- arviz/plots/backends/matplotlib/distplot.py
- arviz/plots/backends/matplotlib/hdiplot.py
- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This recover the old behavior, allowing to do this, without the need to explicitly need to pass the axes
a= np.random.normal(0, 1, 100)
b= np.random.normal(0, 1, 100)
az.plot_kde(a)
az.plot_kde(b)
> automatically get the current axes instance

- doc/source/getting_started/Introduction.ipynb
- doc/source/usage.rst
Fix broken link and replace with relative link (adding anchor to quickstart notebook and updating usage page to link to that anchor)
It looks like some extra metadata got changed when added a line to the notebook. Let me know if I should get rid of those changes.
Closes #1457
> Use relative link with sphinx

- CHANGELOG.md
- arviz/plots/autocorrplot.py
- arviz/plots/bpvplot.py
- arviz/plots/densityplot.py
- arviz/plots/essplot.py
- arviz/plots/mcseplot.py
- arviz/plots/plot_utils.py
- arviz/plots/posteriorplot.py
- arviz/plots/ppcplot.py
- arviz/plots/rankplot.py
- arviz/plots/violinplot.py
> add grid argument to manually specify the number of rows and colums

- arviz/stats/density_utils.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This PR tries to improve testing and code coverage of `arviz.stats.density_utils.py`.
* Add an argument to the `test_plots_kde()` function to cover the case of adaptive KDE.
* Remove the deprecated `_fast_kde()` function
> Increase code coverage (stats.density_utils.py)

- .azure-pipelines/azure-pipelines-base.yml
- .azure-pipelines/azure-pipelines-external.yml
- requirements-external.txt
Ci is failing for two reasons
* Tfp 0.12.0 deprecated edward apparently but our converter looks for it
* PyMC3 submoduled its notebooks and thats causing some clone failure
> Pin tensorflow version

- CHANGELOG.md
- arviz/plots/backends/bokeh/traceplot.py
- arviz/plots/backends/matplotlib/traceplot.py
When kind = rank_vlines or rank_bars, and if divergences are present they will be plotted only under the KDE/histogram
Update. A few examples of how it look without this fix
> plot_trace, do not plot divergences with rankplots

- arviz/plots/backends/bokeh/loopitplot.py
- arviz/plots/backends/matplotlib/loopitplot.py
Add a white line to represent the expected uniform distribution
> add reference line to loopit

- CONTRIBUTING.md
Add a policy so we can unassign people from issue tickets without having to feel bad about it as the expectations are clear and written unambiguously for all
> Add verbiage for unassigning issue tickets

- CHANGELOG.md
- arviz/plots/backends/bokeh/khatplot.py
- arviz/plots/backends/matplotlib/khatplot.py
- arviz/plots/khatplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Replace `annotate` argument with `threshold`, this makes `plot_khat` more consistent with `plot_elpd` and also allows user to define arbitrary values to use as thresholds. This also  add a few tweaks to make it easier to use plot_khat with subplots and share the Y-axis.
> Khat deprecate annotate in favor of threshold

- arviz/data/base.py
- arviz/data/inference_data.py
- arviz/data/io_json.py
- arviz/data/io_pystan.py
- arviz/tests/helpers.py
This PR is only about improving type hint coverage and quality. It contains no new features and makes no substantive changes to existing functionality, so it should be fully covered by existing tests. This is similar in spirit to #1397 and #1398.
In particular, this PR:
- Applies a `mypy`-suggested type hint to a test helper that requires it in order to type-check.
- Applies `# type: ignore` suppressions to a few instances of a known and still-unresolved `mypy` issue https://github.com/python/mypy/issues/1153
The following `mypy`-reported errors are resolved as a result:
```
arviz/data/io_pystan.py:20: error: Name 'json' already defined (by an import)  [no-redef]
arviz/data/io_json.py:9: error: Name 'json' already defined (by an import)  [no-redef]
arviz/data/base.py:15: error: Name …
```
> Resolve a few straightforward mypy type errors.

- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
- Added a missing error check on the `summary()` function's `kind` parameter. Since the check was missing, that meant that illegal `kind` values could be passed, and cause unexpected, self-inconsistent behavior in the function.
- Improved type hints to use explicit `Literal` types instead of `str`, making errors like the ones mentioned in the prior bullet point less likely to happen as `mypy` would catch them statically.
- Resolved a type error caused by unintentional variable-sharing across unrelated portions of the same function.
As with my other PRs, there are no substantive changes to existing functionality and there is no new functionality, so existing tests should cover everything already.
> Minor improvements to type checking and error checks in stats.py.

- arviz/rcparams.py
- arviz/tests/base_tests/test_rcparams.py
Working to resolve the following issue raised by `mypy`:
```
arviz/rcparams.py:286: error: Cannot determine consistent method resolution order (MRO) for "RcParams"  [misc]
```
It seems that `RcParams` inherits from both `dict` and `MutableMapping`, which is confusing `mypy` because `dict` is also a `MutableMapping`. Additionally, it seems that this confusing MRO situation has led to the need to redefine several of the `MutableMapping` methods explicitly, to avoid MRO-related dispatch issues.
I'm not sure why `RcParams` needs `MutableMapping` _in addition to_ having `dict` as a superclass, so I'm leaving this PR as a draft for now. None of the documentation for the class seems to explain this quirk, so I'm hoping that either test cases surface some leads, or one of the maintainers recalls …
> Resolve RcParams MRO confusion and delete unnecessary methods.

- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
Fixes `from_pymc3` compatibility with theano-pymc>=1.1 and allows going back to the original behaviour of `from_pymc3` with `DensityDist` if desired.
Tagging also @michaelosthege for review
PR format?
> Fixes before releasing

- CHANGELOG.md
- arviz/data/base.py
- arviz/data/inference_data.py
Modified the `extend_xr_method` to include docstring and examples. In continuation with the #1223 and #1254 and #1300. Related to #1066 .
> Documentation changes

- CHANGELOG.md
- arviz/data/io_pystan.py
- doc/source/schema/schema.md
> Explain sample_stats naming convention

- arviz/plots/traceplot.py
Fixing a couple more `mypy` errors, closing in toward #1496:
```
arviz/plots/traceplot.py:23: error: Incompatible default for argument "circ_var_units" (default has type "str", argument has type "bool")  [assignment]
arviz/plots/traceplot.py:163: error: Incompatible types in assignment (expression has type "bool", variable has type "Optional[str]")  [assignment]
```
> Fix type mismatches in traceplot.py.

- arviz/plots/backends/bokeh/bpvplot.py
- arviz/plots/backends/matplotlib/bpvplot.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
We recently introducing a smoothing step for discrete data in `plot_pbv`, this does the same but for loo_pit. See example below. I am omitting plot from `plot_pbv`, because they were part of a previous PR.
binomial well-calibrated old
binomial well-calibrated new
binomial bad-calibrated old
binomial bad-calibrated new
Poisson well-calibrated old
Poisson well-calibrated new
poisson bad-calibrated old
poisson bad-calibrated new
> loo_pit for discrete data

- arviz/data/inference_data.py
Suppress the following false positive `mypy` type errors, without affecting any of the underlying functionality. Working toward #1496.
```
arviz/data/inference_data.py:1301: error: "Type[Dataset]" has no attribute "mean"  [attr-defined]
arviz/data/inference_data.py:1302: error: "Type[Dataset]" has no attribute "median"  [attr-defined]
arviz/data/inference_data.py:1303: error: "Type[Dataset]" has no attribute "min"  [attr-defined]
arviz/data/inference_data.py:1304: error: "Type[Dataset]" has no attribute "max"  [attr-defined]
arviz/data/inference_data.py:1305: error: "Type[Dataset]" has no attribute "cumsum"  [attr-defined]
arviz/data/inference_data.py:1306: error: "Type[Dataset]" has no attribute "sum"  [attr-defined]
```
These errors arise from the fact that the `Dataset` type has some …
> Suppress false positive missing method mypy errors.

- arviz/plots/traceplot.py
Avoids the following `mypy` error:
```
arviz/plots/traceplot.py:183: error: "InferenceData" has no attribute "dims"  [attr-defined]
```
Part of #1496.
The error was happening because the `data` variable was initially of type `InferenceData` but was later overwritten with a value of different type on the line:
```python
data = get_coords(convert_to_dataset(data, group="posterior"), coords)
```
In general, assigning a value of a completely different type to an existing variable will cause both `mypy` and `pylint` to complain about the assignment itself. In this case, the `get_coords()` function itself was not type-hinted, i.e. its return type was considered to be `Any`. This led `mypy` to incorrectly deduce that the return type must have preserved the existing type of `data`, because not …
> Avoid overwriting a variable with value of different type.

- arviz/plots/pairplot.py
- arviz/plots/parallelplot.py
This should solve "Make exception consistent between plot_pair and plot_parallel" issue #1507. Now, both plots should raise ValueError with the same error prompt if the number of variables is less than 2. Beginner, so please let me know what I missed.
> Standardized error messaging in pairplot and parallelplot

- CHANGELOG.md
- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/plots/backends/matplotlib/traceplot.py
When plotting circular variables with `plot_trace` the circular subplot title overlaps with the x tick labels. I also fixed repeating warnings derived from changing of tick locations.
On master:
This PR:
> Fix circular traceplot warnings and title

- .azure-pipelines/azure-pipelines-docs.yml
- CHANGELOG.md
- doc/_templates/404.html
- doc/source/conf.py
- doc/source/index.rst
- doc/sphinxext/gallery_generator.py
- requirements-docs.txt
As proposed in #1484, this PR modifies the example gallery to have a single page per type of plot.
Each page has then one tab per backend to ease comparison between backends.
You can see the preview at https://oriolabril.github.io/arviz/examples/index.html, let me know what you think about it.
Also, side note, now only one thumb per example is required, therefore, we can use matplotlib to generate thumbs and forget about exporting bokeh plots as png files and the extra dependencies it requires which I believe will simplify building docs locally.
PR format?
> [docs] Tabs for example gallery!

- CHANGELOG.md
- arviz/plots/backends/bokeh/forestplot.py
- arviz/plots/backends/matplotlib/forestplot.py
Forest plots of multivariate variables currently prepend the variable name to each element label, which adds a lot of clutter to the plot. This removes the variable names from all but the first element.
Can add this feature to other plots as needed, either here or in a separate PR.
Not sure what sort of test would be relevant here, if any.
Closes #1524
> Removed repetitive variable names from forest plots of multivariate variables

- CHANGELOG.md
- arviz/plots/pairplot.py
Fixes #1531. This PR makes only a couple minor changes to plot_pair. The first one is to
fix the generation of the plot labels and the second is to avoid calling filter twice. As
plot_pair generates a half grid of plots, its interpretation of `max_subplots` is not done on
the number of variables like with most other plots but on the actual number of subplots, may not be
ideal but the filtering is currently implemented at the backend level.
PR format?
> fix plot_pair labels

- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_data_zarr.py
- doc/source/api/inference_data.rst
- doc/source/conf.py
- requirements-optional.txt
This pull request adds two methods to the 'InferenceData' class:
- `.from_zarr()` to construct an 'InferenceData' object via xarrays `.open_zarr` method. 
- `.to_zarr()` to convert a zarr 'store' or a path to an 'InferenceData' object
These two methods are quite useful to save and restore 'InferenceData' objects to disk with zarr. Zarr is still experimental in xarray, but I think it could be a good addition.
For the implementation, I tried to use a similar approach as in the `from_dataframe` and `to_dataframe` methods. I also tried to add the changes to the changelog, please take a look. I would appreciate if someone could assist me with writing tests for these methods.
Best,
Sebastian
[Zarr](https://zarr.readthedocs.io/en/stable/)
> Added methods to convert InferenceData to and from Zarr [docs]

- CHANGELOG.md
- arviz/plots/backends/bokeh/autocorrplot.py
- arviz/plots/backends/matplotlib/autocorrplot.py
Add confidence interval to auto correlation plot. It also remove the horizontal line at 0 (which color was "steeelblue", for historical reasons.)
old version 
new version
> autocorrelation plot add ci band and remove hline

- README.md
- doc/source/index.rst
Just noticed that they added a few extra fields, and also got my name more right (this is copy/pasted from https://joss.theoj.org/papers/10.21105/joss.01143, but kept the title the same as before (`arviz_2019` instead of `Kumar2019`).
> Update JOSS bibtex snippet

- doc/source/conf.py
- requirements-docs.txt
I removed the extension because it does not work with the navbar, you click there and
the url somehow grows instead of going to the right page. I have then realized however
that even though it does not fix the paths and references in the navbar, it does fix the
references to the css style and makes the page look good.
Now notfound pages generally look like: 
instead of looking like:
> Add sphinx.notfound extension (again)

- arviz/stats/diagnostics.py
- arviz/stats/stats.py
- arviz/tests/base_tests/test_diagnostics.py
- arviz/tests/base_tests/test_stats.py
> remove ess_mean and ess_sd from summary

- CHANGELOG.md
- arviz/data/io_cmdstan.py
Matched sample stats according to InferenceData schema specification in from_cmdstan converter. Addreses issue #1514
> Update from_cmdstan converter to follow schema convention

- CHANGELOG.md
- arviz/plots/plot_utils.py
> fix point_estimate mode

- CHANGELOG.md
- arviz/data/io_pymc3.py
Added remaining parameters to the rename_dict. Addresses issue #1514
> Update rename_dict on io_pymc3.py converter to follow schema convention

- CHANGELOG.md
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
closes #1540
Remove varname from legend in plotppc. Motivation is:
- it's already the label of the x-axis
- if the case of multiple plots, then a single legend is still valid
xref https://github.com/arviz-devs/arviz/issues/1540#issuecomment-774667864
> Of course the current behavior is problematic, because we have one legend that is supposed to work for both plots but is referring only to the first. So I suggest to have as default one legend and remove from the legend the name of the variable.
Here's what the output from `examples/matplotlib/mpl_plot_ppc.py` would now look like - note how `obs` only appears as the label of the x-axis, rather than being repeated in the legend
> Remove varname from legend in plotppc

- CHANGELOG.md
- arviz/data/io_cmdstanpy.py
Matched sample stats according to InferenceData schema specification in from_cmdstanpy converter. Addreses issue #1514
> Update from_cmdstanpy converter to follow schema convention

- doc/source/conf.py
I tried to fix the layout of the not found page a few PRs ago and it did not work,
I think this will do the trick. Let's see how it goes.
PR format?
> fix notfound

- CHANGELOG.md
- arviz/plots/backends/bokeh/posteriorplot.py
- arviz/plots/backends/matplotlib/posteriorplot.py
Added significant digits formatter for rope values. To fix [#1561](https://github.com/arviz-devs/arviz/issues/1561)
> Added significant digits formatter for rope values

- CHANGELOG.md
- arviz/data/io_cmdstan.py
- arviz/tests/external_tests/test_data_cmdstan.py
- doc/source/conf.py
- requirements-dev.txt
Read CmdStan csv files manually. This enables us to parse large models (100k parameters) much faster than pandas.
This PR also adds `dtypes` argument, which user can use to transform dtypes for specific parameters
dtypes = {"theta": int}
> Update CmdStan read and logic

- arviz/data/base.py
- arviz/data/io_pymc3.py
This PR type-hints the `@requires` decorator, which seems to be used in over 100 places in the repository at the moment. Since decorators are a bit tricky to type-hint correctly, and still have some unsolved edge cases with regard to type-hinting (https://github.com/python/mypy/issues/3157 comes to mind), I wanted to open this PR as an example of the available options and to provide a bit more context for #1498 where we were discussing whether to use `@requires` or not. Also tangentially related to #1496.
The gist of the still-open `mypy` [issue](https://github.com/python/mypy/issues/3157) is that there's no great way to type-hint decorators that work on functions with arbitrary type signatures but change the input function's type signature in some way. The `@requires` decorator falls in …
> Add a possible type hint to the @requires decorator.

- CHANGELOG.md
- arviz/stats/stats_refitting.py
I noticed that changing the `k_thresh` argument to the function `reloo` from the default value 0.7 had no effect. I think this is because the threshold is accidentally hard-coded as 0.7 inside the function.
This change fixes the apparent typo, replacing 0.7 with `k_thresh`.
This function is so far untested and I didn't think it made sense to write a whole test before fixing this bug.
> Fix pareto k threshold typo in reloo function

- CHANGELOG.md
- arviz/wrappers/base.py
- arviz/wrappers/wrap_pystan.py
- doc/source/user_guide/sampling_wrappers.md
> Add links to samplingwrapper docs

- arviz/plots/traceplot.py
- doc/source/conf.py
Fixed mypy errors mentioned in https://github.com/arviz-devs/arviz/pull/1528#issuecomment-783115088 by adding type hints to `var_names` and `latex_elements`. Addresses #1581
> [WIP] fix mypy errors

- CHANGELOG.md
- arviz/data/io_pymc3.py
This is part of a fix for an issue in PyMC3: https://github.com/pymc-devs/pymc3/issues/4469 . A trace could have chains that are not necessarily indexed 0, 1, .... However, `_DefaultTrace.insert` *does* take an index 0, 1, ... So, the index argument into `insert` should be zero-based. This PR decouples the `chain` index (which refers to a logical chain index, possibly starting at 1 or whatever) from the index passed to `_DefaultTrace.insert`.
> use chain serial rather than logical index with _DefaultTrace.insert

- .pylintrc
- CHANGELOG.md
- arviz/data/base.py
- arviz/data/io_pymc3.py
- arviz/plots/backends/bokeh/energyplot.py
- arviz/plots/backends/matplotlib/energyplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_rcparams.py
Enabled 2 pylint checks namely: 
- `use-a-generator`
- `consider-using-generator`
Fix #1578
> Enabled pylint generator checks

- arviz/data/io_cmdstanpy.py
Fixes https://github.com/arviz-devs/arviz/issues/1594
Small fixes
> Fix io_cmdstanpy bugs

- CHANGELOG.md
- arviz/data/io_pystan.py
Related to the issue #1514 , updated the file according to the schema convention
> Update io pystan

- CHANGELOG.md
- arviz/plots/backends/matplotlib/elpdplot.py
`plot_elpd` can now take the `ax` argument. Naive example:
```
d1 = az.load_arviz_data("centered_eight")
d2 = az.load_arviz_data("non_centered_eight")
fig, ax = plt.subplots(1, 2, figsize=(10, 4))
az.plot_elpd({"Centered eight": d1, "Non centered eight": d2}, xlabels=True, ax=ax[0])
az.plot_elpd({"Centered eight": d1, "Non centered eight": d2}, xlabels=True, ax=ax[1])
```
> Fix ax argumentin plot_elpd

- CHANGELOG.md
- arviz/plots/backends/matplotlib/khatplot.py
- arviz/plots/khatplot.py
`plot_khat` can take a `c` argument to use with a color map
> Using color maps in plot_khat

- CHANGELOG.md
- arviz/data/io_cmdstan.py
- arviz/data/io_pystan.py
- arviz/tests/external_tests/test_data_cmdstan.py
- arviz/tests/external_tests/test_data_pystan.py
- arviz/utils.py
> Add default log_lik handling for pystan and cmdstan

- CHANGELOG.md
- arviz/plots/backends/bokeh/ppcplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
To fix #1563 
I have added an interactive legend to `ppc_plot` in bokeh.
Is the position of the legend is good enough?
> Added Interactive legend to ppc_plot bokeh

- CHANGELOG.md
- arviz/data/io_numpyro.py
- arviz/tests/external_tests/test_data_numpyro.py
This PR fixes the crash observed when running the following code:
```python
import numpy as np
import numpyro
import numpyro.distributions as dist
from jax import random
from numpyro.infer import MCMC, NUTS
data = np.random.normal(10, 3, size=100)
def model(data):
numpyro.sample(
'x',
dist.Normal(
numpyro.sample('loc', dist.Uniform(0, 20)),
numpyro.sample('scale', dist.Uniform(0, 20)),
),
obs=data,
)
kernel = NUTS(model)
mcmc = MCMC(NUTS(model), 100, 200, thinning=2)
mcmc.run(random.PRNGKey(0), data=data)
mcmc.print_summary()
az.from_numpyro(mcmc)  # crash
```
Fixes #1618 (line edited by @OriolAbril to use [github issue closing keywords](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-reference …
> Fix `az.from_numpyro` crash when running MCMC with `thinning > 1`

- doc/source/index.rst
Pretty sure we're not going to be supporting PyMC4 anytime soon. Are we still going to support edward or edward2?
**Edit**
Also add pypi badge like we are doing for README.md
> Remove PyMC4 from doc index and add badges

- .azure-pipelines/azure-pipelines-external.yml
- CHANGELOG.md
> upload updated mypy.ini if needed

- CHANGELOG.md
- arviz/data/io_pymc3.py
- arviz/tests/external_tests/test_data_pymc.py
Enabled type checking for `io_pymc3` input... Now it raises an error whenever input type is of `InferenceData`.
Fix #1617
> enabled type checking for io_pymc3 input

- CHANGELOG.md
- doc/source/api/plot_utils.md
- doc/source/user_guide/label_guide.rst
Adds the missing section about writing custom labellers to the label guide.
> add custom labellers section to label guide

- CHANGELOG.md
- arviz/plots/backends/matplotlib/elpdplot.py
Fix xlabels and ax argument in plot_elpd for numvars > 2.
> Fix xlabels and ax argument in plot_elpd

- CHANGELOG.md
- doc/source/user_guide/Numba.ipynb
Removed geweke diagnostic from numba user guide. Closes #1652
> Removed geweke diagnostic from numba user guide

- CHANGELOG.md
- arviz/data/io_pyro.py
Implements fix suggested in #1529 to allow traces on the GPU to be moved back to the CPU.
Closes #1529
> Move observations to cpu in PyroConverter

- arviz/stats/density_utils.py
Added ability to calculate float margins with get_bins. This addresses issue #1639 .
The code distinguishes between dtype of the values array. If int32, previously defined code is used. If not int32, numpy [histogram_bin_edges ](https://numpy.org/doc/stable/reference/generated/numpy.histogram_bin_edges.html) function is used with bins='auto' and default arguments. 
Open to feedback and revisions to suit codebase.
> Added floating margins for get_bins

- .pylintrc
- CHANGELOG.md
- arviz/data/base.py
- arviz/data/io_cmdstan.py
- arviz/data/io_cmdstanpy.py
- arviz/data/io_pystan.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_data_zarr.py
- arviz/tests/base_tests/test_diagnostics.py
- arviz/tests/base_tests/test_plot_utils.py
- arviz/tests/external_tests/test_data_cmdstanpy.py
- arviz/tests/external_tests/test_data_pystan.py
closes #1630
Infer dtypes from model code (all interfaces) or use user given dictionary (cmdstanpy, cmdstan).
> Infer dtypes for all Stan interfaces

- CHANGELOG.md
- arviz/plots/backends/bokeh/separationplot.py
- arviz/plots/backends/matplotlib/separationplot.py
When `y_hat_line` or `expected_events` arguments were used, the legend could not be turned off.
> Fix legend in separation plot

- CHANGELOG.md
- doc/source/user_guide/label_guide.rst
> [WIP] improvement suggestions for the label guide documentation (until sorting dimensions chapter)

- arviz/tests/base_tests/test_stats.py
Modified loo_pit tests to remove dependency on radon dataset. Using modified centered_eight instead.
Closes #1716
> Remove testing dependency on http download for radon dataset

- arviz/plots/hdiplot.py
- arviz/stats/stats.py
> Resolves #1188. The external reference for backend_kwargs in plot_hdi has been added. Additionally, the see also section has been extended in compare with an addition of references. The work is still in progress for the other functions.
> ## Checklist
> * [x]  plot_hdi: nearly finished, only external references for `backend_kwargs` are missing.
> * [x]  compare: extend see also section, maybe use references too? plot_separation is a good example on how to format references in docstrings
> Progressively updated doc references (WIP)

- arviz/tests/base_tests/test_plot_utils.py
Skip test as quick and temporal fix
PR format?
> skip coord name error test

- CHANGELOG.md
- arviz/plots/backends/bokeh/kdeplot.py
- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This pr solves the conflict that arises when `label` is passed as a kwarg. It conflicted with the argument `label`. 
Added `set_default` to the required args. 
Added relevant kwargs in the test module.
Also, now user can use plot_posterior to use plot multiple distributions and have a legend.
closes #1703
> fixed plot_kde to take labels with kwargs.

- CHANGELOG.md
- arviz/tests/base_tests/test_plot_utils.py
For now, tests both exception cases
> fix xarray related tests

- .azure-pipelines/azure-pipelines-external.yml
- arviz/data/inference_data.py
- arviz/data/io_pyro.py
- arviz/tests/helpers.py
- mypy.ini
- requirements-dev.txt
> Fix pylint and pickling issue

- CHANGELOG.md
- arviz/plots/backends/bokeh/loopitplot.py
- arviz/plots/backends/matplotlib/loopitplot.py
Fix credible interval percentage in `plot_loo_pit` legend
Before:
After:
> Fix credible interval  percentage in plot loo pit legend

- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
On main, this warning shows the line number from ArviZ code. On this branch, it'll show the line number from the user's code.
I wanted to add a test, but running
```
pytest arviz/tests/base_tests/test_stats.py -k test_hdp_2darray -W error
```
doesn't throw any errors, neither here nor on main - do the warnings get silenced somewhere during tests?
It shows the warning if I just execute the code:
```python
>>> import numpy as np
>>> import arviz
>>> arviz.hdi(np.random.randn(2, 2))
<stdin>:1: FutureWarning: hdi currently interprets 2d data as (draw, shape) but this will change in a future release to (chain, draw) for coherence with other functions
array([[-1.85791612,  1.28256026],
[ 1.23431573,  1.91356814]])
>>> 
```
> fix stacklevel of hdi warning

- arviz/stats/density_utils.py
Provides a more user-friendly warning when the data used to compute a KDE is constant (or has non finite values). Fixes https://github.com/arviz-devs/arviz/issues/1685. For those cases the plot will look empty.
> KDE friendly warnings for constant data

- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_utils.py
- arviz/utils.py
> validate filter_vars

- CHANGELOG.md
- arviz/plots/backends/bokeh/kdeplot.py
- arviz/plots/backends/bokeh/ppcplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/ppcplot.py
Now we can pass a list of 3 colors instead of a single string
> ppc_plot specify colors for each element

- doc/source/getting_started/Introduction.ipynb
Fixed the reference to netCDf in the [quick-start](https://arviz-devs.github.io/arviz/getting_started/Introduction.html#plotting-with-pystan-objects) section.
> Fixed the link of netCDF

- .azure-pipelines/azure-pipelines-external.yml
Fixing PyMC3 github source test to the PyMC3 branch in pymc3
This means PyMC (not 3) is not being tested right now so that'll have to get added later
> Fix CI PyMC3 github install to v3

- arviz/plots/kdeplot.py
- arviz/stats/density_utils.py
- doc/source/api/stats.rst
The [plot_kde](https://arviz-devs.github.io/arviz/api/generated/arviz.plot_kde.html) was connected to itself in "see also" section. It should be instead connected to `kde` page. 
Added the `kde` page and fixed its identation.
> Added kde page in stats

- doc/source/user_guide/pystan2_refitting_xr_lik.ipynb
**Description:** 
Updated [Refitting PyStan (2.x) models with ArviZ (and xarray)](https://arviz-devs.github.io/arviz/user_guide/pystan2_refitting_xr_lik.html#) part.
* Added links to the ArviZ functions and classes using [Cross-referencing with Sphinx](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html).
* Added links to the xarray functions and classes using [Intersphinx](https://docs.readthedocs.io/en/stable/guides/intersphinx.html).
* Added the rest of the external links using the simple syntax `[]()`.
> Updated Refitting PyStan (2.x) models with ArviZ (and xarray)

- CHANGELOG.md
- arviz/stats/density_utils.py
[Current formula for computing the standard deviation in `_kde_linear`](https://github.com/arviz-devs/arviz/blob/77a30bec94a3b88594edb6b272dad91039594f97/arviz/stats/density_utils.py#L569) is not numerically stable. Replace this  formula with `np.std`.
Solves https://github.com/arviz-devs/arviz/issues/1832
> Fix standard deviation code in density utils by replacing it with np.std.

- doc/source/schema/PyStan_schema_example.ipynb
Documentation update.
- Updated text in notebook as requested in "Update doc-Example of InferenceData schema in PyStan" https://github.com/arviz-devs/arviz/issues/1799 
Looked at PR that updated pymc3 example https://github.com/arviz-devs/arviz/pull/1790 as reference
> Updated text in PyStan schema example to match PyMC3 example

- arviz/plots/separationplot.py
Added references in the docstring of plot_separation.py file.
- Added link to arviz.InferenceData
- Formatted all parameter references as code
- Documented backend_kwargs
- Add see also section for plot_ppc
Fixes: #1887
> Add docs references to plot_separation docstring

- doc/source/contributing/contributing_prs.md
On the [Contributing page](https://arviz-devs.github.io/arviz/contributing/index.html), the links in the bullet points are not on the same level. Heading-1 should only be the title of the page, but `contributing_prs.md` consisted of a lot of first-level headings. Fixed the heading levels to maintain the symmetry.
> Fixed heading structure to maintain symmetry

- arviz/plots/kdeplot.py
* Added references 
* Added backticks
* Added kwargs functions
Note: `fill_kwargs` are being passed to `fill_func` at a few [lines](https://github.com/arviz-devs/arviz/blob/main/arviz/plots/backends/matplotlib/kdeplot.py#L153), but I could not find it in matplotlib docs. 
Fixes: https://github.com/arviz-devs/arviz/issues/1853
> Added refernces in plot_kde

- CHANGELOG.md
- arviz/plots/forestplot.py
- This PR fixes a type where `Forestplot` was written as `Forestpĺot` in comments, which showed up in online documentation.
> Fix typo in `Forestplot`

- setup.py
Arxviz due to its requirement on xarray>=0.16.1 (and possibly for internal reasons as well) in practice has a hard requirement on the python version of >=3.6. However, it is not declared at the moment in the setup.py so the package resolution doesn't notice this through pypi until attempting to satisfy the xarray requirement.
> Update setup.py to require python >= 3.7

- CHANGELOG.md
- arviz/stats/stats.py
Resolves #1941. Changed the order of regularization of the shape parameter of the generalized Pareto distribution and estimation of scale parameter.
> Change order of regularization in psislw (#1941)

- arviz/tests/base_tests/test_data_zarr.py
- requirements.txt
Fixes #1947. I also had some trouble installing some `requirements-external.txt`, but I didn't include those in the change so far. 
I'll tag @obi1kenobi who originally added this pin, I think it was just defensive against the next major version, but if the mypy checks pass, I think we can merge.
> Unpin typing_extensions

- CHANGELOG.md
- requirements-optional.txt
Follow up from https://github.com/arviz-devs/arviz/pull/1953, set an upper bound to bokeh version
for now until making the change, updating the code and requiring version 3.
> add upper bound to bokeh version

- CHANGELOG.md
- arviz/plots/backends/bokeh/distplot.py
- arviz/plots/backends/bokeh/kdeplot.py
- arviz/plots/backends/bokeh/pairplot.py
- arviz/plots/backends/matplotlib/distplot.py
- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/plots/plot_utils.py
A few lines above we set `x_x` and `y_y` using the min and max along each dimension, so this has no visual effect on the plot, _as long as you are plotting models independently_. I think it is important to remove in order to allow using the kde mode of plot_pair to compare models. Otherwise only the last kde to be plotted is guaranteed to be seen complete, the rest are generally cut or lay completely outside the limits.
> remove manual setting of 2d kde lims

- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
The dims for `hdi_data` are flipped, meaning the function errors when `multimodal=True` and `max_modes` is not used to restrict the number of modes.
Before this change:
```python
arviz.hdi(ads, hdi_prob=.9, multimodal=True)
```
results in
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_1840496/2310952448.py in <module>
----> 1 arviz.hdi(ads, hdi_prob=.9, multimodal=True)
~/mambaforge/envs/astro/lib/python3.9/site-packages/arviz/stats/stats.py in hdi(ary, hdi_prob, circular, multimodal, skipna, group, var_names, filter_vars, coords, max_modes, dask_kwargs, **kwargs)
507 
508     hdi_coord = xr.DataArray(["lower", "higher"], dims=["hdi"], …
```
> Fix stats.hdi for multimodal=True

- CHANGELOG.md
- arviz/plots/backends/bokeh/lmplot.py
- arviz/plots/backends/matplotlib/lmplot.py
- arviz/plots/lmplot.py
The `plot_lm()` function currently allows the user to customize the appearance of every displayed group except for the model mean. This is a simple pull request to enable customization of the model mean line as well.
> Allow kwargs to customize appearance of the mean in `plot_lm`

- doc/_templates/donate.html
- doc/_templates/edit-this-page.html
- doc/_templates/twitter.html
- doc/source/_static/custom.css
- doc/source/conf.py
- requirements-docs.txt
* ~fix codeautolink for code blocks generated from plot directive~ seemed to work locally doesn't seem to work here
* add custom style to code with links
* add edit this page button (but skip it for api as it wouldn't point to the right page)
* add donate button to right sidebar of all pages
* add twitter feed to community page left sidebar
> improve codeautolink style, add edit and donate buttons

- arviz/tests/external_tests/test_data_pyjags.py
> Skip pyjags tests

- arviz/data/base.py
- arviz/tests/base_tests/test_data.py
Coerces the coords parameter of the numpy_to_data_array function into a numpy array using np.asarray.
This patch prevents the function from failing on tuple/list parameters.
Added a new unit test to cover the failing test.
Fixes #1451
> Coerce coords into np.array in numpy_to_data_array

- arviz/data/inference_data.py
Bug: 
idata.extend(another_idata, join='right') returns two copies of every group  - i.e. posterior, prior 
Bug cause:
append should only happen if group not in self
Possible fix - (thanks @OriolAbril )
Note: extend(join='left') works just fine.
Feel free to suggest better fixes or tests or anything needed
> extend 'right' join bug fix

- CHANGELOG.md
- arviz/plots/backends/matplotlib/ppcplot.py
Legend labels were not tracking the selected group. In many instances
they were hardcoded to "Posterior ...".
Addresses #1966.
> Fix legend labels in plot_ppc to reflect prior or posterior.

- MANIFEST.in
- requirements-dev.txt
[PEP 561](https://www.python.org/dev/peps/pep-0561/) describes how packages can tell tools such as `mypy` that they support typechecking.
Essentially there are three options:
* Separately released "stub packages"
* `.pyi` files with stub definitions
* inline type hints and a `py.typed` file
This PR adds a `py.typed` file as shown in the https://github.com/ethanhs/pep-561 example project.
The project structure here is a little different. I hope the line in `MANIFEST.in` is correct?
This way type checking in PyMC etc. should become more exact, even if there are still some inconsistencies left.
> Enabled type checking as described by PEP 561

- arviz/plots/densityplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/base_tests/test_utils.py
`filter_vars` argument added to `plot_density`.
Fixes #1225
> Added filter_vars argument to plot_density

- CHANGELOG.md
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This is an attempt at fixing #1981, in which the subplot axes do not have the same range by default but also lack unique labels. In doing so, I hope to correct some of the counterintuitive behaviour around passing "sharex" or "sharey" as backend parameters. I've written a fix, ~and am in the process of adding unit tests for said fix~ and unit tests for the fix. 
**Update** __(23/02/22)__:
I generated an example plot of the marginals, based on the plotpair example gallery code, to illustrate that the marginal axes now fall in the correct place.
Cf. the old behaviour, where the marginal plot axis ticks are not aligned with the plots beneath them, but the labels are also missing.
(I removed the "new features" documentation from the list because this isn't a new feature, just a bug fix to …
> Fix bug in pair plot axis handling

- arviz/data/inference_data.py
Changed attribute access from getattr to [] in concat to fix arviz-devs/arviz#1993.
I have not changed it in lines 2012/2089 and 2017/2094 where "attrs" are handled.
But I did test concatenating with variables named "attrs" which seems to work.
> Changed attribute access from getattr to []

- CHANGELOG.md
- arviz/data/base.py
- arviz/tests/base_tests/test_data.py
Currently if coordinate values are provided for "default dims" they are ignored.
This is an issue for example in pymc where posterior and posterior predictive are
separate sampling steps and you can choose to thin the posterior if generating
posterior predictive samples is expensive as it prevents the original
draw/chain ids to be preserved as coordinate values of the posterior predictive.
> fix issue when coords for default dims are provided

- CHANGELOG.md
- arviz/plots/backends/bokeh/essplot.py
- arviz/plots/backends/matplotlib/essplot.py
- arviz/plots/essplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
I like to explain why I end up working in a PR in its description, so here goes today's story. I was trying different cut offs with `min_ess` and decided to try the relative ess view too and I realized there min_ess was ignored and the value was hard coded to 400. Once I got to fix that I ended up fixing the threshold line for the relative ess evolution view and their kwargs in bokeh too, mostly due to lack of self control.
> fix min_ess use in relative ess evolution plot

- arviz/__init__.py
It now matches the regex from https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions
> update version string to match PEP guidance

- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/base_tests/test_utils.py
- arviz/tests/helpers.py
- arviz/utils.py
- doc/source/user_guide/plots_arguments_guide.md
This updates the util functions so that variables don't need to be represented as strings. As far as I know
this is the only place in the codebase that assumes it.
> Allow varnames that aren't strings to be used in InferenceData

- README.md
- arviz/plots/kdeplot.py
- arviz/plots/pairplot.py
- doc/source/index.rst
We remove plot_joint some time ago, but we forgot to clean references to it.
> remove plot_joint from docs

- CHANGELOG.md
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
Fixes #2010 by removing the `k_min` threshold below which the tail weights were not smoothed. Now these weights are smoothed unless `k` is `nan` or infinite (indicating failure to fit GPD).
> Smooth weights with psislw even for low shape

- arviz/stats/stats_utils.py
Based on issue #2019 
This PR fixes the BASE_FMT text so that it explicitly states the number of samples and number of points. For instance, instead of `Computed from 4000 by 262 log-likelihood matrix` the message should read `Computed from 4000 samples and 262 points log-likelihood matrix`
> Fix BASE_FMT text to clearly specify sample size

- CHANGELOG.md
- arviz/labels.py
Fix mistake in make_label_flat of baselabeller that broke novarlabeller.
No tests added as there are no tests yet, there is already an issue on this #1574
> fix mistake in baselabeller that breaks novarlabeller

- arviz/plots/backends/matplotlib/dotplot.py
> Use datalim when changing aspect

- arviz/stats/stats.py
It seems arviz allows `pseudo-BMA` instead of `pseudo-MA` as options, this PR corrects this typo.
> Correct a typo in allowed method in `compare`

- arviz/plots/kdeplot.py
I noticed that when overlaying plots (in which case I often use the same kwargs for all of them) the kwargs I was passing were being modified to have the `levels` key. The result was still right because hdi_probs takes preference, but it should not happen as it would result in very unintuitive results if one were to forget hdi_probs in the 2nd or 3rd plot.
> copy kwargs to avoid modifying provided ones

- arviz/plots/backends/bokeh/compareplot.py
- arviz/plots/backends/matplotlib/compareplot.py
- arviz/plots/compareplot.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/base_tests/test_rcparams.py
- arviz/tests/base_tests/test_stats.py
- arviz/tests/base_tests/test_stats_utils.py
This fixes #1989 
* Add a legend
* Make insample_dev False as default
* Add a label to the y-axis
* Make x-axis label clear, indicates what we are computing and the scale
* Add a title with a short description on how to interpret the plot. This is something we have discussed in the past to incorporate to ArviZ inspired by https://easystats.github.io/performance/index.html), in the future we could even have a global rcparams that turn this short guide on and off globally (or even have levels, beginner, intermedia, advanced)
* This also introduce changes in the names of the computed quantities, for example "elpd_loo" instead of just "loo". This is mainly to increase consistency with the loo R package. 
* Update the docstring a little. In the near future ArviZ is going to have an …
> Make plot_compare easy to understand

- doc/source/contributing/contributing_prs.md
- doc/source/contributing/doc_toolchain.md
- doc/source/contributing/index.md
- doc/source/contributing/issue_reports.md
I had an offline discussion with @OriolAbril and made the following changes to the Contributing section of ArviZ python library website. I have introduced the following new sections to improve the clarity of the Contributing guide.
**Welcome** 
Provides a brief introduction to the project.
**Before you begin**
Provides prerequisites for new contributors.
**Communication**
Gitter channel details to help contributors get in touch with the community.
**Contributing to ArviZ**
Identifies multiple ways of contributing to ArviZ
> Modified main page of Contributing section of ArviZ python library website

- CHANGELOG.md
- arviz/plots/hdiplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
In #1968 I pointed out that `az.plot_hdi` failed if `x` was of type `datetime` when `smooth=True`. This PR adds an exception to hopefully make this easier for a user to work out what is going wrong. 
FYI this is my first PR to `arviz`, so apologies if I've missed some steps.
> plot_hdi: add exception if `x` is type `np.datetime64` and `smooth=True`

- CHANGELOG.md
- arviz/plots/pairplot.py
This PR resolves #2073 by removing unused arguments from `plot_pair`
----
:books: Documentation preview :books:: https://arviz--2085.org.readthedocs.build/en/2085/
> Removed fill_last, contour and plot_kwargs arguments

- .github/workflows/rtd_link_description.yaml
Read the Docs repository was renamed from `readthedocs/readthedocs-preview` to `readthedocs/actions/`. Now, the `preview` action is under `readthedocs/actions/preview` and is tagged as `v1`
----
:books: Documentation preview :books:: https://arviz--2091.org.readthedocs.build/en/2091/
> Use Read the Docs action v1

- CHANGELOG.md
- arviz/plots/backends/bokeh/kdeplot.py
- arviz/rcparams.py
- arviz/stats/stats.py
- arvizrc.template
- requirements-docs.txt
- requirements-optional.txt
----
:books: Documentation preview :books:: https://arviz--2104.org.readthedocs.build/en/2104/
> Use contourpy for Bokeh contour plots

- requirements-docs.txt
We forgot to unset the theme requirement to the github version.
----
:books: Documentation preview :books:: https://arviz--2111.org.readthedocs.build/en/2111/
> fix doc requirementts

- README.md
After changing the example gallery image sizes (no thumbnail, change `figsize`), the README doesn't look so great right now 😅 Forgot to update while working on this https://github.com/arviz-devs/arviz/pull/2108 
----
:books: Documentation preview :books:: https://arviz--2113.org.readthedocs.build/en/2113/
> Fix README table column width to resize images

- arviz/data/io_numpyro.py
- arviz/tests/external_tests/test_data_numpyro.py
- arviz/tests/external_tests/test_data_pymc.py
Small change to allow numpyro's converter to also grab names from a namedtuple (the current behavior will name variables of a named tuple `Param:0`, `Param:1`, ...) 
----
:books: Documentation preview :books:: https://arviz--2121.org.readthedocs.build/en/2121/
> Allow numpyro converter to work with namedtuples

- CHANGELOG.md
- arviz/plots/energyplot.py
- arviz/stats/diagnostics.py
- arviz/tests/base_tests/test_diagnostics.py
- arviz/tests/base_tests/test_plots_matplotlib.py
This PR ensures that `bfmi` and `plot_energy` compute the same thing if the named dimensions `(chain, draw)` are instead ordered as `(draw, chain)` and adds a test.
Addresses part of https://github.com/arviz-devs/arviz/issues/2102#issuecomment-1229416637
PR format?
----
:books: Documentation preview :books:: https://arviz--2126.org.readthedocs.build/en/2126/
> Correctly (re)order dimensions for bfmi and plot_energy

- arviz/__init__.py
Hi, the `matplotlib.pyplot.register_cmap` function was [deprecated in Matplotlib 3.6](https://matplotlib.org/stable/api/cm_api.html#matplotlib.cm.register_cmap), for `matplotlib.colormaps.register`. I just made this change, which also works for Matplotlib 3.5 as far as I can tell.
----
:books: Documentation preview :books:: https://arviz--2127.org.readthedocs.build/en/2127/
> Fix deprecation of matplotlib.pyplot.register_cmap

- CHANGELOG.md
- arviz/data/__init__.py
- arviz/data/converters.py
- arviz/data/io_beanmachine.py
- doc/source/api/data.rst
- requirements-external.txt
This addresses #2106 by adding native support for Bean Machine into Arviz. 
More tests and documentation are still needed.
----
:books: Documentation preview :books:: https://arviz--2107.org.readthedocs.build/en/2107/
> WIP: Adding Bean Machine converter to Arviz

- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
Fixes #2079 
Filter out object dtype from compression.
> Compress only a subset of types

- .azure-pipelines/azure-pipelines-external.yml
- CHANGELOG.md
- arviz/data/io_pystan.py
- arviz/tests/external_tests/test_data_pystan.py
- arviz/tests/helpers.py
----
:books: Documentation preview :books:: https://arviz--2132.org.readthedocs.build/en/2132/
> Add save_warmup option for pystan3

- CHANGELOG.md
- arviz/data/base.py
- arviz/tests/base_tests/test_data.py
We have the concept of `default_dims` in dict_to_dataset and related functions,
which are dimensions that come at the beginning and can be omitted from the
dims list _but they can also be there_. This fixes a bug for the case
where the default_dims are present in the dims list (which is necessary
when the default dims are not chain and draw).
----
:books: Documentation preview :books:: https://arviz--2138.org.readthedocs.build/en/2138/
> fix handling of default dims

- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_data_zarr.py
closes #2109 
Save attrs to root level
> Save InferenceData attrs

- CHANGELOG.md
- arviz/plots/traceplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Fixes #2150 by internally reordering dimensions of `diverging` as expected in `plot_trace`.
PR format?
----
:books: Documentation preview :books:: https://arviz--2151.org.readthedocs.build/en/2151/
> Fix dimension ordering for traceplot with divergences

- arviz/plots/styles/arviz-doc.mplstyle
- arviz/plots/styles/arviz-docgrid.mplstyle
- examples/matplotlib/mpl_styles.py
----
:books: Documentation preview :books:: https://arviz--2157.org.readthedocs.build/en/2157/
> rename arviz-doc to arviz-docgrid and make arviz-doc a non-grid style

- CHANGELOG.md
- arviz/stats/__init__.py
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
This function will take a list of idatas with `posterior_predictive` groups and a list of model weights (computed using `az.compare` or something else) and it will return a new inference data with a `posterior_predictive` group composed of weighted samples from the input idatas. 
@zaxtax maybe we can focus on this and forgot about `pm.sample_posterior_predictive_w`
----
:books: Documentation preview :books:: https://arviz--2147.org.readthedocs.build/en/2147/
> Add weight_predictions function

- CHANGELOG.md
- arviz/plots/backends/bokeh/ppcplot.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/ppcplot.py
- arviz/tests/base_tests/test_plots_bokeh.py
- arviz/tests/base_tests/test_plots_matplotlib.py
----
:books: Documentation preview :books:: https://arviz--2161.org.readthedocs.build/en/2161/
> add observed_rug argument to plot_ppc

- CHANGELOG.md
- arviz/plots/ppcplot.py
Make a copy of the dictionary coords, so the input parameter coords is not modified.
This PR is to fix the issue mentioned in issue #2047
----
:books: Documentation preview :books:: https://arviz--2160.org.readthedocs.build/en/2160/
> copy coords before modifying

- arviz/__init__.py
- doc/source/contributing/how_to_release.md
`0.14.0.dev0` is similar to `rc1` flags, they are releases that _precede_ 0.14.0.
I have updated the how-to docs to be more clear, I think we have done this for the last
2 releases.
----
:books: Documentation preview :books:: https://arviz--2166.org.readthedocs.build/en/2166/
> fix version and how-to docs

- CHANGELOG.md
- arviz/data/io_beanmachine.py
- arviz/tests/external_tests/test_data_beanmachine.py
- arviz/tests/helpers.py
This is a bug fix to handle when observations and posterior_predictive is missing from the MonteCarloSamples object
----
:books: Documentation preview :books:: https://arviz--2154.org.readthedocs.build/en/2154/
> Add None for fields not used in beanmachine converter

- CHANGELOG.md
- arviz/plots/lmplot.py
- arviz/stats/diagnostics.py
- arviz/tests/base_tests/test_diagnostics.py
plot_lm used np.tile on the plotter lists which contain 4 elements, a string, two dicts and an
array, somehow coercing all this into a numpy array while doing some repetition of elements
to match x and y values. This always rose many warnings, it now breaks the code and therefore the
tests.
This PR updates this to use lists and itertools all the way to perform the same type of repetitions,
no array features were really used so I think it makes more sense to use lists.
I have also updated the code in _z_scale to work with scipy 1.10 and higher as the nan policy in rankdata has changed.
It does not, tests are already broken due to this so it can't go back.
----
:books: Documentation preview :books:: https://arviz--2186.org.readthedocs.build/en/2186/
> Fix plot_lm and _z_scale for scipy 1.10

- CHANGELOG.md
- doc/source/_static/custom.css
- doc/source/conf.py
- doc/source/contributing/index.md
- requirements-docs.txt
This adds an embedding of the webinar I recently gave about
contributing to ArviZ to the contributing overview page.
----
:books: Documentation preview :books:: https://arviz--2184.org.readthedocs.build/en/2184/
> add contributing webinar

- doc/source/schema/schema.md
The goal is to close #230, close #2048 and close #2064. So even though the fix for #230 has already been voted on #2056, I expect some discussion to happen, especially around the rest of the changes.
I have pushed the branch to arviz repo to make it easy for other people to make changes directly. cc @sethaxen 
I am also making the changes here for now, which should get the most visibility, we can move the page to the arviz-project repo after merging.
- ✅  Follows [official](https://github.com/arviz-devs/arviz/blob/main/CONTRIBUTING.md#pull-request-checklist) PR format
- ❌  New features are properly documented (with an example if appropriate)? It is probably time already to rerun the examples, but I don't plan to do it on this PR.
- 🔲  Changes are listed in …
> start updating schema doc

- arviz/stats/diagnostics.py
There was an issue with scipy 1.10 rc1, so I added this ravel to
get CI green quickly. It should be fixed already in rc2 so there
is no need to keep it.
PR format?
----
:books: Documentation preview :books:: https://arviz--2187.org.readthedocs.build/en/2187/
> remove workaround ravel

- .azure-pipelines/azure-pipelines-external.yml
- .pylintrc
- arviz/data/inference_data.py
- arviz/plots/elpdplot.py
- arviz/tests/base_tests/test_rcparams.py
- requirements.txt
Testing to see what happens if we lower the matplotlib dependency. This is for google colab update
----
:books: Documentation preview :books:: https://arviz--2201.org.readthedocs.build/en/2201/
> Downgrade matplotlib dependency to 3.2 and fix numerous pylint issues

- CHANGELOG.md
- arviz/labels.py
When combining with NoVarLabeller or NoModelLabeller there were some stray
nones being printed. This should fix the issue.
----
:books: Documentation preview :books:: https://arviz--2200.org.readthedocs.build/en/2200/
> fix issue in labeller

- arviz/data/io_pyro.py
- arviz/stats/density_utils.py
- arviz/stats/diagnostics.py
closes #2194 - Clean up references to deprecated NumPy type aliases
Deprecated numpy type aliases were replaced (np.float to float, np.bool to bool) according to the recommendations made in NumPy 1.20.0 Release Notes: https://numpy.org/devdocs/release/1.20.0-notes.html
----
:books: Documentation preview :books:: https://arviz--2204.org.readthedocs.build/en/2204/
> Clean up references to deprecated Numpy type aliases

- CHANGELOG.md
- arviz/data/io_emcee.py
The goal of this change is to prevent large memory consumption during the creation of an InferenceData object from emcee. The change also improves efficiency.
Previously, the full chain was initialized once for each of the variables, leading to long initialization time and a spike in memory usage (my 2.5Gb chain with ~30 dimensions led to 60+Gb of allocated memory, crashing the python process).
----
:books: Documentation preview :books:: https://arviz--2215.org.readthedocs.build/en/2215/
> Fixing unreasonable memory usage when creating an InferenceData object from an emcee sampler

- doc/_templates/edit-this-page.html
- requirements-docs.txt
We use an internal function of the pydata-sphinx-theme to remove
the "Edit this page" button on docstrings. It has been modified
in the latest release so we have to update that template.
----
:books: Documentation preview :books:: https://arviz--2218.org.readthedocs.build/en/2218/
> update to pst latest release

- requirements.txt
Continued effort on trying to get ArviZ updated in colab
WIP until we see what happens with tests
> Lower pandas version

- README.md
Solves issue #2223 via the addition of new images of the plots and a hyperlink which directs the user to the plots webpage.
----
:books: Documentation preview :books:: https://arviz--2224.org.readthedocs.build/en/2224/
> Addition of images to the gallery and a hyperlink on README.md

- CHANGELOG.md
- arviz/plots/backends/matplotlib/bfplot.py
- arviz/plots/bfplot.py
Old:
New:
----
:books: Documentation preview :books:: https://arviz--2237.org.readthedocs.build/en/2237/
> BF plot: Use arviz's kde instead of the one from scipy

- .azure-pipelines/azure-pipelines-base.yml
- README.md
- asv_benchmarks/asv.conf.json
- setup.py
Add 3.11 to CI so we test again with 3 python versions. Also drop support for 3.8 (which hasn't been tested for a while)
----
:books: Documentation preview :books:: https://arviz--2240.org.readthedocs.build/en/2240/
> add 3.11 to CI

- arviz/data/base.py
- arviz/utils.py
Replacement of deprecated pkg_resources, now arviz will use importlib.resources
which will allow to use more strict testing policy in packages importing arviz ( previously because of pkg_resources
failing test on warning was not possible, because each import of arviz was warning about deprecation of pkg_resources)
----
:books: Documentation preview :books:: https://arviz--2241.org.readthedocs.build/en/2241/
> Pkg resources replacement

- CHANGELOG.md
- arviz/tests/base_tests/test_utils_numba.py
- arviz/utils.py
Fix deprecation warning with numba jit.
----
:books: Documentation preview :books:: https://arviz--2246.org.readthedocs.build/en/2246/
> Add default nopython kwarg

- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
----
:books: Documentation preview :books:: https://arviz--2227.org.readthedocs.build/en/2227/
> Added the ability to append an InferenceData object to an existing netCDF file 

- arviz/plots/ppcplot.py
Changed the plot_ppc docstring second instance 'observed' to 'observed_rug'
----
:books: Documentation preview :books:: https://arviz--2255.org.readthedocs.build/en/2255/
> change the second instance 'observed' to 'observed_rug' in the doc string of plot_ppc

- .github/FUNDING.yml
It doesn't make much sense to show tidelift in all repos as it is only related to this
one. I will update https://github.com/arviz-devs/.github/blob/master/FUNDING.yml to have only
numfocus so that continues to appear to all repos by default, but here it will be overriden
to show both as it happens now.
----
:books: Documentation preview :books:: https://arviz--2262.org.readthedocs.build/en/2262/
> add funding metadata

- CHANGELOG.md
- arviz/data/__init__.py
- arviz/data/datasets.py
- arviz/data/inference_data.py
- arviz/data/io_datatree.py
- arviz/tests/base_tests/test_data.py
- doc/source/api/data.rst
- requirements-optional.txt
Adds converters to go back and forth between InferenceData and DataTree.
----
:books: Documentation preview :books:: https://arviz--2253.org.readthedocs.build/en/2253/
> add datatree converters

- arviz/data/base.py
----
:books: Documentation preview :books:: https://arviz--2263.org.readthedocs.build/en/2263/
> Fix extended methods docstrings

- arviz/plots/forestplot.py
- arviz/plots/posteriorplot.py
- doc/source/user_guide/plots_arguments_guide.md
Add the `rope` option to the "Plot's arguments guide" page; this option is available in the forest and posterior plots. Added a link to the page in both arguments' documentation.
Additionally, I removed the forest plot with ropes example from its documentation, to add other examples later
----
:books: Documentation preview :books:: https://arviz--2210.org.readthedocs.build/en/2210/
> Add rope to plots arguments guide

- arviz/plots/backends/bokeh/forestplot.py
- arviz/plots/backends/bokeh/posteriorplot.py
- arviz/plots/backends/matplotlib/forestplot.py
- arviz/stats/density_utils.py
- arviz/stats/stats_utils.py
- arviz/tests/base_tests/test_utils_numba.py
- arviz/utils.py
- requirements.txt
This PR fixes bad numba usage we had been doing which recently started causing errors and warnings.
It also adds a numpy 2.0 cap to avoid issues once it is release (planned to happen around the
end of this year already).
I think this should be included in a patch release for 0.16. However, it would be nice if someone could test locally and confirm that indeed, the numba warnings are gone. cc @guin0x @ahartikainen might also be related to #2244 
----
:books: Documentation preview :books:: https://arviz--2268.org.readthedocs.build/en/2268/
> Minor fixes

- .gitignore
- CHANGELOG.md
- arviz/__init__.py
- doc/source/user_guide/Numba.ipynb
Prepare a patch release to include the numba fixes
----
:books: Documentation preview :books:: https://arviz--2269.org.readthedocs.build/en/2269/
> prepare patch release

- CHANGELOG.md
- requirements.txt
- set matplotlib >=3.5 in requirements.txt
Since https://github.com/arviz-devs/arviz/pull/2127 `arviz/__init__.py` requires matplotlib >= 3.5 for `mpl.colormaps.register()` otherwise `arviz` fails on import.
- add this change to changelog.md
> Set matplotlib >=3.5 in requirements.txt

- CHANGELOG.md
- arviz/labels.py
- arviz/plots/backends/matplotlib/ppcplot.py
- arviz/plots/ppcplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
Modify plot_ppc default labeling and several plot_ppc fixes, mainly working properly when
chain and draw aren't the first dimensions positionally
----
:books: Documentation preview :books:: https://arviz--2283.org.readthedocs.build/en/2283/
> plot_ppc related fixes

- arviz/plots/backends/matplotlib/ppcplot.py
fixes #2282
----
:books: Documentation preview :books:: https://arviz--2289.org.readthedocs.build/en/2289/
> avoid bins='auto' on jitted histogram

- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
Related to #2293 
----
:books: Documentation preview :books:: https://arviz--2295.org.readthedocs.build/en/2295/
> Add `__delitem__` to InferenceData

- README.md
In the README file, the pronoun "it" is missing at the start of the sentence just before the word "includes". Also, the heading for dependencies is not highlighted. I Fixed both.
----
📚 Documentation preview 📚: https://arviz--2310.org.readthedocs.build/en/2310/
> doc:add 'it' and new line before dependencies

- arviz/data/inference_data.py
- doc/source/schema/schema.md
A log_prior group is needed for prior sensitivity checks as described here #2093
----
📚 Documentation preview 📚: https://arviz--2312.org.readthedocs.build/en/2312/
> add log_prior group

- .azure-pipelines/azure-pipelines-benchmarks.yml
- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/data/io_pystan.py
- arviz/plots/backends/bokeh/forestplot.py
- arviz/plots/backends/matplotlib/forestplot.py
Related to #2313. This should fix the bug mentioned in that issue.
With the recent improvements to numba it has become more performant yet more restrictive
to support the performance improvements.
plot_forest had a function that was already using forceobj=True, and now due to the
combination of lists, dicts and .append, numba rejects compiling it (probably wasn't doing much
to begin with in previous versions). So I have removed the conditional_jit part.
----
📚 Documentation preview 📚: https://arviz--2319.org.readthedocs.build/en/2319/
> remove conditional_jit from plot_forest label_idx

- CHANGELOG.md
- arviz/data/__init__.py
- arviz/data/base.py
- arviz/data/converters.py
- arviz/data/io_dict.py
- arviz/plots/backends/matplotlib/pairplot.py
- arviz/tests/base_tests/test_data.py
- requirements.txt
This also makes `from_dict` work for nested dictionaries. I joined the keys with double underscores because using a `.` would break attribute access (like, it would still work, but you'd use `idata.posterior['var.x.y']`, instead of `idata.posterior.var__x__y`)
Hopefully this is a no-op for most code, but it should make arviz work automatically with namedtuples or dataclasses. 
----
:books: Documentation preview :books:: https://arviz--2291.org.readthedocs.build/en/2291/
> Make `from_dict` more flexible, and add `from_pytree`

- arviz/stats/density_utils.py
closes #2330
PR format?
----
📚 Documentation preview 📚: https://arviz--2332.org.readthedocs.build/en/2332/
> fix gaussian import from scipy

- arviz/data/base.py
- arviz/data/inference_data.py
Fix for datetime deprecation issue and standardizing timezone(UTC) and format(isoformat) for datetime updates on concatenating InferenceData (issue #2327 )
The `"created_at"` default attribute in the make_attrs function in `arviz/data/base.py` is updated to avoid deprecation as well as work for Python 3.10, which is still supported by ArviZ. 
The `current_time` variable in the concat function in `arviz/data/inference-data.py` is also updated to use the UTC timezone and is isoformatted. 
----
📚 Documentation preview 📚: https://arviz--2329.org.readthedocs.build/en/2329/
> Fix for datetime deprecation and standardizing timezone and isoformat (Issue #2327)

- CHANGELOG.md
- arviz/data/inference_data.py
- doc/source/api/inference_data.rst
Closes #2337 
Adds a `close` method to `arviz.InferenceData` that simply extends from `xarray.Dataset.close`.
----
📚 Documentation preview 📚: https://arviz--2338.org.readthedocs.build/en/2338/
> Add a close method to InferenceData

- arviz/data/io_numpyro.py
Removes extra copy to reduce memory requirements for large models/datasets.   If the copy is desirable for a reason I missed feel free to delete this.  Let me know if any changes are needed
As a side note the default automatic numpyro log-likelihood calculation was a bit of a surprise (as far as unexpected memory explosions go).
----
📚 Documentation preview 📚: https://arviz--2347.org.readthedocs.build/en/2347/
> remove extra copy of log-likelihood in NumPyroConverter

- .azure-pipelines/azure-pipelines-base.yml
- .azure-pipelines/azure-pipelines-external.yml
- CHANGELOG.md
- arviz/plots/plot_utils.py
- arviz/tests/base_tests/test_data.py
- arviz/tests/base_tests/test_data_zarr.py
- arviz/tests/base_tests/test_diagnostics_numba.py
- arviz/tests/base_tests/test_helpers.py
- arviz/tests/base_tests/test_plot_utils.py
- arviz/tests/base_tests/test_stats_numba.py
- arviz/tests/base_tests/test_utils_numba.py
- arviz/tests/external_tests/test_data_pystan.py
- arviz/tests/helpers.py
- requirements.txt
The initial goal of the PR was to test if ArviZ was already compatible with numpy 2.0 (which had just been pre-released as a beta version). Several dependencies weren't compatible yet, so it wasn't feasible to do. While waiting for this, we also saw ArviZ wasn't compatible with the latest scipy pre-release https://github.com/arviz-devs/arviz/issues/2330, and the fix wasn't released before the actual release, generating many more issues like https://github.com/arviz-devs/arviz/issues/2336. Moreover, even though the goal is to follow SPEC 0 guidance on dependency minimum version, having numba as optional dependency in fact pushes us the other way around, it often takes months after the release of a minor python version until we can incorporate it into our CI.
To try and handle all this, …
> Update testing environments

- .azure-pipelines/azure-pipelines-benchmarks.yml
- .pylintrc
- arviz/stats/stats.py
- arviz/tests/base_tests/test_stats.py
- asv_benchmarks/asv.conf.json
There are some CI errors due to the new pylint version and the pandas 3.0 + numpy 2.1 nightlies.
----
📚 Documentation preview 📚: https://arviz--2351.org.readthedocs.build/en/2351/
> fix ci errors

- CHANGELOG.md
- arviz/plots/backends/bokeh/khatplot.py
- arviz/plots/backends/matplotlib/khatplot.py
- arviz/plots/khatplot.py
- arviz/stats/stats.py
- arviz/stats/stats_utils.py
The newest revision of the PSIS paper now recommends:
* "good" ---------> k < min(1 - 1/log10(S), 0.7) 
* "bad" -----------> min(1 - 1/log10(S), 0.7) <= k < 1 
* "very bad"  ---> k > 1
----
📚 Documentation preview 📚: https://arviz--2349.org.readthedocs.build/en/2349/
> Use revised Pareto k threshold

- CHANGELOG.md
- arviz/plots/backends/bokeh/ecdfplot.py
- arviz/plots/backends/matplotlib/ecdfplot.py
- arviz/plots/bpvplot.py
- arviz/plots/densityplot.py
- arviz/plots/dotplot.py
- arviz/plots/ecdfplot.py
- arviz/plots/forestplot.py
- arviz/plots/hdiplot.py
- arviz/plots/loopitplot.py
- arviz/plots/posteriorplot.py
- arviz/plots/violinplot.py
- arviz/rcparams.py
- arviz/stats/ecdf_utils.py
- arviz/stats/stats.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/base_tests/test_rcparams.py
- arviz/tests/helpers.py
- arviz/utils.py
- arvizrc.template
- doc/source/getting_started/Introduction.ipynb
- doc/source/user_guide/plots_arguments_guide.md
- examples/matplotlib/mpl_plot_ecdf.py
This PR introduces new keyword arguments to `plot_ecdf` and deprecates a few existing ones, following suggestions in #2309.
New keywords and features:
- `confidence_bands` now may take string arguments as well as boolean
- `ci_prob` specifies band probability. `stats.ci_prob` is a new rcParam.
- `eval_points` allows the user to specify the evaluation points
- `rvs`, `random_state` can be provided for simulation confidence bands
Deprecated arguments:
- `values2` is now deprecated, in favor of users passing an empirical CDF
Deprecated keywords:
- `pointwise` is now `confidence_bands="pointwise"`
- `fpr` is replaced with `1-ci_prob` for consistency with other plotting functions.
- `pit` is deprecated. We only need this for LOO-PIT, users who need it for something else will probably know how …
> Refactor plot_ecdf arguments

- arviz/data/io_cmdstan.py
Fixes #2353 
Parse string bool values in CmdStan csv header.
----
📚 Documentation preview 📚: https://arviz--2354.org.readthedocs.build/en/2354/
> Parse string bool values in CmdStan csv header

- arviz/stats/diagnostics.py
The docstring for ``rhat`` provides an incorrect formula for $\hat{R}$ which is missing the square root. The expression should be:
$$\hat{R} = \sqrt{\frac{\hat{V}}{W}}.$$
The implementation of the function uses the square root.
This pull request fixes the typo.
----
📚 Documentation preview 📚: https://arviz--2355.org.readthedocs.build/en/2355/
> Fix typo in docstring for rhat: take square root of ratio of variance estimates

- .gitignore
- CHANGELOG.md
- arviz/plots/backends/bokeh/pairplot.py
----
📚 Documentation preview 📚: https://arviz--2362.org.readthedocs.build/en/2362/
> fix bokeh deprecation

- CHANGELOG.md
- arviz/__init__.py
- arviz/preview.py
- setup.py
----
📚 Documentation preview 📚: https://arviz--2361.org.readthedocs.build/en/2361/
> expose new features as preview submodule

- doc/source/contributing/plotting_backends.md
Change path of function provided in [documentation](https://python.arviz.org/en/latest/contributing/plotting_backends.html) to right path.
Fixed incorrect path provided for the `get_plotting_function()` provided in [documentation](https://python.arviz.org/en/latest/contributing/plotting_backends.html) as `arviz.plots.get_plotting_function`  to correct path - `arviz.plots.plot_utils.get_plotting_function`
----
📚 Documentation preview 📚: https://arviz--2364.org.readthedocs.build/en/2364/
> Update `plotting_backends.md` with correct path for function

- arviz/stats/stats.py
- doc/source/conf.py
----
📚 Documentation preview 📚: https://arviz--2366.org.readthedocs.build/en/2366/
> update docstring for loo and waic

- CHANGELOG.md
- doc/source/contributing/index.md
- doc/source/contributing/pr_tutorial.md
In the documentation [Contributions](https://python.arviz.org/en/latest/contributing/index.html) page, when I tried to open the pull request hyperlink in the **"Write documentation"** and **"Make changes in the code"** sections, it is redirecting to [https://www.pymc.io/projects/docs/en/stable/contributing/pr_tutorial.html#pr-tutorial](https://www.pymc.io/projects/docs/en/stable/contributing/pr_tutorial.html#pr-tutorial) page, but in actual it should redirect to [https://python.arviz.org/en/latest/contributing/pr_tutorial.html#pr-tutorial](https://python.arviz.org/en/latest/contributing/pr_tutorial.html#pr-tutorial)
Link to issue: [Issue in the documentation](https://github.com/arviz-devs/arviz/issues/2369)
----
📚 Documentation preview 📚: https://arviz--2370.org.readthedocs.build/en/2370/
> Fix the issue in the Contribution References Documentation

- CHANGELOG.md
- arviz/plots/ecdfplot.py
- arviz/stats/ecdf_utils.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- arviz/tests/base_tests/test_stats_ecdf_utils.py
This pull request adds the optimization method from https://doi.org/10.1007/s11222-022-10090-6 for computing simultaneous ECDF bands and ~switches to using it as the default approach~ uses it as the default approach sometimes based on a heuristic. 
Part of #2309. The changes are non-breaking, since the docstring of `plot_ecdf` intentionally does not document which method is the default.
```python
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt
np.random.seed(0)
dist = scipy.stats.expon()
x = dist.rvs(1000)
eval_points = np.linspace(0, 10, 100)
fig, axs = plt.subplots(2, 1, figsize=(8, 5))
%time az.plot_ecdf(x, ax=axs[0], eval_points=eval_points, confidence_bands=True, cdf=dist.cdf, difference=True)
%time az.plot_ecdf(x, ax=axs[1], …
```
> Add optimized simultaneous ECDF bands

- arviz/stats/stats.py
closes #2376 
----
📚 Documentation preview 📚: https://arviz--2377.org.readthedocs.build/en/2377/
> copy psislw input

- arviz/data/base.py
- arviz/data/converters.py
- arviz/tests/base_tests/test_data.py
- requirements-docs.txt
- requirements-optional.txt
- requirements.txt
`dm-tree` dependency is only used to support pytree objects like nested dicts which 
is not very common and is also very localized in the codebase, being only used via
either `dict_to_dataset` or `from_dict` (both also having the dict->pytree alternative naming).
I would like to keep dependencies for base functionality to something more basic so
we can for example use arviz via pyodide. Also in preparation to `arviz-xyz` refactoring
where anything not required throughout the library is an optional dependency.
----
📚 Documentation preview 📚: https://arviz--2379.org.readthedocs.build/en/2379/
> make dm-tree optional

- arviz/plots/forestplot.py
In the forestplot the central points are the median not the mean. At least, this is what it seems from the [code](https://github.com/arviz-devs/arviz/blob/eb692cb11069405395cbc9fe389938161788ba77/arviz/plots/backends/matplotlib/forestplot.py#L411) of forest plot. Furthermore, I have fixed a typo in the formula in the same attribute's text
----
📚 Documentation preview 📚: https://arviz--2385.org.readthedocs.build/en/2385/
> Fix documentation forestplot

- arviz/plots/backends/matplotlib/kdeplot.py
- arviz/plots/kdeplot.py
Closes #2382
An "extra" contour is plotted by default, when passing hdi_probs or when passing an integer to `levels`.  This little change "fix" the issue. Not entirely happy with the solution
----
📚 Documentation preview 📚: https://arviz--2383.org.readthedocs.build/en/2383/
> 2kde use hdi_probs by default

- arviz/plots/backends/__init__.py
Resolves the crash described in https://github.com/arviz-devs/arviz/issues/2392, occuring when python -OO strips the  `__doc__` attribute
----
📚 Documentation preview 📚: https://arviz--2393.org.readthedocs.build/en/2393/
> handle python -OO

- CHANGELOG.md
- arviz/data/inference_data.py
- arviz/tests/base_tests/test_data.py
Only emit a warning for custom groups when explicitly requested.
As InferenceData gets more uses, data related to the model but not specifically defined
in the schema is also stored as independent groups, which is perfectly fine and doesn't break
anything but it is annoying to get all the warnings or having to silence them constantly.
Moreover, this is set to not happen in `arviz-base` so it will also align behaviour.
----
📚 Documentation preview 📚: https://arviz--2401.org.readthedocs.build/en/2401/
> Allow custom groups without warnings

- arviz/preview.py
- doc/source/api/index.rst
- doc/source/api/preview.md
- doc/source/api/preview.rst
- doc/source/getting_started/Installation.rst
Improve behaviour of `arviz.preview` module
----
📚 Documentation preview 📚: https://arviz--2398.org.readthedocs.build/en/2398/
> Robustify preview module

- CHANGELOG.md
- examples/bokeh/bokeh_plot_ecdf_comparison.py
- examples/matplotlib/mpl_plot_ecdf_comparison.py
Aiming to add a new example of ecdf comparison but the band computation seems to have a bug.
----
:books: Documentation preview :books:: https://arviz--2178.org.readthedocs.build/en/2178/
> add ecdf comparison plot

- arviz/plots/backends/bokeh/bpvplot.py
- arviz/plots/backends/matplotlib/bpvplot.py
- arviz/plots/bpvplot.py
Add a parameter smoothing, default as True, to toggle smoothing on data with integer type.
----
📚 Documentation preview 📚: https://arviz--2344.org.readthedocs.build/en/2344/
> [WIP] Add a parameter to enable/disable smoothing on discrete variables in BLV (Issue #2325)

- CHANGELOG.md
- arviz/plots/hdiplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
It does not seem that categorical (str) type x values are supported by `az.plot_hdi` but the documentation for the function is not clear here and no exception is raised if x is type str (i.e. in the case of an ANOVA type model). Here, I've contributed the following:
- A TypeError if x is a str to `plot_hdi`
- Added test to `test_plots_matplotlib.py` following the example of #2016. 
For now, I prefix the PR with [WIP] to invite input on whether or not to include this lack of support for str type x in the function documentation -- and because this is my first go at contributing to a repository of this caliber...
Fixes #2412 
- 2025-01-19 21:18: My own test was failing, I had misplaced the `raise` statement. Relocated & amended the commit with force-push to keep a concise history.
----
📚 …
> `plot_hdi` raise exception when `x` is string (#2412)

- CHANGELOG.md
- arviz/__init__.py
- arviz/utils.py
----
📚 Documentation preview 📚: https://arviz--2434.org.readthedocs.build/en/2434/
> Prepare release

- arviz/stats/density_utils.py
- arviz/wrappers/base.py
- arviz/wrappers/wrap_stan.py
- doc/source/contributing/content_structure.md
- doc/source/contributing/docstrings.md
Fixed a few more typos while I was reading through the source code.
----
📚 Documentation preview 📚: https://arviz--2449.org.readthedocs.build/en/2449/
> Fixed various typos

- CHANGELOG.md
- requirements-dev.txt
I noticed that you are using type annotations (which is great), and `scipy-stubs` can help make that a bit ~easier~ less difficult :)
----
📚 Documentation preview 📚: https://arviz--2445.org.readthedocs.build/en/2445/
> add `scipy-stubs` as development dependency

- arviz/stats/stats.py
Adds option to not normalize log weights from Pareto smoothed importance sampling. This is useful when the scale of the weights are to be preserved (e.g., importance sampling against an unnormalized distribution).
----
📚 Documentation preview 📚: https://arviz--2455.org.readthedocs.build/en/2455/
> optional normalization for psislw

- arviz/data/inference_data.py
- arviz/data/io_datatree.py
- arviz/tests/base_tests/test_data.py
- doc/source/conf.py
- requirements-optional.txt
Fix an example that was broken with the changes in xarray-einstats
to support preliz and the new scipy distributions
and have `to/from_datatree` methods use xarray instead of xarray-datatree discontinued library.
----
📚 Documentation preview 📚: https://arviz--2458.org.readthedocs.build/en/2458/
> Use datatree from xarray and update example to latest einstats

- arviz/plots/autocorrplot.py
- arviz/tests/base_tests/test_plots_matplotlib.py
- examples/matplotlib/mpl_plot_autocorr.py
**Fixes #2288**
Added the `coords` keyword argument to the `plot_autocorr` function in ArviZ. Used to specify variable names to be plotted. Made it consistent with other plotting functions such as plot_forest and plot_trace.
```python
axes = az.plot_autocorr(
data,
var_names=["mu", "theta"],
coords={"school": ["Deerfield", "Hotchkiss"]},
backend="matplotlib"
)
```
- Test case added -> `test_plot_autocorr_coord`
- Example for plot_autocorr modifed to show utility of the coords keyword.
----
📚 Documentation preview 📚: https://arviz--2404.org.readthedocs.build/en/2404/
> Coords kwarg added to plot_autocorr function

- CHANGELOG.md
- arviz/data/io_numpyro.py
- arviz/tests/external_tests/test_data_numpyro.py
Closes https://github.com/arviz-devs/arviz/issues/2468 by flipping the sign of "potential_energy" when renaming to `lp`.
----
📚 Documentation preview 📚: https://arviz--2470.org.readthedocs.build/en/2470/
> fix for numpyro potential energy sign

- arviz/stats/stats.py
I noticed in https://github.com/scipy/scipy-stubs/pull/881#issuecomment-3287359942 that there's a minor mypy issue in `arviz.stats.stats.compare` where the `weights` name is used for multiple types. That's affects how mypy infers the `weights` type as, which is what *eventually* led to these two reported mypy errors. As you can see, the error messages are rather confusing, and are reported at a different location. So I figured I'd spare you the debugging effort, and might as well fix it myself 🤷🏻 
----
📚 Documentation preview 📚: https://arviz--2477.org.readthedocs.build/en/2477/
> fix minor typing issue in `stats.stats.compare`

- arviz/plots/forestplot.py
Fixes the typo in `plot_forest()` docs. Resolves [#2472](https://github.com/arviz-devs/arviz/issues/2472).
----
📚 Documentation preview 📚: https://arviz--2479.org.readthedocs.build/en/2479/
> Fix typo for forest plot docs
